const prContiniusPerfectPassive = [
    ["Why is the road being repaired?", "The road is being repaired because of the damage.", "The road was repaired last year.", "The road has been repaired recently.", "The road is repaired every year.", "Почему дорогу ремонтируют?", "Чому дорогу ремонтують?", "Dlaczego droga jest naprawiana?"],  
    ["Why is the house being painted?", "The house is being painted to refresh its look.", "The house was painted last summer.", "The house has been painted this week.", "The house is painted every five years.", "Почему дом красят?", "Чому будинок фарбують?", "Dlaczego dom jest malowany?"],  
    ["Why are the documents being checked?", "The documents are being checked for errors.", "The documents were checked yesterday.", "The documents have been checked already.", "The documents are checked every month.", "Почему документы проверяют?", "Чому документи перевіряють?", "Dlaczego dokumenty są sprawdzane?"],  
    ["Why is the bridge being built?", "The bridge is being built to improve traffic.", "The bridge was built last decade.", "The bridge has been built recently.", "The bridge is built when needed.", "Почему строят мост?", "Чому будують міст?", "Dlaczego most jest budowany?"],  
    ["Why is the meeting being recorded?", "The meeting is being recorded for future reference.", "The meeting was recorded last week.", "The meeting has been recorded.", "The meeting is recorded every time.", "Почему встречу записывают?", "Чому зустріч записують?", "Dlaczego spotkanie jest nagrywane?"],  
    ["Why is the street being cleaned?", "The street is being cleaned after the storm.", "The street was cleaned yesterday.", "The street has been cleaned this morning.", "The street is cleaned daily.", "Почему улицу убирают?", "Чому вулицю прибирають?", "Dlaczego ulica jest sprzątana?"],  
    ["Why are the walls being repaired?", "The walls are being repaired because they are damaged.", "The walls were repaired last month.", "The walls have been repaired recently.", "The walls are repaired when necessary.", "Почему стены ремонтируют?", "Чому стіни ремонтують?", "Dlaczego ściany są naprawiane?"],  
    ["Why is the computer being fixed?", "The computer is being fixed due to a system error.", "The computer was fixed last night.", "The computer has been fixed already.", "The computer is fixed when it breaks.", "Почему компьютер чинят?", "Чому комп'ютер ремонтують?", "Dlaczego komputer jest naprawiany?"],  
    ["Why is the road being expanded?", "The road is being expanded to reduce traffic jams.", "The road was expanded in 2015.", "The road has been expanded recently.", "The road is expanded when needed.", "Почему дорогу расширяют?", "Чому дорогу розширюють?", "Dlaczego droga jest poszerzana?"],  
    ["Why is the law being changed?", "The law is being changed due to new regulations.", "The law was changed two years ago.", "The law has been changed recently.", "The law is changed when necessary.", "Почему закон меняют?", "Чому закон змінюють?", "Dlaczego prawo jest zmieniane?"],  
    ["Why is the contract being reviewed?", "The contract is being reviewed for legal accuracy.", "The contract was reviewed last week.", "The contract has been reviewed already.", "The contract is reviewed every year.", "Почему контракт проверяют?", "Чому контракт перевіряють?", "Dlaczego umowa jest sprawdzana?"],  
    ["Why is the museum being renovated?", "The museum is being renovated to attract more visitors.", "The museum was renovated in 2018.", "The museum has been renovated recently.", "The museum is renovated every decade.", "Почему музей реставрируют?", "Чому музей реставрують?", "Dlaczego muzeum jest odnawiane?"],  
    ["Why is the garden being watered?", "The garden is being watered to keep the plants healthy.", "The garden was watered this morning.", "The garden has been watered already.", "The garden is watered daily.", "Почему сад поливают?", "Чому сад поливають?", "Dlaczego ogród jest podlewany?"],  
    ["Why is the software being updated?", "The software is being updated for better security.", "The software was updated last month.", "The software has been updated recently.", "The software is updated regularly.", "Почему обновляют программное обеспечение?", "Чому оновлюють програмне забезпечення?", "Dlaczego oprogramowanie jest aktualizowane?"],  
    ["Why is the window being replaced?", "The window is being replaced because it was broken.", "The window was replaced last week.", "The window has been replaced.", "The window is replaced when needed.", "Почему заменяют окно?", "Чому замінюють вікно?", "Dlaczego okno jest wymieniane?"],  
    ["Why is the floor being cleaned?", "The floor is being cleaned because it was dirty.", "The floor was cleaned yesterday.", "The floor has been cleaned today.", "The floor is cleaned every morning.", "Почему пол моют?", "Чому миють підлогу?", "Dlaczego podłoga jest myta?"],  
    ["Why is the wall being painted?", "The wall is being painted to refresh the look.", "The wall was painted two years ago.", "The wall has been painted recently.", "The wall is painted every few years.", "Почему стену красят?", "Чому фарбують стіну?", "Dlaczego ściana jest malowana?"],  
    ["Why is the stadium being constructed?", "The stadium is being constructed for the upcoming event.", "The stadium was constructed in 2020.", "The stadium has been constructed recently.", "The stadium is constructed when needed.", "Почему строят стадион?", "Чому будують стадіон?", "Dlaczego stadion jest budowany?"],  
    ["Why is the book being translated?", "The book is being translated for a wider audience.", "The book was translated last year.", "The book has been translated recently.", "The book is translated when needed.", "Почему переводят книгу?", "Чому перекладають книгу?", "Dlaczego książka jest tłumaczona?"],  
    ["Why is the building being demolished?", "The building is being demolished for safety reasons.", "The building was demolished in 2019.", "The building has been demolished recently.", "The building is demolished when necessary.", "Почему здание сносят?", "Чому зносять будівлю?", "Dlaczego budynek jest burzony?"],  
    ["Why is the car being tested?", "The car is being tested for safety standards.", "The car was tested last week.", "The car has been tested already.", "The car is tested every year.", "Почему тестируют машину?", "Чому тестують машину?", "Dlaczego samochód jest testowany?"],  
    ["Why is the statue being restored?", "The statue is being restored due to weather damage.", "The statue was restored in 2015.", "The statue has been restored recently.", "The statue is restored when needed.", "Почему реставрируют статую?", "Чому реставрують статую?", "Dlaczego posąg jest odnawiany?"],
    ["Have they cleaned the office?", "The office has been cleaned.", "The office was cleaned yesterday.", "The office is cleaned every morning.", "The office is being cleaned right now.", "Они убрали офис?", "Вони прибрали офіс?", "Czy biuro zostało posprzątane?"],  
    ["Has she finished the report?", "The report has been finished.", "The report was finished last night.", "The report is finished every Friday.", "The report is being finished at the moment.", "Она закончила отчет?", "Вона закінчила звіт?", "Czy raport został ukończony?"],  
    ["Have they repaired the bridge?", "The bridge has been repaired.", "The bridge was repaired last year.", "The bridge is repaired when necessary.", "The bridge is being repaired now.", "Они отремонтировали мост?", "Вони відремонтували міст?", "Czy most został naprawiony?"],  
    ["Has the manager signed the contract?", "The contract has been signed.", "The contract was signed last month.", "The contract is signed by the manager every year.", "The contract is being signed right now.", "Менеджер подписал контракт?", "Менеджер підписав контракт?", "Czy menedżer podpisał umowę?"],  
    ["Have they delivered the package?", "The package has been delivered.", "The package was delivered this morning.", "The package is delivered every week.", "The package is being delivered at the moment.", "Они доставили посылку?", "Вони доставили посилку?", "Czy paczka została dostarczona?"],  
    ["Has she cooked dinner?", "Dinner has been cooked.", "Dinner was cooked an hour ago.", "Dinner is cooked every evening.", "Dinner is being cooked right now.", "Она приготовила ужин?", "Вона приготувала вечерю?", "Czy kolacja została ugotowana?"],  
    ["Have they published the article?", "The article has been published.", "The article was published last week.", "The article is published in the newspaper monthly.", "The article is being published at the moment.", "Они опубликовали статью?", "Вони опублікували статтю?", "Czy artykuł został opublikowany?"],  
    ["Has he completed the project?", "The project has been completed.", "The project was completed in 2022.", "The project is completed every quarter.", "The project is being completed now.", "Он завершил проект?", "Він завершив проєкт?", "Czy projekt został ukończony?"],  
    ["Have they painted the house?", "The house has been painted.", "The house was painted last summer.", "The house is painted every five years.", "The house is being painted right now.", "Они покрасили дом?", "Вони пофарбували будинок?", "Czy dom został pomalowany?"],  
    ["Have they repaired the road?", "The road has been repaired.", "The road was repaired last month.", "The road is repaired when necessary.", "The road is being repaired now.", "Они отремонтировали дорогу?", "Вони відремонтували дорогу?", "Czy droga została naprawiona?"],
    ["Has he fixed the computer?", "The computer has been fixed.", "The computer was fixed last night.", "The computer is fixed when necessary.", "The computer is being fixed at the moment.", "Он починил компьютер?", "Він полагодив комп'ютер?", "Czy komputer został naprawiony?"],  
    ["Have they printed the documents?", "The documents have been printed.", "The documents were printed yesterday.", "The documents are printed for every meeting.", "The documents are being printed right now.", "Они распечатали документы?", "Вони роздрукували документи?", "Czy dokumenty zostały wydrukowane?"],  
    ["Has the book been translated?", "The book has been translated.", "The book was translated two years ago.", "The book is translated when needed.", "The book is being translated at the moment.", "Книга была переведена?", "Книгу було перекладено?", "Czy książka została przetłumaczona?"],  
    ["Has the city improved the park?", "The park has been improved.", "The park was improved last summer.", "The park is improved every few years.", "The park is being improved right now.", "Город улучшил парк?", "Місто покращило парк?", "Czy park został ulepszony?"],  
    ["Has the chef prepared the meal?", "The meal has been prepared.", "The meal was prepared an hour ago.", "The meal is prepared daily.", "The meal is being prepared now.", "Шеф-повар приготовил еду?", "Шеф-кухар приготував їжу?", "Czy posiłek został przygotowany?"],  
    ["Have they opened the new store?", "The new store has been opened.", "The new store was opened last month.", "The new store is opened every Monday.", "The new store is being opened today.", "Они открыли новый магазин?", "Вони відкрили новий магазин?", "Czy nowy sklep został otwarty?"],  
    ["Has the company launched the product?", "The product has been launched.", "The product was launched last year.", "The product is launched after testing.", "The product is being launched now.", "Компания запустила продукт?", "Компанія запустила продукт?", "Czy produkt został uruchomiony?"],  
    ["Have they decorated the hall?", "The hall has been decorated.", "The hall was decorated last night.", "The hall is decorated for every event.", "The hall is being decorated at the moment.", "Они украсили зал?", "Вони прикрасили зал?", "Czy sala została udekorowana?"],  
    ["Has the police arrested the suspect?", "The suspect has been arrested.", "The suspect was arrested this morning.", "The suspect is arrested when found.", "The suspect is being arrested now.", "Полиция арестовала подозреваемого?", "Поліція заарештувала підозрюваного?", "Czy podejrzany został aresztowany?"],  
    ["Has the manager approved the proposal?", "The proposal has been approved.", "The proposal was approved last week.", "The proposal is approved every quarter.", "The proposal is being approved right now.", "Менеджер утвердил предложение?", "Менеджер затвердив пропозицію?", "Czy propozycja została zatwierdzona?"],  
    ["Have they renovated the building?", "The building has been renovated.", "The building was renovated in 2020.", "The building is renovated every decade.", "The building is being renovated right now.", "Они отремонтировали здание?", "Вони відремонтували будівлю?", "Czy budynek został odnowiony?"],  
    ["Has the teacher checked the exams?", "The exams have been checked.", "The exams were checked last Friday.", "The exams are checked every semester.", "The exams are being checked at the moment.", "Учитель проверил экзамены?", "Вчитель перевірив іспити?", "Czy egzaminy zostały sprawdzone?"],  
    ["Has the team finished the task?", "The task has been finished.", "The task was finished yesterday.", "The task is finished at the end of the week.", "The task is being finished now.", "Команда завершила задание?", "Команда завершила завдання?", "Czy zadanie zostało ukończone?"],  
    ["Have they restored the painting?", "The painting has been restored.", "The painting was restored in 2018.", "The painting is restored when necessary.", "The painting is being restored right now.", "Они восстановили картину?", "Вони відновили картину?", "Czy obraz został odrestaurowany?"],  
    ["Has the factory produced the new model?", "The new model has been produced.", "The new model was produced last quarter.", "The new model is produced every year.", "The new model is being produced right now.", "Фабрика произвела новую модель?", "Фабрика виробила нову модель?", "Czy nowy model został wyprodukowany?"],  
    ["Have they updated the system?", "The system has been updated.", "The system was updated last month.", "The system is updated regularly.", "The system is being updated now.", "Они обновили систему?", "Вони оновили систему?", "Czy system został zaktualizowany?"],  
    ["Has the hospital admitted the patient?", "The patient has been admitted.", "The patient was admitted last night.", "The patient is admitted when needed.", "The patient is being admitted at the moment.", "Больница приняла пациента?", "Лікарня прийняла пацієнта?", "Czy pacjent został przyjęty?"],  
    ["Has the government passed the law?", "The law has been passed.", "The law was passed in 2021.", "The law is passed when necessary.", "The law is being passed now.", "Правительство приняло закон?", "Уряд прийняв закон?", "Czy ustawa została uchwalona?"],  
    ["Has the scientist discovered a new element?", "A new element has been discovered.", "A new element was discovered last decade.", "New elements are discovered rarely.", "A new element is being discovered right now.", "Ученый открыл новый элемент?", "Вчений відкрив новий елемент?", "Czy nowy pierwiastek został odkryty?"],  
    ["Has the airline canceled the flight?", "The flight has been canceled.", "The flight was canceled this morning.", "Flights are canceled due to weather conditions.", "The flight is being canceled now.", "Авиакомпания отменила рейс?", "Авіакомпанія скасувала рейс?", "Czy lot został odwołany?"],

];

    // Если это свойство есть, то оно попадает в заголовок теста
    prContiniusPerfectPassive.nameLeson = "is being done/has been done";

    // Свойство показывает сколько индексов содержат правильные предложения
    // Если его нет, то будет считаться, что правильные предложения 
    // только индекс 0 и 1. Если 5 - это индексы 0,1,2,3,4 с правильно
    // созданными предложениями.
    prContiniusPerfectPassive.lengthTrue = 5;

