const presentContinuous = [
        ["She is ... to music.", "listening", "listenning", "listens", "listened", "Она слушает музыку.", "Вона слухає музику.", "Ona słucha muzyki."],
        ["They are ... football.", "playing", "play", "played", "plays", "Они играют в футбол.", "Вони грають у футбол.", "Oni grają w piłkę nożną."],
        ["I am ... a letter.", "writing", "write", "writes", "written", "Я пишу письмо.", "Я пишу листа.", "Piszę list."],
        ["We are ... dinner.", "having", "have", "has", "had", "Мы ужинаем.", "Ми вечеряємо.", "Mamy kolację."],
        ["The cat is ... on the couch.", "sleeping", "sleepping", "sleeps", "slept", "Кот спит на диване.", "Кіт спить на дивані.", "Kot śpi na kanapie."],
        ["He is ... a book.", "reading", "read", "readding", "readed", "Он читает книгу.", "Він читає книгу.", "On czyta książkę."],
        ["She is ... the piano.", "playing", "play", "plays", "played", "Она играет на пианино.", "Вона грає на піаніно.", "Ona gra na pianinie."],
        ["We are ... a movie.", "watching", "watch", "watches", "watched", "Мы смотрим фильм.", "Ми дивимось фільм.", "Oglądamy film."],
        ["They are ... in the park.", "walking", "walkking", "walks", "walked", "Они гуляют в парке.", "Вони гуляють у парку.", "Oni spacerują po parku."],
        ["I am ... for the bus.", "waiting", "waitting", "waits", "waited", "Я жду автобус.", "Я чекаю на автобус.", "Czekam na autobus."],
        ["She is ... a cake.", "baking", "bake", "bakes", "baked", "Она печёт торт.", "Вона пече торт.", "Ona piecze ciasto."],
        ["He is ... the car.", "driving", "drive", "drives", "drived", "Он ведёт машину.", "Він водить машину.", "On prowadzi samochód."],
        ["They are ... the room.", "cleaning", "clean", "cleans", "cleaned", "Они убирают комнату.", "Вони прибирають кімнату.", "Oni sprzątają pokój."],
        ["I am ... breakfast.", "eating", "eat", "eats", "ate", "Я завтракаю.", "Я снідаю.", "Jem śniadanie."],
        ["She is ... to the store.", "going", "go", "goes", "gone", "Она идёт в магазин.", "Вона йде в магазин.", "Ona idzie do sklepu."],
        ["We are ... the news.", "watching", "watch", "watches", "watched", "Мы смотрим новости.", "Ми дивимось новини.", "Oglądamy wiadomości."],
        ["They are ... a story.", "telling", "tell", "tells", "told", "Они рассказывают историю.", "Вони розповідають історію.", "Oni opowiadają historię."],
        ["I am ... to you.", "talking", "talk", "talks", "talked", "Я разговариваю с тобой.", "Я розмовляю з тобою.", "Rozmawiam z tobą."],
        ["She is ... in the garden.", "working", "work", "works", "worked", "Она работает в саду.", "Вона працює в саду.", "Ona pracuje w ogrodzie."],
        ["He is ... to his friend.", "writing", "write", "writes", "writed", "Он пишет своему другу.", "Він пише своєму другу.", "On pisze do swojego przyjaciela."],
        ["They are ... their homework.", "doing", "do", "does", "did", "Они делают домашнее задание.", "Вони роблять домашнє завдання.", "Oni robią swoje zadanie domowe."],
        ["We are ... on the project.", "working", "work", "works", "worked", "Мы работаем над проектом.", "Ми працюємо над проектом.", "Pracujemy nad projektem."],
        ["I am ... the dishes.", "washing", "wash", "washes", "washed", "Я мою посуд.", "Я мию посуд.", "Myję naczynia."],
        ["She is ... the dog.", "feeding", "feed", "feeds", "feeded", "Она кормит собаку.", "Вона годує собаку.", "Ona karmi psa."],
        ["He is ... the table.", "setting", "set", "sets", "seting", "Он накрывает на стол.", "Він накриває на стіл.", "On nakrywa do stołu."],
        ["They are ... the house.", "cleaning", "clean", "cleans", "cleaned", "Они убирают дом.", "Вони прибирають будинок.", "Oni sprzątają dom."],
        ["I am ... my bed.", "making", "make", "makes", "made", "Я заправляю свою постель.", "Я заправляю своє ліжко.", "Ścielę łóżko."],
        ["She is ... to the teacher.", "talking", "talk", "talks", "talked", "Она разговаривает с учителем.", "Вона розмовляє з учителем.", "Ona rozmawia z nauczycielem."],
        ["He is ... a sandwich.", "making", "make", "makes", "made", "Он делает бутерброд.", "Він робить бутерброд.", "On robi kanapkę."],
        ["We are ... the room.", "decorating", "decorate", "decorates", "decorated", "Мы украшаем комнату.", "Ми прикрашаємо кімнату.", "Dekorujemy pokój."],
        ["They are ... a new song.", "singing", "sing", "sings", "sang", "Они поют новую песню.", "Вони співають нову пісню.", "Oni śpiewają nową piosenkę."],
        ["I am ... for a walk.", "going", "go", "goes", "went", "Я иду на прогулку.", "Я йду на прогулянку.", "Idę na spacer."],
        ["She is ... her homework.", "doing", "do", "does", "did", "Она делает домашнее задание.", "Вона робить домашнє завдання.", "Ona robi swoje zadanie domowe."],
        ["He is ... a picture.", "drawing", "draw", "draws", "drawed", "Он рисует картину.", "Він малює картину.", "On rysuje obrazek."],
        ["They are ... for the meeting.", "preparing", "prepare", "prepares", "prepared", "Они готовятся к встрече.", "Вони готуються до зустрічі.", "Przygotowują się do spotkania."],
        ["We are ... the house.", "painting", "paint", "paints", "painted", "Мы красим дом.", "Ми фарбуємо будинок.", "Malujemy dom."],
        ["I am ... my teeth.", "brushing", "brush", "brushes", "brushed", "Я чищу зубы.", "Я чищу зуби.", "Myję zęby."],
        ["She is ... the clothes.", "washing", "wash", "washes", "washed", "Она стирает одежду.", "Вона пере одяг.", "Ona pierze ubrania."],
        ["He is ... the trash.", "taking out", "take out", "takes out", "took out", "Он выносит мусор.", "Він виносить сміття.", "Wynosi śmieci."],
        ["They are ... to the airport.", "driving", "drive", "drives", "drove", "Они едут в аэропорт.", "Вони їдуть до аеропорту.", "Jadą na lotnisko."],
        ["We are ... dinner.", "cooking", "cook", "cooks", "cooked", "Мы готовим ужин.", "Ми готуємо вечерю.", "Gotujemy kolację."],
        ["I am ... for my keys.", "looking", "look", "looks", "looked", "Я ищу свои ключи.", "Я шукаю свої ключі.", "Szukam swoich kluczy."],
        ["She is ... at the moment.", "working", "work", "works", "worked", "Она сейчас работает.", "Вона зараз працює.", "Ona teraz pracuje."],
        ["He is ... his car.", "washing", "wash", "washes", "washed", "Он моет свою машину.", "Він миє свою машину.", "On myje swój samochód."],
        ["They are ... a new game.", "playing", "play", "plays", "played", "Они играют в новую игру.", "Вони грають у нову гру.", "Oni grają w nową grę."],
        ["We are ... the room.", "cleaning", "clean", "cleans", "cleaned", "Мы убираем комнату.", "Ми прибираємо кімнату.", "Sprzątamy pokój."],
        ["I am ... a call.", "making", "make", "makes", "made", "Я совершаю звонок.", "Я телефоную.", "Dzwonię."],
        ["She is ... breakfast.", "cooking", "cook", "cooks", "cooked", "Она готовит завтрак.", "Вона готує сніданок.", "Ona gotuje śniadanie."],
        ["He is ... his shoes.", "tying", "tie", "ties", "tied", "Он завязывает свои ботинки.", "Він зав'язує свої черевики.", "On wiąże buty."],
        ["They are ... the table.", "setting", "set", "sets", "seting", "Они накрывают на стол.", "Вони накривають на стіл.", "Oni nakrywają do stołu."],
        ["We are ... lunch.", "having", "have", "has", "had", "Мы обедаем.", "Ми обідаємо.", "Mamy obiad."],
        ["I am ... to music.", "listening", "listen", "listens", "listened", "Я слушаю музыку.", "Я слухаю музику.", "Słucham muzyki."],
        ["She is ... the floor.", "cleaning", "clean", "cleans", "cleaned", "Она моет пол.", "Вона миє підлогу.", "Ona sprząta podłogę."],
        ["He is ... a new book.", "reading", "read", "reads", "readed", "Он читает новую книгу.", "Він читає нову книгу.", "On czyta nową książkę."],
        ["They are ... to the concert.", "going", "go", "goes", "went", "Они идут на концерт.", "Вони йдуть на концерт.", "Idą na koncert."],
        ["We are ... the report.", "writing", "write", "writes", "writed", "Мы пишем отчёт.", "Ми пишемо звіт.", "Piszemy raport."],
        ["I am ... my shoes.", "putting on", "puting on", "puts on", "putted on", "Я надеваю ботинки.", "Я взуваю черевики.", "Zakładam buty."],
        ["She is ... for a walk.", "going", "go", "goes", "gone", "Она идёт на прогулку.", "Вона йде на прогулянку.", "Ona idzie na spacer."],
        ["He is ... on the phone.", "talking", "talk", "talks", "talked", "Он разговаривает по телефону.", "Він розмовляє по телефону.", "Rozmawia przez telefon."],
        ["They are ... a birthday party.", "having", "have", "has", "had", "Они устраивают вечеринку по случаю дня рождения.", "Вони влаштовують вечірку з нагоди дня народження.", "Mają przyjęcie urodzinowe."],
        ["We are ... the kitchen.", "cleaning", "clean", "cleans", "cleaned", "Мы убираем кухню.", "Ми прибираємо кухню.", "Sprzątamy kuchnię."],
        ["I am ... to the gym.", "going", "go", "goes", "gone", "Я иду в спортзал.", "Я йду в спортзал.", "Idę na siłownię."],
        ["She is ... a cake.", "baking", "bake", "bakes", "baked", "Она печёт торт.", "Вона пече торт.", "Ona piecze ciasto."],
        ["He is ... the table.", "setting", "set", "sets", "seting", "Он накрывает на стол.", "Він накриває на стіл.", "On nakrywa do stołu."],
        ["They are ... the garden.", "watering", "water", "waters", "watered", "Они поливают сад.", "Вони поливають сад.", "Podlewają ogród."],
        ["We are ... the house.", "painting", "paint", "paints", "painted", "Мы красим дом.", "Ми фарбуємо будинок.", "Malujemy dom."],
        ["I am ... a coffee.", "making", "make", "makes", "made", "Я готовлю кофе.", "Я готую каву.", "Robię kawę."],
        ["She is ... for her friend.", "waiting", "wait", "waits", "waited", "Она ждёт своего друга.", "Вона чекає на свого друга.", "Ona czeka na swojego przyjaciela."],
        ["He is ... on a new project.", "working", "work", "works", "worked", "Он работает над новым проектом.", "Він працює над новим проєктом.", "Pracuje nad nowym projektem."],
        ["They are ... their homework.", "doing", "do", "does", "did", "Они делают домашнее задание.", "Вони роблять домашнє завдання.", "Oni robią zadanie domowe."],
        ["We are ... a meeting.", "having", "have", "has", "had", "Мы проводим встречу.", "Ми проводимо зустріч.", "Mamy spotkanie."],
        ["I am ... a new recipe.", "trying", "try", "tries", "tried", "Я пробую новый рецепт.", "Я пробую новий рецепт.", "Próbuję nowego przepisu."],
        ["She is ... at a photo.", "looking", "look", "looks", "looked", "Она смотрит на фотографию.", "Вона дивиться на фотографію.", "Ona patrzy na zdjęcie."],
        ["He is ... to the teacher.", "talking", "talk", "talks", "talked", "Он разговаривает с учителем.", "Він розмовляє з учителем.", "Rozmawia z nauczycielem."],
        ["They are ... to their parents.", "writing", "write", "writes", "writed", "Они пишут своим родителям.", "Вони пишуть своїм батькам.", "Piszą do swoich rodziców."],
        ["We are ... the dishes.", "washing", "wash", "washes", "washed", "Мы моем посуду.", "Ми миємо посуд.", "Myjemy naczynia."],
        ["I am ... a picture.", "drawing", "draw", "draws", "drawed", "Я рисую картину.", "Я малюю картину.", "Rysuję obrazek."],
        ["She is ... the bed.", "making", "make", "makes", "made", "Она заправляет кровать.", "Вона заправляє ліжко.", "Ścieli łóżko."],
        ["He is ... a song.", "singing", "sing", "sings", "sang", "Он поёт песню.", "Він співає пісню.", "Śpiewa piosenkę."],
        ["They are ... a presentation.", "giving", "give", "gives", "gave", "Они проводят презентацию.", "Вони проводять презентацію.", "Prezentują."],
        ["We are ... the window.", "cleaning", "clean", "cleans", "cleaned", "Мы моем окно.", "Ми миємо вікно.", "Czyścimy okno."],
        ["I am ... a cake.", "baking", "bake", "bakes", "baked", "Я пеку торт.", "Я печу торт.", "Piekę ciasto."],
        ["She is ... the house.", "decorating", "decorate", "decorates", "decorated", "Она украшает дом.", "Вона прикрашає будинок.", "Dekoruje dom."],
        ["He is ... the grass.", "cutting", "cut", "cuting", "cutted", "Он косит траву.", "Він косить траву.", "Kosi trawę."],
        ["They are ... on a new book.", "working", "work", "works", "worked", "Они работают над новой книгой.", "Вони працюють над новою книгою.", "Pracują nad nową książką."],
        ["We are ... the report.", "typing", "type", "types", "typed", "Мы печатаем отчёт.", "Ми друкуємо звіт.", "Piszą raport."],
        ["I am ... for my friend.", "waiting", "wait", "waits", "waited", "Я жду своего друга.", "Я чекаю на свого друга.", "Czekam na swojego przyjaciela."],
        ["She is ... the room.", "cleaning", "clean", "cleans", "cleaned", "Она убирает комнату.", "Вона прибирає кімнату.", "Sprząta pokój."],
        ["He is ... a sandwich.", "eating", "eat", "eats", "ate", "Он ест бутерброд.", "Він їсть бутерброд.", "Je kanapkę."],
        ["They are ... the flowers.", "watering", "water", "waters", "watered", "Они поливают цветы.", "Вони поливають квіти.", "Podlewają kwiaty."],
        ["We are ... the car.", "washing", "wash", "washes", "washed", "Мы моем машину.", "Ми миємо машину.", "Myją samochód."],
        ["I am ... breakfast.", "having", "have", "has", "had", "Я завтракаю.", "Я снідаю.", "Mam śniadanie."],
        ["She is ... the cat.", "feeding", "feed", "feeds", "feeded", "Она кормит кота.", "Вона годує кота.", "Karmi kota."],
        ["He is ... the suitcase.", "packing", "pack", "packs", "packed", "Он упаковывает чемодан.", "Він пакує валізу.", "Pakuje walizkę."],
        ["They are ... the fence.", "painting", "paint", "paints", "painted", "Они красят забор.", "Вони фарбують паркан.", "Malują płot."],
        ["We are ... a picnic.", "having", "have", "has", "had", "Мы устраиваем пикник.", "Ми влаштовуємо пікнік.", "Mamy piknik."],
        ["I am ... to a podcast.", "listening", "listen", "listens", "listened", "Я слушаю подкаст.", "Я слухаю подкаст.", "Słucham podcastu."],
        ["She is ... the floor.", "sweeping", "sweep", "sweeps", "sweeped", "Она подметает пол.", "Вона підмітає підлогу.", "Zamiata podłogę."],
        ["He is ... the window.", "cleaning", "clean", "cleans", "cleaned", "Он моет окно.", "Він миє вікно.", "Myje okno."],
        ["They are ... a new recipe.", "trying", "try", "tries", "tried", "Они пробуют новый рецепт.", "Вони пробують новий рецепт.", "Próbują nowego przepisu."],
        ["We are ... the report.", "writing", "write", "writes", "writed", "Мы пишем отчёт.", "Ми пишемо звіт.", "Piszemy raport."],
        ["I am ... a letter.", "writing", "write", "writes", "writed", "Я пишу письмо.", "Я пишу листа.", "Piszę list."],
        ["She is ... the cake.", "decorating", "decorate", "decorates", "decorated", "Она украшает торт.", "Вона прикрашає торт.", "Dekoruje tort."],
        ["He is ... the room.", "painting", "paint", "paints", "painted", "Он красит комнату.", "Він фарбує кімнату.", "Malują pokój."],
        ["They are ... a dog.", "walking", "walk", "walks", "walked", "Они выгуливают собаку.", "Вони вигулюють собаку.", "Wyprowadzają psa."],
        ["We are ... lunch.", "eating", "eat", "eats", "ate", "Мы обедаем.", "Ми обідаємо.", "Jemy obiad."],
        ["I am ... for a run.", "going", "go", "goes", "gone", "Я иду на пробежку.", "Я йду на пробіжку.", "Idę pobiegać."],
        ["She is ... the car.", "washing", "wash", "washes", "washed", "Она моет машину.", "Вона миє машину.", "Myje samochód."],
        ["He is ... for a bus.", "waiting", "wait", "waits", "waited", "Он ждёт автобус.", "Він чекає на автобус.", "Czeka na autobus."],
        ["They are ... a puzzle.", "solving", "solve", "solves", "solved", "Они решают головоломку.", "Вони вирішують головоломку.", "Rozwiązują zagadkę."],
        ["We are ... to music.", "listening", "listen", "listens", "listened", "Мы слушаем музыку.", "Ми слухаємо музику.", "Słuchamy muzyki."],
        ["I am ... the plant.", "watering", "water", "waters", "watered", "Я поливаю растение.", "Я поливаю рослину.", "Podlewam roślinę."],
        ["She is ... a movie.", "watching", "watch", "watches", "watched", "Она смотрит фильм.", "Вона дивиться фільм.", "Ogląda film."],
        ["He is ... his shoes.", "tying", "tie", "ties", "tied", "Он завязывает ботинки.", "Він зав'язує черевики.", "Wiąże buty."],
        ["They are ... their clothes.", "washing", "wash", "washes", "washed", "Они стирают свою одежду.", "Вони перуть свій одяг.", "Piorą swoje ubrania."],
        ["We are ... the homework.", "doing", "do", "does", "did", "Мы делаем домашнее задание.", "Ми робимо домашнє завдання.", "Odrabiamy pracę domową."],
        ["I am ... for dinner.", "cooking", "cook", "cooks", "cooked", "Я готовлю ужин.", "Я готую вечерю.", "Gotuję obiad."],
        ["She is ... her room.", "cleaning", "clean", "cleans", "cleaned", "Она убирает свою комнату.", "Вона прибирає свою кімнату.", "Sprząta swój pokój."],
        ["He is ... to a podcast.", "listening", "listen", "listens", "listened", "Он слушает подкаст.", "Він слухає подкаст.", "Słucha podcastu."],
        ["They are ... the groceries.", "buying", "buy", "buys", "bought", "Они покупают продукты.", "Вони купують продукти.", "Kupują zakupy."],
        ["We are ... the door.", "painting", "paint", "paints", "painted", "Мы красим дверь.", "Ми фарбуємо двері.", "Malujemy drzwi."],
        ["I am ... my phone.", "charging", "charge", "charges", "charged", "Я заряжаю телефон.", "Я заряджаю телефон.", "Ładuję telefon."],
        ["She is ... the present.", "wrapping", "wraping", "wraps", "wrapped", "Она заворачивает подарок.", "Вона загортає подарунок.", "Ona pakuje prezent."],
        ["He is ... a photo.", "taking", "take", "takes", "took", "Он фотографирует.", "Він фотографує.", "Robi zdjęcie."],
        ["They are ... to their friend.", "talking", "talk", "talks", "talked", "Они разговаривают со своим другом.", "Вони розмовляють зі своїм другом.", "Rozmawiają ze swoim przyjacielem."],
        ["We are ... to the station.", "going", "go", "goes", "gone", "Мы идём на станцию.", "Ми йдемо на станцію.", "Idziemy na stację."],
        ["I am ... my hair.", "washing", "wash", "washes", "washed", "Я мою волосы.", "Я мию волосся.", "Myję włosy."],
        ["She is ... her shoes.", "polishing", "polish", "polishes", "polished", "Она чистит ботинки.", "Вона чистить черевики.", "Czyści buty."],
        ["He is ... his car.", "repairing", "repair", "repairs", "repaired", "Он ремонтирует свою машину.", "Він ремонтує свою машину.", "Naprawia samochód."],
        ["They are ... the house.", "decorating", "decorate", "decorates", "decorated", "Они украшают дом.", "Вони прикрашають будинок.", "Dekorują dom."],
        ["We are ... the tree.", "decorating", "decorate", "decorates", "decorated", "Мы украшаем дерево.", "Ми прикрашаємо дерево.", "Dekorujemy choinkę."],
        ["I am ... for work.", "getting ready", "geting ready", "gets ready", "got ready", "Я готовлюсь к работе.", "Я готуюсь до роботи.", "Przygotowuję się do pracy."],
        ["She is ... her room.", "cleaning", "clean", "cleans", "cleaned", "Она убирает свою комнату.", "Вона прибирає свою кімнату.", "Sprząta swój pokój."],
        ["He is ... the letter.", "writing", "write", "writes", "writed", "Он пишет письмо.", "Він пише листа.", "Pisze list."],
        ["They are ... the house.", "decorating", "decorate", "decorates", "decorated", "Они украшают дом.", "Вони прикрашають будинок.", "Dekorują dom."],
        ["We are ... a puzzle.", "solving", "solve", "solves", "solved", "Мы решаем головоломку.", "Ми вирішуємо головоломку.", "Rozwiązujemy zagadkę."],
        ["I am ... my shoes.", "tying", "tie", "ties", "tied", "Я завязываю ботинки.", "Я зав'язую черевики.", "Wiążę buty."],
        ["She is ... a letter.", "writing", "write", "writes", "writed", "Она пишет письмо.", "Вона пише листа.", "Pisze list."],
        ["He is ... his hair.", "cutting", "cut", "cuts", "cuting", "Он стрижёт волосы.", "Він стриже волосся.", "Obcina włosy."],
        ["They are ... a house.", "buying", "buy", "buys", "bought", "Они покупают дом.", "Вони купують будинок.", "Kupują dom."],
        ["We are ... the movie.", "watching", "watch", "watches", "watched", "Мы смотрим фильм.", "Ми дивимось фільм.", "Oglądamy film."],
        ["I am ... for a bus.", "waiting", "wait", "waits", "waited", "Я жду автобус.", "Я чекаю на автобус.", "Czekam na autobus."],
        ["She is ... to the teacher.", "talking", "talk", "talks", "talked", "Она разговаривает с учителем.", "Вона розмовляє з учителем.", "Rozmawia z nauczycielem."],
        ["He is ... his room.", "cleaning", "clean", "cleans", "cleaned", "Он убирает свою комнату.", "Він прибирає свою кімнату.", "Sprząta swój pokój."],
        ["They are ... the flowers.", "watering", "water", "waters", "watered", "Они поливают цветы.", "Вони поливають квіти.", "Podlewają kwiaty."],
        ["We are ... the party.", "organizing", "organize", "organizes", "organized", "Мы организуем вечеринку.", "Ми організовуємо вечірку.", "Organizujemy imprezę."],
        ["I am ... a new skill.", "learning", "learn", "learns", "learned", "Я изучаю новый навык.", "Я вивчаю нову навичку.", "Uczę się nowej umiejętności."],
        ["She is ... for work.", "getting ready", "get ready", "geting ready", "got ready", "Она готовится к работе.", "Вона готується до роботи.", "Przygotowuje się do pracy."],
        ["He is ... the bed.", "making", "make", "makes", "made", "Он заправляет кровать.", "Він заправляє ліжко.", "Ścieli łóżko."],
        ["They are ... the new project.", "starting", "start", "starts", "started", "Они начинают новый проект.", "Вони починають новий проект.", "Zaczynają nowy projekt."],
        ["We are ... the movie.", "watching", "watch", "watches", "watched", "Мы смотрим фильм.", "Ми дивимося фільм.", "Oglądamy film."],
        ["I am ... my room.", "cleaning", "clean", "cleans", "cleaned", "Я убираю свою комнату.", "Я прибираю свою кімнату.", "Sprzątam swój pokój."],
        ["She is ... the door.", "closing", "close", "closes", "closed", "Она закрывает дверь.", "Вона зачиняє двері.", "Zamyka drzwi."],
        ["He is ... his shoes.", "polishing", "polish", "polishes", "polished", "Он чистит ботинки.", "Він чистить черевики.", "Czyści buty."],
        ["They are ... the report.", "finishing", "finish", "finishes", "finished", "Они заканчивают отчёт.", "Вони закінчують звіт.", "Kończą raport."],
        ["We are ... the puzzle.", "solving", "solve", "solves", "solved", "Мы решаем головоломку.", "Ми вирішуємо головоломку.", "Rozwiązujemy zagadkę."],
        ["I am ... the garden.", "watering", "water", "waters", "watered", "Я поливаю сад.", "Я поливаю сад.", "Podlewam ogród."],
        ["She is ... her homework.", "doing", "do", "does", "did", "Она делает домашнее задание.", "Вона робить домашнє завдання.", "Odrabia pracę domową."],
        ["He is ... for a walk.", "going", "go", "goes", "gone", "Он идёт на прогулку.", "Він йде на прогулянку.", "Idzie na spacer."],
        ["They are ... the car.", "cleaning", "clean", "cleans", "cleaned", "Они моют машину.", "Вони миють машину.", "Myją samochód."],
        ["We are ... the new game.", "playing", "play", "plays", "played", "Мы играем в новую игру.", "Ми граємо в нову гру.", "Gramy w nową grę."],
        ["I am ... my friend.", "calling", "call", "calls", "called", "Я звоню своему другу.", "Я телефоную своєму другу.", "Dzwonię do swojego przyjaciela."],
        ["She is ... a picture.", "painting", "paint", "paints", "painted", "Она рисует картину.", "Вона малює картину.", "Maluję obrazek."],
        ["He is ... the homework.", "doing", "do", "does", "did", "Он делает домашнее задание.", "Він робить домашнє завдання.", "Odrabia pracę domową."],
        ["They are ... a letter.", "writing", "write", "writes", "writed", "Они пишут письмо.", "Вони пишуть листа.", "Piszą list."],
        ["We are ... for a run.", "going", "go", "goes", "gone", "Мы идём на пробежку.", "Ми йдемо на пробіжку.", "Idziemy pobiegać."],
        ["I am ... a picture.", "drawing", "draw", "draws", "drawed", "Я рисую картину.", "Я малюю картину.", "Rysuję obrazek."],
        ["She is ... a puzzle.", "solving", "solve", "solves", "solved", "Она решает головоломку.", "Вона розв'язує головоломку.", "Rozwiązuje zagadkę."],
        ["He is ... his breakfast.", "eating", "eat", "eats", "ate", "Он ест свой завтрак.", "Він їсть свій сніданок.", "Je swoje śniadanie."],
        ["They are ... their hair.", "cutting", "cut", "cuts", "cuting", "Они стригут свои волосы.", "Вони стрижуть своє волосся.", "Obcinają swoje włosy."],
        ["We are ... the house.", "decorating", "decorate", "decorates", "decorated", "Мы украшаем дом.", "Ми прикрашаємо будинок.", "Dekorujemy dom."],
        ["I am ... my shoes.", "polishing", "polish", "polishes", "polished", "Я чищу ботинки.", "Я чищу черевики.", "Czyszczę buty."],
        ["She is ... to her friend.", "talking", "talk", "talks", "talked", "Она разговаривает со своей подругой.", "Вона розмовляє зі своєю подругою.", "Rozmawia ze swoją przyjaciółką."],
        ["He is ... for a walk.", "going", "go", "goes", "gone", "Он идёт на прогулку.", "Він іде на прогулянку.", "Idzie na spacer."],
        ["They are ... the new project.", "starting", "start", "starts", "started", "Они начинают новый проект.", "Вони починають новий проєкт.", "Zaczynają nowy projekt."],
        ["We are ... the room.", "cleaning", "clean", "cleans", "cleaned", "Мы убираем комнату.", "Ми прибираємо кімнату.", "Sprzątamy pokój."],
        ["I am ... for the bus.", "waiting", "wait", "waits", "waited", "Я жду автобус.", "Я чекаю на автобус.", "Czekam na autobus."],
        ["She is ... the house.", "cleaning", "clean", "cleans", "cleaned", "Она убирает дом.", "Вона прибирає будинок.", "Sprząta dom."],
        ["He is ... the new song.", "listening", "listen", "listens", "listened", "Он слушает новую песню.", "Він слухає нову пісню.", "Słucha nowej piosenki."],
        ["They are ... the cake.", "decorating", "decorate", "decorates", "decorated", "Они украшают торт.", "Вони прикрашають торт.", "Dekorują tort."],
        ["We are ... to a movie.", "going", "go", "goes", "gone", "Мы идём в кино.", "Ми йдемо в кіно.", "Idziemy do kina."],
        ["I am ... the dog.", "feeding", "feed", "feeds", "feeded", "Я кормлю собаку.", "Я годую собаку.", "Karmię psa."],
        ["She is ... the report.", "writing", "write", "writes", "writed", "Она пишет отчёт.", "Вона пише звіт.", "Pisze raport."],
        ["He is ... the suitcase.", "packing", "pack", "packs", "packed", "Он упаковывает чемодан.", "Він пакує валізу.", "Pakuje walizkę."],
        ["They are ... the windows.", "cleaning", "clean", "cleans", "cleaned", "Они моют окна.", "Вони миють вікна.", "Myją okna."],
        ["We are ... a new book.", "writing", "write", "writes", "writed", "Мы пишем новую книгу.", "Ми пишемо нову книгу.", "Piszą nową książkę."],
        ["I am ... a coffee.", "making", "make", "makes", "made", "Я делаю кофе.", "Я роблю каву.", "Robię kawę."],
        ["She is ... for a walk.", "going", "go", "goes", "gone", "Она идёт на прогулку.", "Вона йде на прогулянку.", "Idzie na spacer."],
        ["He is ... his hair.", "cutting", "cut", "cuting", "cutted", "Он стрижёт свои волосы.", "Він стриже своє волосся.", "Obcina swoje włosy."],
        ["They are ... the new game.", "playing", "play", "plays", "played", "Они играют в новую игру.", "Вони грають у нову гру.", "Grają w nową grę."],
        ["We are ... the plant.", "watering", "water", "waters", "watered", "Мы поливаем растение.", "Ми поливаємо рослину.", "Podlewamy roślinę."],
        ["I am ... the flowers.", "watering", "water", "waters", "watered", "Я поливаю цветы.", "Я поливаю квіти.", "Podlewam kwiaty."],
        ["She is ... the puzzle.", "solving", "solve", "solves", "solved", "Она решает головоломку.", "Вона розв'язує головоломку.", "Rozwiązuje zagadkę."],
        ["He is ... a new language.", "learning", "learn", "learns", "learned", "Он изучает новый язык.", "Він вивчає нову мову.", "Uczy się nowego języka."],
        ["They are ... the new project.", "starting", "start", "starts", "started", "Они начинают новый проект.", "Вони починають новий проєкт.", "Zaczynają nowy projekt."],
        ["We are ... the car.", "washing", "wash", "washes", "washed", "Мы моем машину.", "Ми миємо машину.", "Myjemy samochód."],
        ["I am ... the door.", "closing", "close", "closes", "closed", "Я закрываю дверь.", "Я зачиняю двері.", "Zamykam drzwi."],
        ["She is ... the present.", "wrapping", "wrap", "wraping", "wrapped", "Она заворачивает подарок.", "Вона загортає подарунок.", "Pakuje prezent."],
        ["He is ... the plant.", "watering", "water", "waters", "watered", "Он поливает растение.", "Він поливає рослину.", "Podlewa roślinę."],
        ["They are ... the groceries.", "buying", "buy", "buys", "bought", "Они покупают продукты.", "Вони купують продукти.", "Kupują zakupy."],
        ["We are ... the new house.", "decorating", "decorate", "decorates", "decorated", "Мы украшаем новый дом.", "Ми прикрашаємо новий будинок.", "Dekorujemy nowy dom."],
        ["I am ... the windows.", "cleaning", "clean", "cleans", "cleaned", "Я мою окна.", "Я мию вікна.", "Myję okna."],
        ["She is ... the movie.", "watching", "watch", "watches", "watched", "Она смотрит фильм.", "Вона дивиться фільм.", "Ogląda film."],
        ["He is ... the report.", "writing", "write", "writes", "writed", "Он пишет отчёт.", "Він пише звіт.", "Pisze raport."],
        ["They are ... the car.", "cleaning", "clean", "cleans", "cleaned", "Они моют машину.", "Вони миють машину.", "Myją samochód."],
        ["We are ... the house.", "decorating", "decorate", "decorates", "decorated", "Мы украшаем дом.", "Ми прикрашаємо будинок.", "Dekorujemy dom."],
        ["I am ... for a run.", "going", "go", "goes", "gone", "Я иду на пробежку.", "Я йду на пробіжку.", "Idę pobiegać."],
        ["She is ... the suitcase.", "packing", "pack", "packs", "packed", "Она упаковывает чемодан.", "Вона пакує валізу.", "Pakuje walizkę."],
        ["He is ... to music.", "listening", "listen", "listens", "listened", "Он слушает музыку.", "Він слухає музику.", "Słucha muzyki."],
        ["They are ... to the teacher.", "talking", "talk", "talks", "talked", "Они разговаривают с учителем.", "Вони розмовляють з учителем.", "Rozmawiają z nauczycielem."],
        ["We are ... the house.", "cleaning", "clean", "cleans", "cleaned", "Мы убираем дом.", "Ми прибираємо будинок.", "Sprzątamy dom."],
        ["I am ... the present.", "wrapping", "wrap", "wraping", "wrapped", "Я заворачиваю подарок.", "Я загортаю подарунок.", "Pakuję prezent."],
        ["She is ... her hair.", "washing", "wash", "washes", "washed", "Она моет свои волосы.", "Вона миє своє волосся.", "Myje swoje włosy."],
        ["He is ... to the teacher.", "talking", "talk", "talks", "talked", "Он разговаривает с учителем.", "Він розмовляє з учителем.", "Rozmawia z nauczycielem."],
        ["They are ... a letter.", "writing", "write", "writes", "writed", "Они пишут письмо.", "Вони пишуть листа.", "Piszą list."],
        ["We are ... to the park.", "going", "go", "goes", "gone", "Мы идём в парк.", "Ми йдемо до парку.", "Idziemy do parku."],
        ["I am ... my shoes.", "polishing", "polish", "polishes", "polished", "Я чищу ботинки.", "Я чищу черевики.", "Czyszczę buty."],
        ["She is ... the cake.", "decorating", "decorate", "decorates", "decorated", "Она украшает торт.", "Вона прикрашає торт.", "Dekoruje tort."],
        ["He is ... for the bus.", "waiting", "wait", "waits", "waited", "Он ждёт автобус.", "Він чекає на автобус.", "Czeka na autobus."],
        ["They are ... the movie.", "watching", "watch", "watches", "watched", "Они смотрят фильм.", "Вони дивляться фільм.", "Oglądają film."],
        ["We are ... the room.", "cleaning", "clean", "cleans", "cleaned", "Мы убираем комнату.", "Ми прибираємо кімнату.", "Sprzątamy pokój."],
        ["I am ... for work.", "getting ready", "get ready", "geting ready", "got ready", "Я готовлюсь к работе.", "Я готуюсь до роботи.", "Przygotowuję się do pracy."],
        ["She is ... a new language.", "learning", "learn", "learns", "learned", "Она изучает новый язык.", "Вона вивчає нову мову.", "Uczy się nowego języka."],
        ["He is ... the new project.", "starting", "start", "starts", "started", "Он начинает новый проект.", "Він починає новий проект.", "Zaczyna nowy projekt."],
        ["They are ... a picture.", "drawing", "draw", "draws", "drawed", "Они рисуют картину.", "Вони малюють картину.", "Rysują obrazek."],
        ["We are ... for the party.", "getting ready", "geting ready", "gets ready", "got ready", "Мы готовимся к вечеринке.", "Ми готуємося до вечірки.", "Przygotowujemy się na imprezę."],
        ["I am ... the cake.", "decorating", "decorate", "decorates", "decorated", "Я украшаю торт.", "Я прикрашаю торт.", "Dekoruję tort."],
        ["She is ... her friend.", "calling", "call", "calls", "called", "Она звонит своей подруге.", "Вона телефонує своїй подрузі.", "Dzwoni do swojej przyjaciółki."],
        ["He is ... the new game.", "playing", "play", "plays", "played", "Он играет в новую игру.", "Він грає в нову гру.", "Gra w nową grę."],
        ["They are ... for the bus.", "waiting", "wait", "waits", "waited", "Они ждут автобус.", "Вони чекають на автобус.", "Czekają na autobus."],
        ["We are ... a puzzle.", "solving", "solve", "solves", "solved", "Мы решаем головоломку.", "Ми вирішуємо головоломку.", "Rozwiązujemy zagadkę."],
        ["I am ... for a run.", "going", "go", "goes", "gone", "Я иду на пробежку.", "Я йду на пробіжку.", "Idę pobiegać."],
        ["She is ... her room.", "cleaning", "clean", "cleans", "cleaned", "Она убирает свою комнату.", "Вона прибирає свою кімнату.", "Sprząta swój pokój."],
        ["He is ... the report.", "writing", "write", "writes", "writed", "Он пишет отчёт.", "Він пише звіт.", "Pisze raport."],
        ["They are ... the car.", "cleaning", "clean", "cleans", "cleaned", "Они моют машину.", "Вони миють машину.", "Myją samochód."],
        ["We are ... to the park.", "going", "go", "goes", "gone", "Мы идём в парк.", "Ми йдемо до парку.", "Idziemy do parku."],
        ["I am ... my shoes.", "polishing", "polish", "polishes", "polished", "Я чищу ботинки.", "Я чищу черевики.", "Czyszczę buty."],
        ["She is ... the cake.", "decorating", "decorate", "decorates", "decorated", "Она украшает торт.", "Вона прикрашає торт.", "Dekoruje tort."],
        ["He is ... for the bus.", "waiting", "wait", "waits", "waited", "Он ждёт автобус.", "Він чекає на автобус.", "Czeka na autobus."],
        ["They are ... the movie.", "watching", "watch", "watches", "watched", "Они смотрят фильм.", "Вони дивляться фільм.", "Oglądają film."],
        ["We are ... the room.", "cleaning", "clean", "cleans", "cleaned", "Мы убираем комнату.", "Ми прибираємо кімнату.", "Sprzątamy pokój."],
        ["I am ... for work.", "getting ready", "get ready", "geting ready", "got ready", "Я готовлюсь к работе.", "Я готуюсь до роботи.", "Przygotowuję się do pracy."],
        ["She is ... a new language.", "learning", "learn", "learns", "learned", "Она изучает новый язык.", "Вона вивчає нову мову.", "Uczy się nowego języka."],
        ["He is ... the new project.", "starting", "start", "starts", "started", "Он начинает новый проект.", "Він починає новий проект.", "Zaczyna nowy projekt."],
        ["They are ... a picture.", "drawing", "draw", "draws", "drawed", "Они рисуют картину.", "Вони малюють картину.", "Rysują obrazek."],
        ["We are ... for the party.", "getting ready", "geting ready", "gets ready", "got ready", "Мы готовимся к вечеринке.", "Ми готуємося до вечірки.", "Przygotowujemy się na imprezę."],
        ["I am ... the cake.", "decorating", "decorate", "decorates", "decorated", "Я украшаю торт.", "Я прикрашаю торт.", "Dekoruję tort."],
        ["She is ... her friend.", "calling", "call", "calls", "called", "Она звонит своей подруге.", "Вона телефонує своїй подрузі.", "Dzwoni do swojej przyjaciółki."],
        ["He is ... the new game.", "playing", "play", "plays", "played", "Он играет в новую игру.", "Він грає в нову гру.", "Gra w nową grę."],
        ["They are ... for the bus.", "waiting", "wait", "waits", "waited", "Они ждут автобус.", "Вони чекають на автобус.", "Czekają na autobus."],
        ["We are ... a puzzle.", "solving", "solve", "solves", "solved", "Мы решаем головоломку.", "Ми вирішуємо головоломку.", "Rozwiązujemy zagadkę."],
        ["I am ... for a run.", "going", "go", "goes", "gone", "Я иду на пробежку.", "Я йду на пробіжку.", "Idę pobiegać."],
        ["She is ... her room.", "cleaning", "clean", "cleans", "cleaned", "Она убирает свою комнату.", "Вона прибирає свою кімнату.", "Sprząta swój pokój."],
        ["He is ... the report.", "writing", "write", "writes", "writed", "Он пишет отчёт.", "Він пише звіт.", "Pisze raport."],
        ["They are ... the car.", "cleaning", "clean", "cleans", "cleaned", "Они моют машину.", "Вони миють машину.", "Myją samochód."],
        ["We are ... to the park.", "going", "go", "goes", "gone", "Мы идём в парк.", "Ми йдемо до парку.", "Idziemy do parku."],
        ["I am ... my shoes.", "polishing", "polish", "polishes", "polished", "Я чищу ботинки.", "Я чищу черевики.", "Czyszczę buty."],
        ["She is ... the cake.", "decorating", "decorate", "decorates", "decorated", "Она украшает торт.", "Вона прикрашає торт.", "Dekoruje tort."],
        ["He is ... for the bus.", "waiting", "wait", "waits", "waited", "Он ждёт автобус.", "Він чекає на автобус.", "Czeka na autobus."],
        ["They are ... the movie.", "watching", "watch", "watches", "watched", "Они смотрят фильм.", "Вони дивляться фільм.", "Oglądają film."],
        ["We are ... the room.", "cleaning", "clean", "cleans", "cleaned", "Мы убираем комнату.", "Ми прибираємо кімнату.", "Sprzątamy pokój."],
        ["I am ... for work.", "getting ready", "geting ready", "gets ready", "got ready", "Я готовлюсь к работе.", "Я готуюсь до роботи.", "Przygotowuję się do pracy."],
        ["She is ... a new language.", "learning", "learn", "learns", "learned", "Она изучает новый язык.", "Вона вивчає нову мову.", "Uczy się nowego języka."],
        ["He is ... the new project.", "starting", "start", "starts", "started", "Он начинает новый проект.", "Він починає новий проект.", "Zaczyna nowy projekt."],
        ["They are ... a picture.", "drawing", "draw", "draws", "drawed", "Они рисуют картину.", "Вони малюють картину.", "Rysują obrazek."],
        ["We are ... for the party.", "getting ready", "geting ready", "gets ready", "got ready", "Мы готовимся к вечеринке.", "Ми готуємося до вечірки.", "Przygotowujemy się na imprezę."],
        ["I am ... the cake.", "decorating", "decorate", "decorates", "decorated", "Я украшаю торт.", "Я прикрашаю торт.", "Dekoruję tort."],
        ["She is ... her friend.", "calling", "call", "calls", "called", "Она звонит своей подруге.", "Вона телефонує своїй подрузі.", "Dzwoni do swojej przyjaciółki."],
        ["He is ... the new game.", "playing", "play", "plays", "played", "Он играет в новую игру.", "Він грає в нову гру.", "Gra w nową grę."],
        ["They are ... for the bus.", "waiting", "wait", "waits", "waited", "Они ждут автобус.", "Вони чекають на автобус.", "Czekają na autobus."],
        ["We are ... a puzzle.", "solving", "solve", "solves", "solved", "Мы решаем головоломку.", "Ми вирішуємо головоломку.", "Rozwiązujemy zagadkę."],
        ["I am ... for a run.", "going", "go", "goes", "gone", "Я иду на пробежку.", "Я йду на пробіжку.", "Idę pobiegać."],
        ["She is ... her room.", "cleaning", "clean", "cleans", "cleaned", "Она убирает свою комнату.", "Вона прибирає свою кімнату.", "Sprząta swój pokój."],
        ["He is ... the report.", "writing", "write", "writes", "writed", "Он пишет отчёт.", "Він пише звіт.", "Pisze raport."],
        ["They are ... the car.", "cleaning", "clean", "cleans", "cleaned", "Они моют машину.", "Вони миють машину.", "Myją samochód."],
        ["We are ... to the park.", "going", "go", "goes", "gone", "Мы идём в парк.", "Ми йдемо до парку.", "Idziemy do parku."],
        ["I am ... my shoes.", "polishing", "polish", "polishes", "polished", "Я чищу ботинки.", "Я чищу черевики.", "Czyszczę buty."],
        ["She is ... the cake.", "decorating", "decorate", "decorates", "decorated", "Она украшает торт.", "Вона прикрашає торт.", "Dekoruje tort."],
        ["He is ... for the bus.", "waiting", "wait", "waits", "waited", "Он ждёт автобус.", "Він чекає на автобус.", "Czeka na autobus."],
        ["They are ... the movie.", "watching", "watch", "watches", "watched", "Они смотрят фильм.", "Вони дивляться фільм.", "Oglądają film."],
        ["We are ... the room.", "cleaning", "clean", "cleans", "cleaned", "Мы убираем комнату.", "Ми прибираємо кімнату.", "Sprzątamy pokój."],
        ["I am ... for work.", "getting ready", "get ready", "geting ready", "got ready", "Я готовлюсь к работе.", "Я готуюсь до роботи.", "Przygotowuję się do pracy."],
        ["She is ... a new language.", "learning", "learn", "learns", "learned", "Она изучает новый язык.", "Вона вивчає нову мову.", "Uczy się nowego języka."],
        ["He is ... the new project.", "starting", "start", "starts", "started", "Он начинает новый проект.", "Він починає новий проект.", "Zaczyna nowy projekt."],
        ["They are ... a picture.", "drawing", "draw", "draws", "drawed", "Они рисуют картину.", "Вони малюють картину.", "Rysują obrazek."],
        ["We are ... for the party.", "getting ready", "geting ready", "gets ready", "got ready", "Мы готовимся к вечеринке.", "Ми готуємося до вечірки.", "Przygotowujemy się na imprezę."],
        ["I am ... the cake.", "decorating", "decorate", "decorates", "decorated", "Я украшаю торт.", "Я прикрашаю торт.", "Dekoruję tort."],
        ["She is ... her friend.", "calling", "call", "calls", "called", "Она звонит своей подруге.", "Вона телефонує своїй подрузі.", "Dzwoni do swojej przyjaciółki."],
        ["He is ... the new game.", "playing", "play", "plays", "played", "Он играет в новую игру.", "Він грає в нову гру.", "Gra w nową grę."],
        ["They are ... for the bus.", "waiting", "wait", "waits", "waited", "Они ждут автобус.", "Вони чекають на автобус.", "Czekają na autobus."],
        ["We are ... a puzzle.", "solving", "solve", "solves", "solved", "Мы решаем головоломку.", "Ми вирішуємо головоломку.", "Rozwiązujemy zagadkę."],
        ["I am ... for a run.", "going", "go", "goes", "gone", "Я иду на пробежку.", "Я йду на пробіжку.", "Idę pobiegać."],
        ["She is ... her room.", "cleaning", "clean", "cleans", "cleaned", "Она убирает свою комнату.", "Вона прибирає свою кімнату.", "Sprząta swój pokój."],
        ["He is ... the report.", "writing", "write", "writes", "writed", "Он пишет отчёт.", "Він пише звіт.", "Pisze raport."],
        ["They are ... the car.", "cleaning", "clean", "cleans", "cleaned", "Они моют машину.", "Вони миють машину.", "Myją samochód."],
        ["We are ... to the park.", "going", "go", "goes", "gone", "Мы идём в парк.", "Ми йдемо до парку.", "Idziemy do parku."],
        ["I am ... my shoes.", "polishing", "polish", "polishes", "polished", "Я чищу ботинки.", "Я чищу черевики.", "Czyszczę buty."],
        ["She is ... the cake.", "decorating", "decorate", "decorates", "decorated", "Она украшает торт.","Вона прикрашає торт.","Ona dekoruje tort."],
        function (id) {
        return replaceEllipsisWithWord(id, presentContinuous);
        }
];


