const presentSimpleOrContinius = [
[
    "I ___ books every day.",
    "read",
    "am reading",
    "read",
    "will read",
    "Я читаю книги каждый день.",
    "Я читаю книги кожен день.",
    "Czytam książki codziennie."
],
[
    "She ___ to work every morning.",
    "goes",
    "is going",
    "went",
    "will go",
    "Она ходит на работу каждое утро.",
    "Вона ходить на роботу щоранку.",
    "Ona chodzi do pracy każdego ranka."
],
[
    "They ___ dinner at 7 PM.",
    "eat",
    "are eating",
    "ate",
    "will eat",
    "Они едят ужин в 7 вечера.",
    "Вони їдять вечерю о 7 вечора.",
    "Oni jedzą kolację o 7 wieczorem."
],
[
    "We ___ to the gym twice a week.",
    "go",
    "are going",
    "went",
    "will go",
    "Мы ходим в спортзал дважды в неделю.",
    "Ми ходимо до спортзалу двічі на тиждень.",
    "Chodzimy na siłownię dwa razy w tygodniu."
],
[
    "John ___ his car every weekend.",
    "washes",
    "is washing",
    "washed",
    "will wash",
    "Джон моет свою машину каждые выходные.",
    "Джон миє свою машину щовихідні.",
    "John myje swój samochód co weekend."
],
[
    "They ___ a new movie next month.",
    "release",
    "are releasing",
    "released",
    "will release",
    "Они выпускают новый фильм в следующем месяце.",
    "Вони випускають новий фільм наступного місяця.",
    "Oni wydają nowy film w przyszłym miesiącu."
],
[
    "She ___ her mother every Sunday.",
    "visits",
    "is visiting",
    "visited",
    "will visit",
    "Она навещает свою мать каждое воскресенье.",
    "Вона відвідує свою матір щонеділі.",
    "Ona odwiedza swoją matkę w każdą niedzielę."
],
[
    "He ___ coffee every morning.",
    "drinks",
    "is drinking",
    "drank",
    "will drink",
    "Он пьет кофе каждое утро.",
    "Він п'є каву щоранку.",
    "On pije kawę każdego ranka."
],
[
    "We ___ soccer every Saturday.",
    "play",
    "are playing",
    "played",
    "will play",
    "Мы играем в футбол каждую субботу.",
    "Ми граємо у футбол щосуботи.",
    "Gramy w piłkę nożną w każdą sobotę."
],
[
    "They ___ to music in the evening.",
    "listen",
    "are listening",
    "listened",
    "will listen",
    "Они слушают музыку вечером.",
    "Вони слухають музику ввечері.",
    "Słuchają muzyki wieczorem."
],
[
    "He ___ his homework after school.",
    "does",
    "is doing",
    "did",
    "will do",
    "Он делает домашнее задание после школы.",
    "Він робить домашнє завдання після школи.",
    "On odrabia pracę domową po szkole."
],
[
    "She ___ lunch at 1 PM.",
    "has",
    "is having",
    "had",
    "will have",
    "Она обедает в 1 час дня.",
    "Вона обідає о першій годині дня.",
    "Ona ma obiad o 13:00."
],
[
    "They ___ on vacation every summer.",
    "go",
    "are going",
    "went",
    "will go",
    "Они ездят в отпуск каждое лето.",
    "Вони їздять у відпустку кожного літа.",
    "Jadą na wakacje każdego lata."
],
[
    "We ___ TV in the evening.",
    "watch",
    "are watching",
    "watched",
    "will watch",
    "Мы смотрим телевизор вечером.",
    "Ми дивимося телевізор ввечері.",
    "Oglądamy telewizję wieczorem."
],
[
    "I ___ my homework every day.",
    "do",
    "am doing",
    "did",
    "will do",
    "Я делаю домашнее задание каждый день.",
    "Я роблю домашнє завдання кожен день.",
    "Odrabiam pracę domową codziennie."
],
[
    "She ___ breakfast at 8 AM.",
    "has",
    "is having",
    "had",
    "will have",
    "Она завтракает в 8 утра.",
    "Вона снідає о 8 ранку.",
    "Ona je śniadanie o 8 rano."
],
[
    "They ___ football every weekend.",
    "play",
    "are playing",
    "played",
    "will play",
    "Они играют в футбол каждые выходные.",
    "Вони грають у футбол щовихідні.",
    "Grają w piłkę nożną co weekend."
],
[
    "He ___ a book before bed.",
    "reads",
    "is reading",
    "read",
    "will read",
    "Он читает книгу перед сном.",
    "Він читає книгу перед сном.",
    "Czyta książkę przed snem."
],
[
    "We ___ to the store on Saturdays.",
    "go",
    "are going",
    "went",
    "will go",
    "Мы ходим в магазин по субботам.",
    "Ми ходимо до магазину щосуботи.",
    "Idziemy do sklepu w soboty."
],
[
    "She ___ a letter to her friend.",
    "writes",
    "is writing",
    "wrote",
    "will write",
    "Она пишет письмо своему другу.",
    "Вона пише листа своєму другові.",
    "Ona pisze list do przyjaciela."
],
[
    "I ___ to the park every weekend.",
    "go",
    "am going",
    "went",
    "will go",
    "Я хожу в парк каждые выходные.",
    "Я ходжу до парку кожні вихідні.",
    "Chodzę do parku co weekend."
],
[
    "She ___ for her exams every evening.",
    "studies",
    "is studying",
    "studied",
    "will study",
    "Она готовится к экзаменам каждый вечер.",
    "Вона готується до іспитів щовечора.",
    "Ona uczy się do egzaminów każdego wieczoru."
],
[
    "They ___ basketball every Sunday.",
    "play",
    "are playing",
    "played",
    "will play",
    "Они играют в баскетбол каждое воскресенье.",
    "Вони грають у баскетбол щонеділі.",
    "Oni grają w koszykówkę w każdą niedzielę."
],
[
    "He ___ his dog every morning.",
    "walks",
    "is walking",
    "walked",
    "will walk",
    "Он выгуливает свою собаку каждое утро.",
    "Він вигулює свою собаку щоранку.",
    "On wyprowadza psa każdego ranka."
],
[
    "We ___ pizza on Fridays.",
    "eat",
    "are eating",
    "ate",
    "will eat",
    "Мы едим пиццу по пятницам.",
    "Ми їмо піцу по п’ятницях.",
    "Jemy pizzę w piątki."
],
[
    "I ___ a movie every night.",
    "watch",
    "am watching",
    "watched",
    "will watch",
    "Я смотрю фильм каждый вечер.",
    "Я дивлюсь фільм кожного вечора.",
    "Oglądam film każdego wieczoru."
],
[
    "She ___ to the gym every Monday.",
    "goes",
    "is going",
    "went",
    "will go",
    "Она ходит в спортзал каждый понедельник.",
    "Вона ходить до спортзалу щопонеділка.",
    "Ona chodzi na siłownię w każdy poniedziałek."
],
[
    "They ___ to the beach in summer.",
    "go",
    "are going",
    "went",
    "will go",
    "Они ездят на пляж летом.",
    "Вони їздять на пляж влітку.",
    "Jadą na plażę latem."
],
[
    "He ___ a new book every month.",
    "reads",
    "is reading",
    "read",
    "will read",
    "Он читает новую книгу каждый месяц.",
    "Він читає нову книгу щомісяця.",
    "Czyta nową książkę co miesiąc."
],
[
    "We ___ dinner together every day.",
    "have",
    "are having",
    "had",
    "will have",
    "Мы ужинаем вместе каждый день.",
    "Ми вечеряємо разом щодня.",
    "Jemy obiad razem codziennie."
],
[
    "They ___ the bus every morning.",
    "take",
    "are taking",
    "took",
    "will take",
    "Они садятся на автобус каждое утро.",
    "Вони сідають на автобус щоранку.",
    "Biorą autobus każdego ranka."
],
[
    "He ___ music on his phone.",
    "listens",
    "is listening",
    "listened",
    "will listen",
    "Он слушает музыку на своем телефоне.",
    "Він слухає музику на своєму телефоні.",
    "Słucha muzyki na swoim telefonie."
],
[
    "We ___ in the park every Sunday.",
    "run",
    "are running",
    "ran",
    "will run",
    "Мы бегаем в парке каждое воскресенье.",
    "Ми бігаємо в парку щонеділі.",
    "Biegamy w parku w każdą niedzielę."
],
[
    "I ___ emails every morning.",
    "write",
    "am writing",
    "wrote",
    "will write",
    "Я пишу электронные письма каждое утро.",
    "Я пишу електронні листи щоранку.",
    "Piszę maile każdego ranka."
],
[
    "She ___ a book every week.",
    "reads",
    "is reading",
    "read",
    "will read",
    "Она читает книгу каждую неделю.",
    "Вона читає книгу щотижня.",
    "Czyta książkę co tydzień."
],
[
    "They ___ the car every month.",
    "wash",
    "are washing",
    "washed",
    "will wash",
    "Они моют машину каждый месяц.",
    "Вони миють машину щомісяця.",
    "Myją samochód co miesiąc."
],
[
    "He ___ football on weekends.",
    "plays",
    "is playing",
    "played",
    "will play",
    "Он играет в футбол по выходным.",
    "Він грає у футбол на вихідних.",
    "Gra w piłkę nożną w weekendy."
],
[
    "We ___ shopping every Saturday.",
    "go",
    "are going",
    "went",
    "will go",
    "Мы ходим за покупками каждую субботу.",
    "Ми ходимо за покупками щосуботи.",
    "Idziemy na zakupy w każdą sobotę."
],
[
    "She ___ the piano in the evening.",
    "plays",
    "is playing",
    "played",
    "will play",
    "Она играет на пианино вечером.",
    "Вона грає на піаніно ввечері.",
    "Gra na pianinie wieczorem."
],
[
    "They ___ breakfast at 8 AM.",
    "have",
    "are having",
    "had",
    "will have",
    "Они завтракают в 8 утра.",
    "Вони снідають о 8 ранку.",
    "Jedzą śniadanie o 8 rano."
],
[
"I ___ my room every weekend.",
"clean",
"am cleaning",
"cleaned",
"will clean",
"Я убираю свою комнату каждые выходные.",
"Я прибираю свою кімнату кожні вихідні.",
"Sprzątam mój pokój co weekend."
],
[
"She ___ her mother every evening.",
"calls",
"is calling",
"called",
"will call",
"Она звонит своей маме каждый вечер.",
"Вона дзвонить своїй мамі кожного вечора.",
"Dzwoni do swojej mamy każdego wieczoru."
],
[
"They ___ together on Sundays.",
"sing",
"are singing",
"sang",
"will sing",
"Они поют вместе по воскресеньям.",
"Вони співають разом щонеділі.",
"Śpiewają razem w niedziele."
],
[
"He ___ his friends every Friday.",
"meets",
"is meeting",
"met",
"will meet",
"Он встречается с друзьями каждую пятницу.",
"Він зустрічається з друзями щоп'ятниці.",
"Spotyka się z przyjaciółmi w każdy piątek."
],
[
"We ___ our homework after school.",
"do",
"are doing",
"did",
"will do",
"Мы делаем домашнюю работу после школы.",
"Ми робимо домашнє завдання після школи.",
"Robimy pracę domową po szkole."
],
[
"I ___ dinner for my family every day.",
"cook",
"am cooking",
"cooked",
"will cook",
"Я готовлю ужин для своей семьи каждый день.",
"Я готую вечерю для своєї сім'ї щодня.",
"Gotuję obiad dla mojej rodziny każdego dnia."
],
[
"She ___ her bike to school.",
"rides",
"is riding",
"rode",
"will ride",
"Она ездит в школу на велосипеде.",
"Вона їздить до школи на велосипеді.",
"Jeździ rowerem do szkoły."
],
[
"They ___ for work early every day.",
"leave",
"are leaving",
"left",
"will leave",
"Они уходят на работу рано каждый день.",
"Вони йдуть на роботу рано щодня.",
"Wychodzą do pracy wcześnie każdego dnia."
],
[
"He ___ to the news every morning.",
"listens",
"is listening",
"listened",
"will listen",
"Он слушает новости каждое утро.",
"Він слухає новини щоранку.",
"Słucha wiadomości każdego ranka."
],
[
"We ___ the garden in summer.",
"water",
"are watering",
"watered",
"will water",
"Мы поливаем сад летом.",
"Ми поливаємо сад влітку.",
"Podlewamy ogród latem."
],
[
"I ___ my teeth twice a day.",
"brush",
"am brushing",
"brushed",
"will brush",
"Я чищу зубы дважды в день.",
"Я чищу зуби двічі на день.",
"Myję zęby dwa razy dziennie."
],
[
"She ___ new songs on the piano.",
"plays",
"is playing",
"played",
"will play",
"Она играет новые песни на пианино.",
"Вона грає нові пісні на піаніно.",
"Gra nowe piosenki na pianinie."
],
[
"They ___ for the marathon every day.",
"train",
"are training",
"trained",
"will train",
"Они тренируются для марафона каждый день.",
"Вони тренуються для марафону щодня.",
"Trenują na maraton każdego dnia."
],
[
"He ___ English lessons twice a week.",
"takes",
"is taking",
"took",
"will take",
"Он берёт уроки английского дважды в неделю.",
"Він бере уроки англійської двічі на тиждень.",
"Bierze lekcje angielskiego dwa razy w tygodniu."
],
[
"We ___ football after school.",
"play",
"are playing",
"played",
"will play",
"Мы играем в футбол после школы.",
"Ми граємо у футбол після школи.",
"Gramy w piłkę nożną po szkole."
],
[
"I ___ my car every Sunday.",
"wash",
"am washing",
"washed",
"will wash",
"Я мою свою машину каждое воскресенье.",
"Я мию свою машину кожної неділі.",
"Myję mój samochód w każdą niedzielę."
],
[
"She ___ yoga in the morning.",
"does",
"is doing",
"did",
"will do",
"Она занимается йогой по утрам.",
"Вона займається йогою щоранку.",
"Robi jogę rano."
],
[
"They ___ movies on weekends.",
"watch",
"are watching",
"watched",
"will watch",
"Они смотрят фильмы по выходным.",
"Вони дивляться фільми на вихідних.",
"Oglądają filmy w weekendy."
],
[
"He ___ to the gym twice a week.",
"goes",
"is going",
"went",
"will go",
"Он ходит в спортзал дважды в неделю.",
"Він ходить до спортзалу двічі на тиждень.",
"Chodzi na siłownię dwa razy w tygodniu."
],
[
"We ___ together every weekend.",
"work",
"are working",
"worked",
"will work",
"Мы работаем вместе каждые выходные.",
"Ми працюємо разом кожні вихідні.",
"Pracujemy razem co weekend."
], // дальше индекс 60
["I ___ (work) at the moment.", "am working", "work", "worked", "will work", "Я работаю в данный момент.", "Я працюю зараз.", "Pracuję w tej chwili."],
["They ___ (play) football now.", "are playing", "play", "played", "will play", "Они играют в футбол сейчас.", "Вони грають у футбол зараз.", "Oni grają w piłkę nożną teraz."],
["She ___ (cook) dinner.", "is cooking", "cooks", "cooked", "will cook", "Она готовит ужин.", "Вона готує вечерю.", "Ona gotuje obiad."],
["We ___ (read) a book.", "are reading", "read", "read", "will read", "Мы читаем книгу.", "Ми читаємо книгу.", "Czytamy książkę."],
["He ___ (clean) the house.", "is cleaning", "cleans", "cleaned", "will clean", "Он убирает дом.", "Він прибирає будинок.", "On sprząta dom."],
["You ___ (study) for the exam.", "are studying", "study", "studied", "will study", "Ты готовишься к экзамену.", "Ти готуєшся до іспиту.", "Przygotowujesz się do egzaminu."],
["They ___ (swim) in the pool.", "are swimming", "swim", "swam", "will swim", "Они плавают в бассейне.", "Вони плавають в басейні.", "Oni pływają w basenie."],
["I ___ (drive) my car.", "am driving", "drive", "drove", "will drive", "Я вожу машину.", "Я воджу машину.", "Prowadzę samochód."],
["He ___ (watch) TV.", "is watching", "watches", "watched", "will watch", "Он смотрит телевизор.", "Він дивиться телевізор.", "On ogląda telewizję."],
["We ___ (travel) around the city.", "are traveling", "travel", "traveled", "will travel", "Мы путешествуем по городу.", "Ми подорожуємо містом.", "Podróżujemy po mieście."],
["She ___ (sleep) right now.", "is sleeping", "sleeps", "slept", "will sleep", "Она сейчас спит.", "Вона зараз спить.", "Ona teraz śpi."],
["You ___ (run) fast.", "are running", "run", "ran", "will run", "Ты быстро бегаешь.", "Ти швидко біжиш.", "Biegniesz szybko."],
["They ___ (build) a new house.", "are building", "build", "built", "will build", "Они строят новый дом.", "Вони будують новий будинок.", "Oni budują nowy dom."],
["I ___ (write) an essay.", "am writing", "write", "wrote", "will write", "Я пишу эссе.", "Я пишу есе.", "Piszę esej."],
["He ___ (paint) the wall.", "is painting", "paints", "painted", "will paint", "Он красит стену.", "Він фарбує стіну.", "On maluje ścianę."],
["We ___ (fix) the computer.", "are fixing", "fix", "fixed", "will fix", "Мы чинем компьютер.", "Ми лагодимо комп’ютер.", "Naprawiamy komputer."],
["She ___ (dance) at the party.", "is dancing", "dances", "danced", "will dance", "Она танцует на вечеринке.", "Вона танцює на вечірці.", "Ona tańczy na imprezie."],
["You ___ (sing) very well.", "are singing", "sing", "sang", "will sing", "Ты поёшь очень хорошо.", "Ти співаєш дуже добре.", "Śpiewasz bardzo dobrze."],
["They ___ (talk) on the phone.", "are talking", "talk", "talked", "will talk", "Они разговаривают по телефону.", "Вони розмовляють по телефону.", "Oni rozmawiają przez telefon."],
["I ___ (make) a cake.", "am making", "make", "made", "will make", "Я делаю торт.", "Я роблю торт.", "Robię ciasto."],
["He ___ (drive) to work.", "is driving", "drives", "drove", "will drive", "Он едет на работу.", "Він їде на роботу.", "On jedzie do pracy."],
["We ___ (plan) a trip.", "are planning", "plan", "planned", "will plan", "Мы планируем поездку.", "Ми плануємо подорож.", "Planujemy wycieczkę."],
["She ___ (eat) an apple.", "is eating", "eats", "ate", "will eat", "Она ест яблоко.", "Вона їсть яблуко.", "Ona je jabłko."],
["You ___ (buy) a new phone.", "are buying", "buy", "bought", "will buy", "Ты покупаешь новый телефон.", "Ти купуєш новий телефон.", "Kupujesz nowy telefon."],
["They ___ (clean) the room.", "are cleaning", "clean", "cleaned", "will clean", "Они убирают комнату.", "Вони прибирають кімнату.", "Oni sprzątają pokój."],
["I ___ (study) for my test.", "am studying", "study", "studied", "will study", "Я готовлюсь к тесту.", "Я готуюсь до тесту.", "Przygotowuję się do testu."],
["He ___ (fix) the car.", "is fixing", "fixes", "fixed", "will fix", "Он чинит машину.", "Він лагодить машину.", "On naprawia samochód."],
["We ___ (celebrate) her birthday.", "are celebrating", "celebrate", "celebrated", "will celebrate", "Мы празднуем её день рождения.", "Ми святкуємо її день народження.", "Świętujemy jej urodziny."],
["She ___ (prepare) dinner.", "is preparing", "prepares", "prepared", "will prepare", "Она готовит ужин.", "Вона готує вечерю.", "Ona przygotowuje obiad."],
["You ___ (wash) your hands.", "are washing", "wash", "washed", "will wash", "Ты моешь руки.", "Ти миєш руки.", "Myjesz ręce."],
["They ___ (arrive) soon.", "are arriving", "arrive", "arrived", "will arrive", "Они скоро прибудут.", "Вони скоро приїдуть.", "Oni wkrótce przyjadą."],
["They ___ (wait) for the bus.", "are waiting", "wait", "waited", "will wait", "Они ждут автобус.", "Вони чекають автобус.", "Oni czekają na autobus."],
["I ___ (exercise) in the gym.", "am exercising", "exercise", "exercised", "will exercise", "Я тренируюсь в спортзале.", "Я тренуюсь у спортзалі.", "Ćwiczę na siłowni."],
["He ___ (watch) the news.", "is watching", "watches", "watched", "will watch", "Он смотрит новости.", "Він дивиться новини.", "On ogląda wiadomości."],
["We ___ (discuss) the project.", "are discussing", "discuss", "discussed", "will discuss", "Мы обсуждаем проект.", "Ми обговорюємо проєкт.", "Dyskutujemy o projekcie."],
["She ___ (write) a letter.", "is writing", "writes", "wrote", "will write", "Она пишет письмо.", "Вона пише лист.", "Ona pisze list."],
["You ___ (learn) Spanish.", "are learning", "learn", "learned", "will learn", "Ты учишь испанский.", "Ти вчиш іспанську.", "Uczysz się hiszpańskiego."],
["They ___ (fix) the bike.", "are fixing", "fix", "fixed", "will fix", "Они чинят велосипед.", "Вони лагодять велосипед.", "Oni naprawiają rower."],
["I ___ (open) the window.", "am opening", "open", "opened", "will open", "Я открываю окно.", "Я відчиняю вікно.", "Otwieram okno."],
["He ___ (carry) the bags.", "is carrying", "carries", "carried", "will carry", "Он несет сумки.", "Він несе сумки.", "On niesie torby."],
["We ___ (meet) with friends.", "are meeting", "meet", "met", "will meet", "Мы встречаемся с друзьями.", "Ми зустрічаємося з друзями.", "Spotykamy się z przyjaciółmi."],
["She ___ (call) her mother.", "is calling", "calls", "called", "will call", "Она звонит своей маме.", "Вона дзвонить своїй мамі.", "Ona dzwoni do swojej matki."],
["You ___ (play) video games.", "are playing", "play", "played", "will play", "Ты играешь в видеоигры.", "Ти граєш у відеоігри.", "Grasz w gry wideo."],
["They ___ (paint) the house.", "are painting", "paint", "painted", "will paint", "Они красят дом.", "Вони фарбують будинок.", "Oni malują dom."],
["I ___ (cut) the vegetables.", "am cutting", "cut", "cut", "will cut", "Я нарезаю овощи.", "Я ріжу овочі.", "Kroję warzywa."],
["He ___ (run) to catch the bus.", "is running", "runs", "ran", "will run", "Он бежит, чтобы успеть на автобус.", "Він біжить, щоб встигнути на автобус.", "On biegnie, aby złapać autobus."],
["We ___ (drive) to the airport.", "are driving", "drive", "drove", "will drive", "Мы едем в аэропорт.", "Ми їдемо до аеропорту.", "Jedziemy na lotnisko."],
["She ___ (dance) in the rain.", "is dancing", "dances", "danced", "will dance", "Она танцует под дождем.", "Вона танцює під дощем.", "Ona tańczy w deszczu."],
["You ___ (listen) to music.", "are listening", "listen", "listened", "will listen", "Ты слушаешь музыку.", "Ти слухаєш музику.", "Słuchasz muzyki."],
["They ___ (enjoy) the weather.", "are enjoying", "enjoy", "enjoyed", "will enjoy", "Они наслаждаются погодой.", "Вони насолоджуються погодою.", "Oni cieszą się pogodą."],
["I ___ (talk) to my friend.", "am talking", "talk", "talked", "will talk", "Я разговариваю с другом.", "Я розмовляю з другом.", "Rozmawiam z przyjacielem."],
["He ___ (shop) for groceries.", "is shopping", "shops", "shopped", "will shop", "Он покупает продукты.", "Він купує продукти.", "On robi zakupy spożywcze."],
["We ___ (plan) a surprise party.", "are planning", "plan", "planned", "will plan", "Мы планируем вечеринку-сюрприз.", "Ми плануємо вечірку-сюрприз.", "Planujemy przyjęcie niespodziankę."],
["She ___ (organize) her desk.", "is organizing", "organizes", "organized", "will organize", "Она организует своё рабочее место.", "Вона організовує своє робоче місце.", "Ona organizuje swoje biurko."],
["You ___ (pack) for the trip.", "are packing", "pack", "packed", "will pack", "Ты собираешь вещи для поездки.", "Ти збираєш речі для подорожі.", "Pakujesz się na wycieczkę."],
["They ___ (train) for the marathon.", "are training", "train", "trained", "will train", "Они тренируются для марафона.", "Вони тренуються для марафону.", "Oni trenują do maratonu."],
["I ___ (jog) in the park.", "am jogging", "jog", "jogged", "will jog", "Я бегаю в парке.", "Я бігаю у парку.", "Biegam po parku."],
["He ___ (visit) his grandmother.", "is visiting", "visits", "visited", "will visit", "Он навещает свою бабушку.", "Він навідує свою бабусю.", "On odwiedza swoją babcię."],
["We ___ (travel) to another city.", "are traveling", "travel", "traveled", "will travel", "Мы едем в другой город.", "Ми їдемо в інше місто.", "Podróżujemy do innego miasta."],
["She ___ (knit) a sweater.", "is knitting", "knits", "knitted", "will knit", "Она вяжет свитер.", "Вона в’яже светр.", "Ona robi na drutach sweter."],
["You ___ (draw) a picture.", "are drawing", "draw", "drew", "will draw", "Ты рисуешь картину.", "Ти малюєш картину.", "Rysujesz obrazek."],
["He ___ (build) a treehouse.", "is building", "builds", "built", "will build", "Он строит домик на дереве.", "Він будує будиночок на дереві.", "On buduje domek na drzewie."],
["We ___ (explore) the forest.", "are exploring", "explore", "explored", "will explore", "Мы исследуем лес.", "Ми досліджуємо ліс.", "Eksplorujemy las."],
["She ___ (feed) the baby.", "is feeding", "feeds", "fed", "will feed", "Она кормит ребенка.", "Вона годує дитину.", "Ona karmi dziecko."],
["You ___ (cook) dinner.", "are cooking", "cook", "cooked", "will cook", "Ты готовишь ужин.", "Ти готуєш вечерю.", "Gotujesz kolację."],
["They ___ (sing) a song.", "are singing", "sing", "sang", "will sing", "Они поют песню.", "Вони співають пісню.", "Śpiewają piosenkę."],
["I ___ (clean) the room.", "am cleaning", "clean", "cleaned", "will clean", "Я убираю комнату.", "Я прибираю кімнату.", "Sprzątam pokój."],
["He ___ (water) the plants.", "is watering", "waters", "watered", "will water", "Он поливает растения.", "Він поливає рослини.", "On podlewa rośliny."],
["We ___ (dance) at the party.", "are dancing", "dance", "danced", "will dance", "Мы танцуем на вечеринке.", "Ми танцюємо на вечірці.", "Tańczymy na imprezie."],
["She ___ (paint) a portrait.", "is painting", "paints", "painted", "will paint", "Она рисует портрет.", "Вона малює портрет.", "Ona maluje portret."],
["You ___ (study) for the exam.", "are studying", "study", "studied", "will study", "Ты готовишься к экзамену.", "Ти готуєшся до іспиту.", "Uczysz się do egzaminu."],
["They ___ (shop) for clothes.", "are shopping", "shop", "shopped", "will shop", "Они покупают одежду.", "Вони купують одяг.", "Oni robią zakupy na ubrania."],
["I ___ (draw) a sketch.", "am drawing", "draw", "drew", "will draw", "Я рисую эскиз.", "Я малюю ескіз.", "Rysuję szkic."],
["He ___ (repair) the car.", "is repairing", "repairs", "repaired", "will repair", "Он чинит машину.", "Він ремонтує машину.", "On naprawia samochód."],
["We ___ (decorate) the room.", "are decorating", "decorate", "decorated", "will decorate", "Мы украшаем комнату.", "Ми прикрашаємо кімнату.", "Dekorujemy pokój."],
["She ___ (teach) the class.", "is teaching", "teaches", "taught", "will teach", "Она преподает в классе.", "Вона викладає в класі.", "Ona uczy w klasie."],
["You ___ (read) a book.", "are reading", "read", "read", "will read", "Ты читаешь книгу.", "Ти читаєш книгу.", "Czytasz książkę."],
["They ___ (move) to a new house.", "are moving", "move", "moved", "will move", "Они переезжают в новый дом.", "Вони переїжджають до нового будинку.", "Przeprowadzają się do nowego domu."],
["I ___ (watch) a movie.", "am watching", "watch", "watched", "will watch", "Я смотрю фильм.", "Я дивлюся фільм.", "Oglądam film."],
["He ___ (write) a report.", "is writing", "writes", "wrote", "will write", "Он пишет отчет.", "Він пише звіт.", "On pisze raport."],
["We ___ (practice) the guitar.", "are practicing", "practice", "practiced", "will practice", "Мы практикуем игру на гитаре.", "Ми практикуємо гру на гітарі.", "Ćwiczymy na gitarze."],
["She ___ (shop) online.", "is shopping", "shops", "shopped", "will shop", "Она покупает онлайн.", "Вона купує онлайн.", "Ona robi zakupy online."],
["You ___ (design) a website.", "are designing", "design", "designed", "will design", "Ты разрабатываешь вебсайт.", "Ти розробляєш вебсайт.", "Projektujesz stronę internetową."],
["They ___ (play) basketball.", "are playing", "play", "played", "will play", "Они играют в баскетбол.", "Вони грають у баскетбол.", "Grają w koszykówkę."],
["I ___ (send) an email.", "am sending", "send", "sent", "will send", "Я отправляю электронное письмо.", "Я відправляю електронний лист.", "Wysyłam email."],
["He ___ (discover) a new talent.", "is discovering", "discovers", "discovered", "will discover", "Он открывает новый талант.", "Він відкриває новий талант.", "On odkrywa nowy talent."],
["We ___ (celebrate) our anniversary.", "are celebrating", "celebrate", "celebrated", "will celebrate", "Мы отмечаем нашу годовщину.", "Ми святкуємо нашу річницю.", "Świętujemy naszą rocznicę."],
["She ___ (organize) a charity event.", "is organizing", "organizes", "organized", "will organize", "Она организует благотворительное мероприятие.", "Вона організує благодійний захід.", "Ona organizuje wydarzenie charytatywne."],
["You ___ (exercise) at the gym.", "are exercising", "exercise", "exercised", "will exercise", "Ты тренируешься в спортзале.", "Ти тренуєшся в спортзалі.", "Ćwiczysz na siłowni."],
["They ___ (travel) to Europe.", "are traveling", "travel", "traveled", "will travel", "Они путешествуют по Европе.", "Вони подорожують по Європі.", "Podróżują po Europie."],
["I ___ (prepare) for the meeting.", "am preparing", "prepare", "prepared", "will prepare", "Я готовлюсь к встрече.", "Я готуюсь до зустрічі.", "Przygotowuję się do spotkania."],
["He ___ (train) for the marathon.", "is training", "trains", "trained", "will train", "Он тренируется для марафона.", "Він тренується до марафону.", "On trenuje do maratonu."],
["We ___ (build) a new website.", "are building", "build", "built", "will build", "Мы создаем новый вебсайт.", "Ми створюємо новий вебсайт.", "Budujemy nową stronę internetową."],
["She ___ (research) for her thesis.", "is researching", "researches", "researched", "will research", "Она исследует для своей диссертации.", "Вона досліджує для своєї дисертації.", "Ona prowadzi badania do swojej pracy dyplomowej."],
["You ___ (fix) the computer.", "are fixing", "fix", "fixed", "will fix", "Ты чинешь компьютер.", "Ти ремонтуєш комп'ютер.", "Naprawiasz komputer."],
["They ___ (join) a club.", "are joining", "join", "joined", "will join", "Они присоединяются к клубу.", "Вони приєднуються до клубу.", "Oni dołączają do klubu."],
["I ___ (visit) my grandmother.", "am visiting", "visit", "visited", "will visit", "Я навещаю бабушку.", "Я відвідую бабусю.", "Odwiedzam babcię."],
["He ___ (look) for a job.", "is looking", "looks", "looked", "will look", "Он ищет работу.", "Він шукає роботу.", "On szuka pracy."],
["We ___ (test) the new software.", "are testing", "test", "tested", "will test", "Мы тестируем новое программное обеспечение.", "Ми тестуємо нове програмне забезпечення.", "Testujemy nowe oprogramowanie."],
["She ___ (perform) in the theater.", "is performing", "performs", "performed", "will perform", "Она выступает в театре.", "Вона виступає в театрі.", "Ona występuje w teatrze."],
["You ___ (discuss) the project.", "are discussing", "discuss", "discussed", "will discuss", "Ты обсуждаешь проект.", "Ти обговорюєш проект.", "Dyskusja o projekcie."],
["They ___ (learn) a new language.", "are learning", "learn", "learned", "will learn", "Они учат новый язык.", "Вони вивчають нову мову.", "Uczą się nowego języka."],
["I ___ (check) my email.", "am checking", "check", "checked", "will check", "Я проверяю свою почту.", "Я перевіряю свою електронну пошту.", "Sprawdzam swoją pocztę."],
["He ___ (play) the piano.", "is playing", "plays", "played", "will play", "Он играет на пианино.", "Він грає на піаніно.", "On gra na pianinie."],
["We ___ (eat) dinner together.", "are eating", "eat", "ate", "will eat", "Мы ужинаем вместе.", "Ми вечеряємо разом.", "Jemy kolację razem."],
["She ___ (exercise) every morning.", "is exercising", "exercises", "exercised", "will exercise", "Она занимается каждый утро.", "Вона займається щоранку.", "Ona ćwiczy każdego ranka."],
["You ___ (play) video games.", "are playing", "play", "played", "will play", "Ты играешь в видеоигры.", "Ти граєш у відеоігри.", "Grasz w gry wideo."],
["They ___ (visit) the museum.", "are visiting", "visit", "visited", "will visit", "Они посещают музей.", "Вони відвідують музей.", "Oni odwiedzają muzeum."],
["I ___ (talk) on the phone.", "am talking", "talk", "talked", "will talk", "Я говорю по телефону.", "Я розмовляю по телефону.", "Mówię przez telefon."],
["He ___ (gather) information.", "is gathering", "gathers", "gathered", "will gather", "Он собирает информацию.", "Він збирає інформацію.", "On zbiera informacje."],
["We ___ (follow) the news.", "are following", "follow", "followed", "will follow", "Мы следим за новостями.", "Ми стежимо за новинами.", "Śledzimy wiadomości."],
["She ___ (explore) new places.", "is exploring", "explores", "explored", "will explore", "Она исследует новые места.", "Вона досліджує нові місця.", "Ona odkrywa nowe miejsca."],
["You ___ (report) the incident.", "are reporting", "report", "reported", "will report", "Ты сообщаешь об инциденте.", "Ти повідомляєш про інцидент.", "Informujesz o incydencie."],
["They ___ (share) their ideas.", "are sharing", "share", "shared", "will share", "Они делятся своими идеями.", "Вони діляться своїми ідеями.", "Dzielą się swoimi pomysłami."],
["I ___ (study) for my exams.", "am studying", "study", "studied", "will study", "Я готовлюсь к экзаменам.", "Я готуюсь до екзаменів.", "Uczę się do egzaminów."],
["He ___ (talk) about his plans.", "is talking", "talks", "talked", "will talk", "Он говорит о своих планах.", "Він говорить про свої плани.", "On mówi o swoich planach."],
/*индекс 177*/["We ___ (have) a great time.", "are having", "have", "had", "will have", "Мы отлично проводим время.", "Ми чудово проводимо час.", "Mamy świetny czas."],
["I am eating lunch.", "Are you eating lunch?", "Do you eat lunch?", "What are you eating?", "Is he eating lunch?", "Я обедаю.", "Я обідаю.", "Ja jem lunch."],
["She is reading a book.", "Is she reading a book?", "Does she read a book?", "What is she reading?", "Is he reading a book?", "Она читает книгу.", "Вона читає книгу.", "Ona czyta książkę."],
["They are playing soccer.", "Are they playing soccer?", "Do they play soccer?", "What are they playing?", "Is he playing soccer?", "Они играют в футбол.", "Вони грають у футбол.", "Oni grają w piłkę nożną."],
["We are watching a movie.", "Are we watching a movie?", "Do we watch movies?", "What are we watching?", "Is she watching a movie?", "Мы смотрим фильм.", "Ми дивимося фільм.", "Oglądamy film."],
["He is cooking dinner.", "Is he cooking dinner?", "Does he cook dinner?", "What is he cooking?", "Is she cooking dinner?", "Он готовит ужин.", "Він готує вечерю.", "On gotuje kolację."],
["You are studying for the exam.", "Are you studying for the exam?", "Do you study for exams?", "What are you studying?", "Is she studying for the exam?", "Ты готовишься к экзамену.", "Ти готуєшся до екзамену.", "Uczysz się do egzaminu."],
["I am learning English.", "Are you learning English?", "Do you learn English?", "What are you learning?", "Is he learning English?", "Я учу английский.", "Я вивчаю англійську.", "Uczę się angielskiego."],
["She is working on a project.", "Is she working on a project?", "Does she work on projects?", "What is she working on?", "Is he working on the project?", "Она работает над проектом.", "Вона працює над проектом.", "Ona pracuje nad projektem."],
["They are traveling to Paris.", "Are they traveling to Paris?", "Do they travel to Paris?", "Where are they traveling?", "Is he traveling to Paris?", "Они путешествуют в Париж.", "Вони подорожують до Парижа.", "Oni podróżują do Paryża."],
["We are playing video games.", "Are we playing video games?", "Do we play video games?", "What are we playing?", "Is she playing video games?", "Мы играем в видеоигры.", "Ми граємо у відеоігри.", "Gramy w gry wideo."],
["I am writing a letter.", "Are you writing a letter?", "Do you write letters?", "What are you writing?", "Is she writing a letter?", "Я пишу письмо.", "Я пишу листа.", "Piszę list."],
["He is painting a picture.", "Is he painting a picture?", "Does he paint pictures?", "What is he painting?", "Is she painting a picture?", "Он рисует картину.", "Він малює картину.", "On maluje obraz."],
["You are cleaning your room.", "Are you cleaning your room?", "Do you clean your room?", "What are you cleaning?", "Is she cleaning her room?", "Ты убираешь свою комнату.", "Ти прибираєш свою кімнату.", "Sprzątasz swój pokój."],
["They are preparing for the test.", "Are they preparing for the test?", "Do they prepare for tests?", "What are they preparing for?", "Is he preparing for the test?", "Они готовятся к тесту.", "Вони готуються до тесту.", "Oni przygotowują się do testu."],
["We are discussing the plan.", "Are we discussing the plan?", "Do we discuss plans?", "What are we discussing?", "Is she discussing the plan?", "Мы обсуждаем план.", "Ми обговорюємо план.", "Dyskusja o planie."],
["I am shopping for groceries.", "Are you shopping for groceries?", "Do you shop for groceries?", "What are you shopping for?", "Is she shopping for groceries?", "Я покупаю продукты.", "Я купую продукти.", "Kupuję zakupy."],
["He is fixing the car.", "Is he fixing the car?", "Does he fix cars?", "What is he fixing?", "Is she fixing the car?", "Он чинит машину.", "Він ремонтує машину.", "On naprawia samochód."],
["You are helping your friend.", "Are you helping your friend?", "Do you help your friends?", "Who are you helping?", "Is she helping her friend?", "Ты помогаешь своему другу.", "Ти допомагаєш своєму другові.", "Pomagasz swojemu przyjacielowi."],
["They are celebrating a birthday.", "Are they celebrating a birthday?", "Do they celebrate birthdays?", "What are they celebrating?", "Is he celebrating a birthday?", "Они празднуют день рождения.", "Вони святкують день народження.", "Oni świętują urodziny."],
["We are learning to dance.", "Are we learning to dance?", "Do we learn to dance?", "What are we learning?", "Is she learning to dance?", "Мы учимся танцевать.", "Ми навчаємося танцювати.", "Uczymy się tańczyć."],
["I am visiting my parents.", "Are you visiting your parents?", "Do you visit your parents?", "Who are you visiting?", "Is she visiting her parents?", "Я навещаю родителей.", "Я відвідую батьків.", "Odwiedzam rodziców."],
["He is helping his sister.", "Is he helping his sister?", "Does he help his sister?", "Who is he helping?", "Is she helping her sister?", "Он помогает сестре.", "Він допомагає сестрі.", "On pomaga siostrze."],
["You are enjoying the weather.", "Are you enjoying the weather?", "Do you enjoy the weather?", "What are you enjoying?", "Is she enjoying the weather?", "Ты наслаждаешься погодой.", "Ти насолоджуєшся погодою.", "Cieszysz się pogodą."],
["They are meeting their friends.", "Are they meeting their friends?", "Do they meet their friends?", "Who are they meeting?", "Is he meeting his friends?", "Они встречаются с друзьями.", "Вони зустрічаються з друзями.", "Spotykają się z przyjaciółmi."],
["We are planning a trip.", "Are we planning a trip?", "Do we plan trips?", "What are we planning?", "Is she planning a trip?", "Мы планируем поездку.", "Ми плануємо поїздку.", "Planujemy podróż."],
["I am watching the news.", "Are you watching the news?", "Do you watch the news?", "What are you watching?", "Is she watching the news?", "Я смотрю новости.", "Я дивлюся новини.", "Oglądam wiadomości."],
["He is working late tonight.", "Is he working late tonight?", "Does he work late?", "Why is he working late?", "Is she working late tonight?", "Он работает допоздна сегодня.", "Він працює до пізна сьогодні.", "On pracuje do późna dzisiaj."],
["You are taking a break.", "Are you taking a break?", "Do you take breaks?", "When are you taking a break?", "Is she taking a break?", "Ты делаешь перерыв.", "Ти робиш перерву.", "Robisz przerwę."],
["They are waiting for the bus.", "Are they waiting for the bus?", "Do they wait for the bus?", "Where are they waiting?", "Is he waiting for the bus?", "Они ждут автобус.", "Вони чекають автобус.", "Czekają na autobus."],
["We are enjoying the concert.", "Are we enjoying the concert?", "Do we enjoy concerts?", "What are we enjoying?", "Is she enjoying the concert?", "Мы наслаждаемся концертом.", "Ми насолоджуємося концертом.", "Cieszymy się koncertem."],
["I am cleaning the house.", "Are you cleaning the house?", "Do you clean the house?", "What are you cleaning?", "Is she cleaning the house?", "Я убираю дом.", "Я прибираю дім.", "Sprzątam dom."],
["He is taking photos.", "Is he taking photos?", "Does he take photos?", "What is he taking?", "Is she taking photos?", "Он фотографирует.", "Він фотографує.", "On robi zdjęcia."],
["You are sharing your ideas.", "Are you sharing your ideas?", "Do you share your ideas?", "What are you sharing?", "Is she sharing her ideas?", "Ты делишься своими идеями.", "Ти ділитись своїми ідеями.", "Dzielisz się swoimi pomysłami."],
["I am eating lunch.", "Are you eating lunch?", "Do you eat lunch?", "What are you eating?", "Is he eating lunch?", "Я обедаю.", "Я обідаю.", "Ja jem lunch."],
["She is reading a book.", "Is she reading a book?", "Does she read a book?", "What is she reading?", "Is he reading a book?", "Она читает книгу.", "Вона читає книгу.", "Ona czyta książkę."],
["They are playing soccer.", "Are they playing soccer?", "Do they play soccer?", "What are they playing?", "Is he playing soccer?", "Они играют в футбол.", "Вони грають у футбол.", "Oni grają w piłkę nożną."],
["We are watching a movie.", "Are we watching a movie?", "Do we watch movies?", "What are we watching?", "Is she watching a movie?", "Мы смотрим фильм.", "Ми дивимося фільм.", "Oglądamy film."],
["He is cooking dinner.", "Is he cooking dinner?", "Does he cook dinner?", "What is he cooking?", "Is she cooking dinner?", "Он готовит ужин.", "Він готує вечерю.", "On gotuje kolację."],
["You are studying for the exam.", "Are you studying for the exam?", "Do you study for exams?", "What are you studying?", "Is she studying for the exam?", "Ты готовишься к экзамену.", "Ти готуєшся до екзамену.", "Uczysz się do egzaminu."],
["I am learning English.", "Are you learning English?", "Do you learn English?", "What are you learning?", "Is he learning English?", "Я учу английский.", "Я вивчаю англійську.", "Uczę się angielskiego."],
["She is working on a project.", "Is she working on a project?", "Does she work on projects?", "What is she working on?", "Is he working on the project?", "Она работает над проектом.", "Вона працює над проектом.", "Ona pracuje nad projektem."],
["They are traveling to Paris.", "Are they traveling to Paris?", "Do they travel to Paris?", "Where are they traveling?", "Is he traveling to Paris?", "Они путешествуют в Париж.", "Вони подорожують до Парижа.", "Oni podróżują do Paryża."],
["We are playing video games.", "Are we playing video games?", "Do we play video games?", "What are we playing?", "Is she playing video games?", "Мы играем в видеоигры.", "Ми граємо у відеоігри.", "Gramy w gry wideo."],
["I am writing a letter.", "Are you writing a letter?", "Do you write letters?", "What are you writing?", "Is she writing a letter?", "Я пишу письмо.", "Я пишу листа.", "Piszę list."],
["He is painting a picture.", "Is he painting a picture?", "Does he paint pictures?", "What is he painting?", "Is she painting a picture?", "Он рисует картину.", "Він малює картину.", "On maluje obraz."],
["You are cleaning your room.", "Are you cleaning your room?", "Do you clean your room?", "What are you cleaning?", "Is she cleaning her room?", "Ты убираешь свою комнату.", "Ти прибираєш свою кімнату.", "Sprzątasz swój pokój."],
["They are preparing for the test.", "Are they preparing for the test?", "Do they prepare for tests?", "What are they preparing for?", "Is he preparing for the test?", "Они готовятся к тесту.", "Вони готуються до тесту.", "Oni przygotowują się do testu."],
["We are discussing the plan.", "Are we discussing the plan?", "Do we discuss plans?", "What are we discussing?", "Is she discussing the plan?", "Мы обсуждаем план.", "Ми обговорюємо план.", "Dyskusja o planie."],
["I am shopping for groceries.", "Are you shopping for groceries?", "Do you shop for groceries?", "What are you shopping for?", "Is she shopping for groceries?", "Я покупаю продукты.", "Я купую продукти.", "Kupuję zakupy."],
["He is fixing the car.", "Is he fixing the car?", "Does he fix cars?", "What is he fixing?", "Is she fixing the car?", "Он чинит машину.", "Він ремонтує машину.", "On naprawia samochód."],
["You are helping your friend.", "Are you helping your friend?", "Do you help your friends?", "Who are you helping?", "Is she helping her friend?", "Ты помогаешь своему другу.", "Ти допомагаєш своєму другові.", "Pomagasz swojemu przyjacielowi."],
["They are celebrating a birthday.", "Are they celebrating a birthday?", "Do they celebrate birthdays?", "What are they celebrating?", "Is he celebrating a birthday?", "Они празднуют день рождения.", "Вони святкують день народження.", "Oni świętują urodziny."],
["We are learning to dance.", "Are we learning to dance?", "Do we learn to dance?", "What are we learning?", "Is she learning to dance?", "Мы учимся танцевать.", "Ми навчаємося танцювати.", "Uczymy się tańczyć."],
["I am visiting my parents.", "Are you visiting my parents?", "Do you visit your parents?", "Who are you visiting?", "Is she visiting her parents?", "Я навещаю родителей.", "Я відвідую батьків.", "Odwiedzam rodziców."],
["He is helping his sister.", "Is he helping his sister?", "Does he help his sister?", "Who is he helping?", "Is she helping her sister?", "Он помогает сестре.", "Він допомагає сестрі.", "On pomaga siostrze."],
["You are enjoying the weather.", "Are you enjoying the weather?", "Do you enjoy the weather?", "What are you enjoying?", "Is she enjoying the weather?", "Ты наслаждаешься погодой.", "Ти насолоджуєшся погодою.", "Cieszysz się pogodą."],
["They are meeting their friends.", "Are they meeting their friends?", "Do they meet their friends?", "Who are they meeting?", "Is he meeting his friends?", "Они встречаются с друзьями.", "Вони зустрічаються з друзями.", "Spotykają się z przyjaciółmi."],
["We are planning a trip.", "Are we planning a trip?", "Do we plan trips?", "What are we planning?", "Is she planning a trip?", "Мы планируем поездку.", "Ми плануємо поїздку.", "Planujemy podróż."],
["I am watching the news.", "Are you watching the news?", "Do you watch the news?", "What are you watching?", "Is she watching the news?", "Я смотрю новости.", "Я дивлюся новини.", "Oglądam wiadomości."],
["He is working late tonight.", "Is he working late tonight?", "Does he work late?", "Why is he working late?", "Is she working late tonight?", "Он работает допоздна сегодня.", "Він працює до пізна сьогодні.", "On pracuje do późna dzisiaj."],
["You are taking a break.", "Are you taking a break?", "Do you take breaks?", "When are you taking a break?", "Is she taking a break?", "Ты делаешь перерыв.", "Ти робиш перерву.", "Robisz przerwę."],
["They are waiting for the bus.", "Are they waiting for the bus?", "Do they wait for the bus?", "Where are they waiting?", "Is he waiting for the bus?", "Они ждут автобус.", "Вони чекають автобус.", "Czekają na autobus."],
["We are enjoying the concert.", "Are we enjoying the concert?", "Do we enjoy concerts?", "What are we enjoying?", "Is she enjoying the concert?", "Мы наслаждаемся концертом.", "Ми насолоджуємося концертом.", "Cieszymy się koncertem."],
["I am cleaning the house.", "Are you cleaning the house?", "Do you clean the house?", "What are you cleaning?", "Is she cleaning the house?", "Я убираю дом.", "Я прибираю дім.", "Sprzątam dom."],
["He is taking photos.", "Is he taking photos?", "Does he take photos?", "What is he taking?", "Is she taking photos?", "Он фотографирует.", "Він фотографує.", "On robi zdjęcia."],
["You are sharing your ideas.", "Are you sharing your ideas?", "Do you share your ideas?", "What are you sharing?", "Is she sharing her ideas?", "Ты делишься своими идеями.", "Ти ділитись своїми ідеями.", "Dzielisz się swoimi pomysłami."],
["I am eating lunch.", "Are you eating lunch?", "Do you eat lunch?", "What are you eating?", "Is he eating lunch?", "Я обедаю.", "Я обідаю.", "Ja jem lunch."],
["She is reading a book.", "Is she reading a book?", "Does she read a book?", "What is she reading?", "Is he reading a book?", "Она читает книгу.", "Вона читає книгу.", "Ona czyta książkę."],
["They are playing soccer.", "Are they playing soccer?", "Do they play soccer?", "What are they playing?", "Is he playing soccer?", "Они играют в футбол.", "Вони грають у футбол.", "Oni grają w piłkę nożną."],
["We are watching a movie.", "Are we watching a movie?", "Do we watch movies?", "What are we watching?", "Is she watching a movie?", "Мы смотрим фильм.", "Ми дивимося фільм.", "Oglądamy film."],
["He is cooking dinner.", "Is he cooking dinner?", "Does he cook dinner?", "What is he cooking?", "Is she cooking dinner?", "Он готовит ужин.", "Він готує вечерю.", "On gotuje kolację."],
["You are studying for the exam.", "Are you studying for the exam?", "Do you study for exams?", "What are you studying?", "Is she studying for the exam?", "Ты готовишься к экзамену.", "Ти готуєшся до екзамену.", "Uczysz się do egzaminu."],
["I am learning English.", "Are you learning English?", "Do you learn English?", "What are you learning?", "Is he learning English?", "Я учу английский.", "Я вивчаю англійську.", "Uczę się angielskiego."],
["She is working on a project.", "Is she working on a project?", "Does she work on projects?", "What is she working on?", "Is he working on the project?", "Она работает над проектом.", "Вона працює над проектом.", "Ona pracuje nad projektem."],
["They are traveling to Paris.", "Are they traveling to Paris?", "Do they travel to Paris?", "Where are they traveling?", "Is he traveling to Paris?", "Они путешествуют в Париж.", "Вони подорожують до Парижа.", "Oni podróżują do Paryża."],
["We are playing video games.", "Are we playing video games?", "Do we play video games?", "What are we playing?", "Is she playing video games?", "Мы играем в видеоигры.", "Ми граємо у відеоігри.", "Gramy w gry wideo."],
["I am writing a letter.", "Are you writing a letter?", "Do you write letters?", "What are you writing?", "Is she writing a letter?", "Я пишу письмо.", "Я пишу листа.", "Piszę list."],
["He is painting a picture.", "Is he painting a picture?", "Does he paint pictures?", "What is he painting?", "Is she painting a picture?", "Он рисует картину.", "Він малює картину.", "On maluje obraz."],
["You are cleaning your room.", "Are you cleaning your room?", "Do you clean your room?", "What are you cleaning?", "Is she cleaning her room?", "Ты убираешь свою комнату.", "Ти прибираєш свою кімнату.", "Sprzątasz swój pokój."],
["They are preparing for the test.", "Are they preparing for the test?", "Do they prepare for tests?", "What are they preparing for?", "Is he preparing for the test?", "Они готовятся к тесту.", "Вони готуються до тесту.", "Oni przygotowują się do testu."],
["We are discussing the plan.", "Are we discussing the plan?", "Do we discuss plans?", "What are we discussing?", "Is she discussing the plan?", "Мы обсуждаем план.", "Ми обговорюємо план.", "Dyskusja o planie."],
["I am shopping for groceries.", "Are you shopping for groceries?", "Do you shop for groceries?", "What are you shopping for?", "Is she shopping for groceries?", "Я покупаю продукты.", "Я купую продукти.", "Kupuję zakupy."],
["He is fixing the car.", "Is he fixing the car?", "Does he fix cars?", "What is he fixing?", "Is she fixing the car?", "Он чинит машину.", "Він ремонтує машину.", "On naprawia samochód."],
["You are helping your friend.", "Are you helping your friend?", "Do you help your friends?", "Who are you helping?", "Is she helping her friend?", "Ты помогаешь своему другу.", "Ти допомагаєш своєму другові.", "Pomagasz swojemu przyjacielowi."],
["They are celebrating a birthday.", "Are they celebrating a birthday?", "Do they celebrate birthdays?", "What are they celebrating?", "Is he celebrating a birthday?", "Они празднуют день рождения.", "Вони святкують день народження.", "Oni świętują urodziny."],
["We are learning to dance.", "Are we learning to dance?", "Do we learn to dance?", "What are we learning?", "Is she learning to dance?", "Мы учимся танцевать.", "Ми навчаємося танцювати.", "Uczymy się tańczyć."],
["I am visiting my parents.", "Are you visiting my parents?", "Do you visit your parents?", "Who are you visiting?", "Is she visiting her parents?", "Я навещаю родителей.", "Я відвідую батьків.", "Odwiedzam rodziców."],
["He is helping his sister.", "Is he helping his sister?", "Does he help his sister?", "Who is he helping?", "Is she helping her sister?", "Он помогает сестре.", "Він допомагає сестрі.", "On pomaga siostrze."],
["You are enjoying the weather.", "Are you enjoying the weather?", "Do you enjoy the weather?", "What are you enjoying?", "Is she enjoying the weather?", "Ты наслаждаешься погодой.", "Ти насолоджуєшся погодою.", "Cieszysz się pogodą."],
["They are meeting their friends.", "Are they meeting their friends?", "Do they meet their friends?", "Who are they meeting?", "Is he meeting his friends?", "Они встречаются с друзьями.", "Вони зустрічаються з друзями.", "Spotykają się z przyjaciółmi."],
["We are planning a trip.", "Are we planning a trip?", "Do we plan trips?", "What are we planning?", "Is she planning a trip?", "Мы планируем поездку.", "Ми плануємо поїздку.", "Planujemy podróż."],
["I am watching the news.", "Are you watching the news?", "Do you watch the news?", "What are you watching?", "Is she watching the news?", "Я смотрю новости.", "Я дивлюся новини.", "Oglądam wiadomości."],
["He is working late tonight.", "Is he working late tonight?", "Does he work late?", "Why is he working late?", "Is she working late tonight?", "Он работает допоздна сегодня.", "Він працює до пізна сьогодні.", "On pracuje do późna dzisiaj."],
["You are taking a break.", "Are you taking a break?", "Do you take breaks?", "When are you taking a break?", "Is she taking a break?", "Ты делаешь перерыв.", "Ти робиш перерву.", "Robisz przerwę."],
["They are waiting for the bus.", "Are they waiting for the bus?", "Do they wait for the bus?", "Where are they waiting?", "Is he waiting for the bus?", "Они ждут автобус.", "Вони чекають автобус.", "Czekają na autobus."],
["We are enjoying the concert.", "Are we enjoying the concert?", "Do we enjoy concerts?", "What are we enjoying?", "Is she enjoying the concert?", "Мы наслаждаемся концертом.", "Ми насолоджуємося концертом.", "Cieszymy się koncertem."],
["I am cleaning the house.", "Are you cleaning the house?", "Do you clean the house?", "What are you cleaning?", "Is she cleaning the house?", "Я убираю дом.", "Я прибираю дім.", "Sprzątam dom."],
["He is taking photos.", "Is he taking photos?", "Does he take photos?", "What is he taking?", "Is she taking photos?", "Он фотографирует.", "Він фотографує.", "On robi zdjęcia."],
["You are sharing your ideas.", "Are you sharing your ideas?", "Do you share your ideas?", "What are you sharing?", "Is she sharing her ideas?", "Ты делишься своими идеями.", "Ти ділитись своїми ідеями.", "Dzielisz się swoimi pomysłami."],
["I eat breakfast every morning.", "Do you eat breakfast every morning?", "Are you eating breakfast every morning?", "Did you eat breakfast yesterday?", "Will you eat breakfast tomorrow?", "Я завтракаю каждое утро.", "Я їм сніданок щоранку.", "Jem śniadanie każdego ranka."],
    ["She does not like chocolate.", "Does she like chocolate?", "Is she liking chocolate?", "Has she liked chocolate?", "Did she not like chocolate before?", "Она не любит шоколад.", "Вона не любить шоколад.", "Ona nie lubi czekolady."],
    ["They play football on weekends.", "Do they play football on weekends?", "Are they playing football on weekends?", "Were they playing football last weekend?", "Have they played football this month?", "Они играют в футбол по выходным.", "Вони грають у футбол на вихідних.", "Oni grają w piłkę nożną w weekendy."],
    ["He studies hard for his exams.", "Does he study hard for his exams?", "Is he studying hard for his exams?", "Did he study hard last year?", "Will he study hard next semester?", "Он усердно учится к экзаменам.", "Він наполегливо навчається до іспитів.", "On ciężko studiuje do swoich egzaminów."],
    ["We do not watch TV at night.", "Do we watch TV at night?", "Are we watching TV at night?", "Have we watched TV this week?", "Did we not watch TV yesterday?", "Мы не смотрим телевизор по ночам.", "Ми не дивимось телевізор вночі.", "Nie oglądamy telewizji w nocy."],
    ["You work in a big company.", "Do you work in a big company?", "Are you working in a big company?", "Have you worked in this company before?", "Will you work in this company next year?", "Вы работаете в большой компании.", "Ви працюєте у великій компанії.", "Pracujesz w dużej firmie."],
    ["I do not go to the gym.", "Do you go to the gym?", "Are you going to the gym?", "Did you go to the gym last week?", "Will you go to the gym tomorrow?", "Я не хожу в спортзал.", "Я не ходжу в спортзал.", "Nie chodzę na siłownię."],
    ["She loves to read books.", "Does she love to read books?", "Is she loving to read books?", "Has she loved this book?", "Did she love to read last summer?", "Она любит читать книги.", "Вона любить читати книги.", "Ona uwielbia czytać książki."],
    ["They do not travel often.", "Do they travel often?", "Are they traveling often?", "Have they traveled to Europe?", "Did they travel last summer?", "Они не путешествуют часто.", "Вони не подорожують часто.", "Oni nie podróżują często."],
    ["He plays the guitar beautifully.", "Does he play the guitar beautifully?", "Is he playing the guitar beautifully?", "Did he play the guitar last night?", "Will he play the guitar tomorrow?", "Он прекрасно играет на гитаре.", "Він чудово грає на гітарі.", "On pięknie gra na gitarze."],
    ["We do not eat meat.", "Do we eat meat?", "Are we eating meat?", "Have we eaten meat this week?", "Did we eat meat last weekend?", "Мы не едим мясо.", "Ми не їмо м'ясо.", "Nie jemy mięsa."],
    ["I eat breakfast every morning.", "Do you eat breakfast every morning?", "Are you eating breakfast every morning?", "Did you eat breakfast yesterday?", "Will you eat breakfast tomorrow?", "Я завтракаю каждое утро.", "Я їм сніданок щоранку.", "Jem śniadanie każdego ranka."],
    ["She does not like chocolate.", "Does she like chocolate?", "Is she liking chocolate?", "Has she liked chocolate?", "Did she not like chocolate before?", "Она не любит шоколад.", "Вона не любить шоколад.", "Ona nie lubi czekolady."],
    ["They play football on weekends.", "Do they play football on weekends?", "Are they playing football on weekends?", "Were they playing football last weekend?", "Have they played football this month?", "Они играют в футбол по выходным.", "Вони грають у футбол на вихідних.", "Oni grają w piłkę nożną w weekendy."],
    ["He studies hard for his exams.", "Does he study hard for his exams?", "Is he studying hard for his exams?", "Did he study hard last year?", "Will he study hard next semester?", "Он усердно учится к экзаменам.", "Він наполегливо навчається до іспитів.", "On ciężko studiuje do swoich egzaminów."],
    ["We do not watch TV at night.", "Do we watch TV at night?", "Are we watching TV at night?", "Have we watched TV this week?", "Did we not watch TV yesterday?", "Мы не смотрим телевизор по ночам.", "Ми не дивимось телевізор вночі.", "Nie oglądamy telewizji w nocy."],
    ["You work in a big company.", "Do you work in a big company?", "Are you working in a big company?", "Have you worked in this company before?", "Will you work in this company next year?", "Вы работаете в большой компании.", "Ви працюєте у великій компанії.", "Pracujesz w dużej firmie."],
    ["I do not go to the gym.", "Do you go to the gym?", "Are you going to the gym?", "Did you go to the gym last week?", "Will you go to the gym tomorrow?", "Я не хожу в спортзал.", "Я не ходжу в спортзал.", "Nie chodzę na siłownię."],
    ["She loves to read books.", "Does she love to read books?", "Is she loving to read books?", "Has she loved this book?", "Did she love to read last summer?", "Она любит читать книги.", "Вона любить читати книги.", "Ona uwielbia czytać książki."],
    ["They do not travel often.", "Do they travel often?", "Are they traveling often?", "Have they traveled to Europe?", "Did they travel last summer?", "Они не путешествуют часто.", "Вони не подорожують часто.", "Oni nie podróżują często."],
    ["He plays the guitar beautifully.", "Does he play the guitar beautifully?", "Is he playing the guitar beautifully?", "Did he play the guitar last night?", "Will he play the guitar tomorrow?", "Он прекрасно играет на гитаре.", "Він чудово грає на гітарі.", "On pięknie gra na gitarze."],
    ["We do not eat meat.", "Do we eat meat?", "Are we eating meat?", "Have we eaten meat this week?", "Did we eat meat last weekend?", "Мы не едим мясо.", "Ми не їмо м'ясо.", "Nie jemy mięsa."],
    ["I walk my dog every day.", "Do you walk your dog every day?", "Are you walking your dog every day?", "Did you walk your dog yesterday?", "Will you walk your dog tomorrow?", "Я гуляю со своей собакой каждый день.", "Я вигулюю свою собаку кожного дня.", "Wyprowadzam swojego psa każdego dnia."],
    ["She works late on Fridays.", "Does she work late on Fridays?", "Is she working late on Fridays?", "Did she work late last Friday?", "Will she work late next week?", "Она работает допоздна по пятницам.", "Вона працює допізна в п'ятницю.", "Pracuje do późna w piątki."],
    ["They do not study on weekends.", "Do they study on weekends?", "Are they studying on weekends?", "Did they study last weekend?", "Will they study next weekend?", "Они не учатся по выходным.", "Вони не навчаються на вихідних.", "Oni się nie uczą w weekendy."],
    ["He speaks three languages.", "Does he speak three languages?", "Is he speaking three languages?", "Has he spoken three languages before?", "Did he speak three languages last year?", "Он говорит на трёх языках.", "Він говорить трьома мовами.", "On mówi trzema językami."],
    ["We do not go out often.", "Do we go out often?", "Are we going out often?", "Did we go out last night?", "Will we go out tonight?", "Мы не часто выходим.", "Ми не часто виходимо.", "Nie wychodzimy często."],
    ["You eat lunch at noon.", "Do you eat lunch at noon?", "Are you eating lunch at noon?", "Did you eat lunch yesterday?", "Will you eat lunch tomorrow?", "Вы обедаете в полдень.", "Ви обідаєте о дванадцятій.", "Obiadacie o dwunastej."],
    ["I do not read newspapers.", "Do you read newspapers?", "Are you reading newspapers?", "Did you read newspapers last week?", "Will you read newspapers this weekend?", "Я не читаю газеты.", "Я не читаю газети.", "Nie czytam gazet."],
    ["She writes emails every day.", "Does she write emails every day?", "Is she writing emails every day?", "Has she written emails this week?", "Did she write emails last week?", "Она пишет письма каждый день.", "Вона пише електронні листи щодня.", "Ona pisze maile codziennie."],
    ["They do not play video games.", "Do they play video games?", "Are they playing video games?", "Have they played video games recently?", "Did they play video games last night?", "Они не играют в видеоигры.", "Вони не грають у відеоігри.", "Oni nie grają w gry wideo."],
    ["He teaches mathematics.", "Does he teach mathematics?", "Is he teaching mathematics?", "Did he teach mathematics last year?", "Will he teach mathematics next semester?", "Он преподает математику.", "Він викладає математику.", "On uczy matematyki."],
    ["We do not have pets.", "Do we have pets?", "Are we having pets?", "Did we have pets last year?", "Will we have pets next year?", "У нас нет домашних животных.", "У нас немає домашніх тварин.", "Nie mamy zwierząt domowych."],
    ["You drive a car to work.", "Do you drive a car to work?", "Are you driving a car to work?", "Did you drive a car to work last week?", "Will you drive a car to work tomorrow?", "Вы ездите на машине на работу.", "Ви їдете на роботу на машині.", "Jeździsz do pracy samochodem."],
    ["I do not like to dance.", "Do you like to dance?", "Are you liking to dance?", "Did you like to dance last weekend?", "Will you like to dance at the party?", "Мне не нравится танцевать.", "Мені не подобається танцювати.", "Nie lubię tańczyć."],
    ["She goes shopping on Saturdays.", "Does she go shopping on Saturdays?", "Is she going shopping on Saturdays?", "Did she go shopping last Saturday?", "Will she go shopping next Saturday?", "Она ходит за покупками по субботам.", "Вона ходить за покупками в суботу.", "Ona chodzi na zakupy w soboty."],
    ["They do not call me often.", "Do they call you often?", "Are they calling you often?", "Did they call you last week?", "Will they call you tomorrow?", "Они не звонят мне часто.", "Вони не телефонують мені часто.", "Oni nie dzwonią do mnie często."],
    ["He listens to music every day.", "Does he listen to music every day?", "Is he listening to music every day?", "Did he listen to music yesterday?", "Will he listen to music tomorrow?", "Он слушает музыку каждый день.", "Він слухає музику щодня.", "On słucha muzyki codziennie."],
    ["We do not swim in the pool.", "Do we swim in the pool?", "Are we swimming in the pool?", "Did we swim in the pool last week?", "Will we swim in the pool next summer?", "Мы не плаваем в бассейне.", "Ми не плаваємо в басейні.", "Nie pływamy w basenie."],
    ["You write stories.", "Do you write stories?", "Are you writing stories?", "Did you write a story last week?", "Will you write a story tomorrow?", "Ты пишешь истории.", "Ти пишеш історії.", "Piszesz opowiadania."],
    ["They do not enjoy their job.", "Do they enjoy their job?", "Are they enjoying their job?", "Did they enjoy their job last year?", "Will they enjoy their job in the future?", "Им не нравится их работа.", "Їм не подобається їхня робота.", "Nie podoba im się ich praca."],
    ["He eats lunch at noon.", "Does he eat lunch at noon?", "Is he eating lunch at noon?", "Did he eat lunch yesterday?", "Will he eat lunch tomorrow?", "Он обедает в полдень.", "Він обідає о дванадцятій.", "On je obiad w południe."],
    ["We do not play sports.", "Do we play sports?", "Are we playing sports?", "Did we play sports last weekend?", "Will we play sports next month?", "Мы не занимаемся спортом.", "Ми не займаємося спортом.", "Nie uprawiamy sportu."],
    ["She talks to her friends often.", "Does she talk to her friends often?", "Is she talking to her friends often?", "Did she talk to her friends last week?", "Will she talk to her friends this weekend?", "Она часто разговаривает с друзьями.", "Вона часто розмовляє з друзями.", "Ona często rozmawia z przyjaciółmi."],
    ["You do not attend classes regularly.", "Do you attend classes regularly?", "Are you attending classes regularly?", "Did you attend classes last semester?", "Will you attend classes next semester?", "Вы не посещаете занятия регулярно.", "Ви не відвідуєте заняття регулярно.", "Nie uczęszczasz na zajęcia regularnie."],
    ["He reads a book every night.", "Does he read a book every night?", "Is he reading a book every night?", "Did he read a book last night?", "Will he read a book tonight?", "Он читает книгу каждую ночь.", "Він читає книгу щоночі.", "On czyta książkę każdej nocy."],
    ["They do not like to swim.", "Do they like to swim?", "Are they liking to swim?", "Did they like to swim last summer?", "Will they like to swim next summer?", "Им не нравится плавать.", "Їм не подобається плавати.", "Nie lubią pływać."],
    ["I do not visit my grandparents often.", "Do you visit your grandparents often?", "Are you visiting your grandparents often?", "Did you visit your grandparents last week?", "Will you visit your grandparents this weekend?", "Я не часто навещаю бабушку и дедушку.", "Я не часто відвідую бабусю і дідуся.", "Nie odwiedzam dziadków często."],
    ["She enjoys listening to music.", "Does she enjoy listening to music?", "Is she enjoying listening to music?", "Did she enjoy listening to music last weekend?", "Will she enjoy listening to music tonight?", "Она любит слушать музыку.", "Вона любить слухати музику.", "Ona lubi słuchać muzyki."],
    ["We do not go to the beach.", "Do we go to the beach?", "Are we going to the beach?", "Did we go to the beach last summer?", "Will we go to the beach this summer?", "Мы не ходим на пляж.", "Ми не ходимо на пляж.", "Nie chodzimy na plażę."],
    ["He drinks coffee in the morning.", "Does he drink coffee in the morning?", "Is he drinking coffee in the morning?", "Did he drink coffee yesterday?", "Will he drink coffee tomorrow?", "Он пьет кофе по утрам.", "Він п'є каву вранці.", "On pije kawę rano."],
    ["You do not play the piano.", "Do you play the piano?", "Are you playing the piano?", "Did you play the piano last year?", "Will you play the piano at the concert?", "Ты не играешь на пианино.", "Ти не граєш на піаніно.", "Nie grasz na pianinie."],
    ["They go to school every day.", "Do they go to school every day?", "Are they going to school every day?", "Did they go to school yesterday?", "Will they go to school tomorrow?", "Они ходят в школу каждый день.", "Вони ходять до школи кожного дня.", "Oni idą do szkoły każdego dnia."],
    ["I do not work on Sundays.", "Do you work on Sundays?", "Are you working on Sundays?", "Did you work on Sunday?", "Will you work on Sunday?", "Я не работаю по воскресеньям.", "Я не працюю в неділю.", "Nie pracuję w niedzielę."],
    ["She loves to cook.", "Does she love to cook?", "Is she loving to cook?", "Did she love to cook last week?", "Will she love to cook tomorrow?", "Она любит готовить.", "Вона любить готувати.", "Ona uwielbia gotować."],
    ["We do not go shopping on weekends.", "Do we go shopping on weekends?", "Are we going shopping on weekends?", "Did we go shopping last weekend?", "Will we go shopping next weekend?", "Мы не ходим за покупками по выходным.", "Ми не ходимо на покупки на вихідних.", "Nie chodzimy na zakupy w weekendy."],
    ["He watches movies every Saturday.", "Does he watch movies every Saturday?", "Is he watching movies every Saturday?", "Did he watch a movie last Saturday?", "Will he watch a movie tomorrow?", "Он смотрит фильмы каждую субботу.", "Він дивиться фільми кожну суботу.", "On ogląda filmy w każdą sobotę."],
    ["You do not clean your room.", "Do you clean your room?", "Are you cleaning your room?", "Did you clean your room yesterday?", "Will you clean your room tomorrow?", "Ты не убираешь свою комнату.", "Ти не прибираєш свою кімнату.", "Nie sprzątasz swojego pokoju."],
    ["They enjoy playing board games.", "Do they enjoy playing board games?", "Are they enjoying playing board games?", "Did they enjoy playing board games last weekend?", "Will they enjoy playing board games tonight?", "Им нравится играть в настольные игры.", "Їм подобається грати в настільні ігри.", "Oni lubią grać w gry planszowe."],
    ["I do not like to cook.", "Do you like to cook?", "Are you liking to cook?", "Did you like to cook last week?", "Will you like to cook tomorrow?", "Мне не нравится готовить.", "Мені не подобається готувати.", "Nie lubię gotować."],
    ["He plays soccer every Friday.", "Does he play soccer every Friday?", "Is he playing soccer every Friday?", "Did he play soccer last week?", "Will he play soccer tomorrow?", "Он играет в футбол каждую пятницу.", "Він грає у футбол кожну п'ятницю.", "On gra w piłkę nożną w każdy piątek."],
    ["You do not drive a motorcycle.", "Do you drive a motorcycle?", "Are you driving a motorcycle?", "Did you drive a motorcycle last summer?", "Will you drive a motorcycle next year?", "Ты не водишь мотоцикл.", "Ти не їдеш на мотоциклі.", "Nie jeździsz na motocyklu."],
    ["They go for walks in the park.", "Do they go for walks in the park?", "Are they going for walks in the park?", "Did they go for a walk yesterday?", "Will they go for a walk tomorrow?", "Они гуляют в парке.", "Вони гуляють у парку.", "Oni spacerują w parku."],
    ["We do not listen to the radio.", "Do we listen to the radio?", "Are we listening to the radio?", "Did we listen to the radio yesterday?", "Will we listen to the radio tomorrow?", "Мы не слушаем радио.", "Ми не слухаємо радіо.", "Nie słuchamy radia."],
    ["I brush my teeth every day.", "Do you brush your teeth every day?", "Are you brushing your teeth every day?", "Did you brush your teeth this morning?", "Will you brush your teeth tonight?", "Я чищу зубы каждый день.", "Я чищу зуби щодня.", "Szczotkuję zęby każdego dnia."],
    ["She does not write letters.", "Does she write letters?", "Is she writing letters?", "Did she write a letter last week?", "Will she write a letter tomorrow?", "Она не пишет письма.", "Вона не пише листи.", "Ona nie pisze listów."],
    ["He does not study on weekends.", "Does he study on weekends?", "Is he studying on weekends?", "Did he study last weekend?", "Will he study this weekend?", "Он не учится по выходным.", "Він не навчається на вихідних.", "On nie uczy się w weekendy."],
    ["We play board games every Friday.", "Do we play board games every Friday?", "Are we playing board games every Friday?", "Did we play board games last week?", "Will we play board games tomorrow?", "Мы играем в настольные игры каждую пятницу.", "Ми граємо в настільні ігри кожну п'ятницю.", "Gramy w gry planszowe w każdy piątek."],
    ["You do not visit the museum often.", "Do you visit the museum often?", "Are you visiting the museum often?", "Did you visit the museum last month?", "Will you visit the museum this weekend?", "Вы не часто посещаете музей.", "Ви не часто відвідуєте музей.", "Nie odwiedzacie muzeum często."],
    ["She reads the news every morning.", "Does she read the news every morning?", "Is she reading the news every morning?", "Did she read the news yesterday?", "Will she read the news tomorrow?", "Она читает новости каждое утро.", "Вона читає новини щоранку.", "Ona czyta wiadomości każdego ranka."],
    ["I do not play video games.", "Do you play video games?", "Are you playing video games?", "Did you play video games last night?", "Will you play video games tonight?", "Я не играю в видеоигры.", "Я не граю у відеоігри.", "Nie gram w gry wideo."],
    ["They visit their relatives every summer.", "Do they visit their relatives every summer?", "Are they visiting their relatives this summer?", "Did they visit their relatives last summer?", "Will they visit their relatives this summer?", "Они навещают своих родственников каждое лето.", "Вони відвідують своїх родичів кожного літа.", "Oni odwiedzają swoich krewnych każdego lata."],
    ["He does not ride a bicycle.", "Does he ride a bicycle?", "Is he riding a bicycle?", "Did he ride a bicycle last weekend?", "Will he ride a bicycle tomorrow?", "Он не катается на велосипеде.", "Він не їздить на велосипеді.", "On nie jeździ na rowerze."],
    ["We do not travel abroad every year.", "Do we travel abroad every year?", "Are we traveling abroad this year?", "Did we travel abroad last year?", "Will we travel abroad next year?", "Мы не путешествуем за границу каждый год.", "Ми не подорожуємо за кордон кожного року.", "Nie podróżujemy za granicę co roku."],
    ["You drink tea every evening.", "Do you drink tea every evening?", "Are you drinking tea right now?", "Did you drink tea yesterday evening?", "Will you drink tea tonight?", "Ты пьешь чай каждый вечер.", "Ти п'єш чай щоночі.", "Pijesz herbatę każdego wieczoru."],
    ["They do not celebrate holidays.", "Do they celebrate holidays?", "Are they celebrating holidays this year?", "Did they celebrate holidays last year?", "Will they celebrate holidays this year?", "Они не отмечают праздники.", "Вони не святкують свята.", "Oni nie obchodzą świąt."],
    ["I write in my journal every night.", "Do you write in your journal?", "Are you writing in your journal right now?", "Did you write in your journal last night?", "Will you write in your journal tomorrow?", "Я пишу в своем дневнике каждую ночь.", "Я пишу в своєму щоденнику щоночі.", "Piszę w moim dzienniku każdej nocy."],
    ["She does not wear a coat in summer.", "Does she wear a coat in summer?", "Is she wearing a coat right now?", "Did she wear a coat last summer?", "Will she wear a coat this summer?", "Она не носит пальто летом.", "Вона не носить пальто влітку.", "Ona nie nosi płaszcza latem."],
    ["We play chess on Sundays.", "Do we play chess on Sundays?", "Are we playing chess this Sunday?", "Did we play chess last Sunday?", "Will we play chess next Sunday?", "Мы играем в шахматы по воскресеньям.", "Ми граємо в шахи в неділю.", "Gramy w szachy w niedzielę."],
    ["He does not go fishing.", "Does he go fishing?", "Is he going fishing this weekend?", "Did he go fishing last month?", "Will he go fishing next month?", "Он не ходит на рыбалку.", "Він не ходить на рибалку.", "On nie chodzi na ryby."],
    ["You do not exercise regularly.", "Do you exercise regularly?", "Are you exercising right now?", "Did you exercise last week?", "Will you exercise this week?", "Ты не занимаешься регулярно.", "Ти не займаєшся регулярно.", "Nie ćwiczysz regularnie."],
    ["They do not eat fast food.", "Do they eat fast food?", "Are they eating fast food right now?", "Did they eat fast food last weekend?", "Will they eat fast food tomorrow?", "Они не едят фаст-фуд.", "Вони не їдять швидку їжу.", "Oni nie jedzą fast foodu."],
    ["I do not like to read fiction.", "Do you like to read fiction?", "Are you liking to read fiction?", "Did you like to read fiction last month?", "Will you like to read fiction this month?", "Мне не нравится читать художественную литературу.", "Мені не подобається читати художню літературу.", "Nie lubię czytać fikcji."],
 /*индекс 360*/   ["She plays the guitar every weekend.", "Does she play the guitar every weekend?", "Is she playing the guitar right now?", "Did she play the guitar last weekend?", "Will she play the guitar at the concert?", "Она играет на гитаре каждые выходные.", "Вона грає на гітарі кожні вихідні.", "Ona gra na gitarze w każdy weekend."],
    [
        "I am not watching TV.",
        "Are you not watching TV?",
        "Do you not watch TV?",
        "Were you not watching TV?",
        "Will you not be watching TV?",
        "Я не смотрю телевизор.",
        "Я не дивлюсь телевізор.",
        "Nie oglądam telewizji."
    ],
    [
        "She is not eating breakfast.",
        "Is she not eating breakfast?",
        "Does she not eat breakfast?",
        "Has she not been eating breakfast?",
        "Would she not be eating breakfast?",
        "Она не завтракает.",
        "Вона не снідає.",
        "Ona nie je śniadania."
    ],
    [
        "They are not playing football.",
        "Are they not playing football?",
        "Do they not play football?",
        "Were they not playing football?",
        "Are they not going to play football?",
        "Они не играют в футбол.",
        "Вони не грають у футбол.",
        "Oni nie grają w piłkę nożną."
    ],
    [
        "He is not studying right now.",
        "Is he not studying right now?",
        "Does he not study right now?",
        "Was he not studying right now?",
        "Might he not be studying right now?",
        "Он сейчас не учится.",
        "Він зараз не навчається.",
        "On teraz się nie uczy."
    ],
    [
        "We are not going to the party.",
        "Are we not going to the party?",
        "Do we not go to the party?",
        "Had we not been going to the party?",
        "Will we not be going to the party?",
        "Мы не идем на вечеринку.",
        "Ми не йдемо на вечірку.",
        "Nie idziemy na imprezę."
    ],
    [
        "You are not working today.",
        "Are you not working today?",
        "Do you not work today?",
        "Were you not working today?",
        "Would you not be working today?",
        "Ты сегодня не работаешь.",
        "Ти сьогодні не працюєш.",
        "Nie pracujesz dzisiaj."
    ],
    [
        "I am not reading a book.",
        "Are you not reading a book?",
        "Do you not read a book?",
        "Had I not been reading a book?",
        "Might I not be reading a book?",
        "Я не читаю книгу.",
        "Я не читаю книжку.",
        "Nie czytam książki."
    ],
    [
        "She is not driving the car.",
        "Is she not driving the car?",
        "Does she not drive the car?",
        "Was she not driving the car?",
        "Will she not be driving the car?",
        "Она не водит машину.",
        "Вона не їздить на машині.",
        "Ona nie prowadzi samochodu."
    ],
    [
        "They are not studying together.",
        "Are they not studying together?",
        "Do they not study together?",
        "Were they not studying together?",
        "Would they not be studying together?",
        "Они не учатся вместе.",
        "Вони не навчаються разом.",
        "Oni nie uczą się razem."
    ],
    [
        "He is not playing the guitar.",
        "Is he not playing the guitar?",
        "Does he not play the guitar?",
        "Had he not been playing the guitar?",
        "Might he not be playing the guitar?",
        "Он не играет на гитаре.",
        "Він не грає на гітарі.",
        "On nie gra na gitarze."
    ],
    [
        "We are not having dinner.",
        "Are we not having dinner?",
        "Do we not have dinner?",
        "Were we not having dinner?",
        "Will we not be having dinner?",
        "Мы не ужинаем.",
        "Ми не вечеряємо.",
        "Nie jemy kolacji."
    ],
    [
        "You are not running in the park.",
        "Are you not running in the park?",
        "Do you not run in the park?",
        "Were you not running in the park?",
        "Will you not be running in the park?",
        "Ты не бегаете в парке.",
        "Ти не бігаєш у парку.",
        "Nie biegasz w parku."
    ],
    [
        "They are not watching a movie.",
        "Are they not watching a movie?",
        "Do they not watch a movie?",
        "Were they not watching a movie?",
        "Will they not be watching a movie?",
        "Они не смотрят фильм.",
        "Вони не дивляться фільм.",
        "Oni nie oglądają filmu."
    ],
    [
        "She is not writing a letter.",
        "Is she not writing a letter?",
        "Does she not write a letter?",
        "Had she not been writing a letter?",
        "Might she not be writing a letter?",
        "Она не пишет письмо.",
        "Вона не пише листа.",
        "Ona nie pisze listu."
    ],
    [
        "He is not playing soccer.",
        "Is he not playing soccer?",
        "Does he not play soccer?",
        "Was he not playing soccer?",
        "Would he not be playing soccer?",
        "Он не играет в футбол.",
        "Він не грає у футбол.",
        "On nie gra w piłkę nożną."
    ],
    [
        "We are not traveling this summer.",
        "Are we not traveling this summer?",
        "Do we not travel this summer?",
        "Had we not been traveling this summer?",
        "Will we not be traveling this summer?",
        "Мы не путешествуем этим летом.",
        "Ми не подорожуємо цього літа.",
        "Nie podróżujemy tego lata."
    ],
    [
        "I am not learning English.",
        "Are you not learning English?",
        "Do you not learn English?",
        "Were you not learning English?",
        "Will you not be learning English?",
        "Я не учу английский.",
        "Я не вивчаю англійську.",
        "Nie uczę się angielskiego."
    ],
    [
        "They are not cleaning the house.",
        "Are they not cleaning the house?",
        "Do they not clean the house?",
        "Were they not cleaning the house?",
        "Might they not be cleaning the house?",
        "Они не убирают дом.",
        "Вони не прибирають дім.",
        "Oni nie sprzątają domu."
    ],
    [
        "He is not reading a book.",
        "Is he not reading a book?",
        "Does he not read a book?",
        "Had he not been reading a book?",
        "Will he not be reading a book?",
        "Он не читает книгу.",
        "Він не читає книжку.",
        "On nie czyta książki."
    ],
    [
        "She is not swimming in the pool.",
        "Is she not swimming in the pool?",
        "Does she not swim in the pool?",
        "Was she not swimming in the pool?",
        "Will she not be swimming in the pool?",
        "Она не плавает в бассейне.",
        "Вона не плаває у басейні.",
        "Ona nie pływa w basenie."
    ],
    [
        "We are not discussing the project.",
        "Are we not discussing the project?",
        "Do we not discuss the project?",
        "Were we not discussing the project?",
        "Will we not be discussing the project?",
        "Мы не обсуждаем проект.",
        "Ми не обговорюємо проект.",
        "Nie omawiamy projektu."
    ],
    [
        "You are not playing guitar.",
        "Are you not playing guitar?",
        "Do you not play guitar?",
        "Had you not been playing guitar?",
        "Might you not be playing guitar?",
        "Ты не играешь на гитаре.",
        "Ти не граєш на гітарі.",
        "Nie grasz na gitarze."
    ],
    [
        "They are not studying for the exam.",
        "Are they not studying for the exam?",
        "Do they not study for the exam?",
        "Were they not studying for the exam?",
        "Will they not be studying for the exam?",
        "Они не готовятся к экзамену.",
        "Вони не готуються до іспиту.",
        "Oni nie przygotowują się do egzaminu."
    ],
    [
        "He is not working at the office.",
        "Is he not working at the office?",
        "Does he not work at the office?",
        "Had he not been working at the office?",
        "Will he not be working at the office?",
        "Он не работает в офисе.",
        "Він не працює в офісі.",
        "On nie pracuje w biurze."
    ],
    [
        "We are not playing soccer this weekend.",
        "Are we not playing soccer this weekend?",
        "Do we not play soccer this weekend?",
        "Were we not playing soccer this weekend?",
        "Will we not be playing soccer this weekend?",
        "Мы не играем в футбол в эти выходные.",
        "Ми не граємо у футбол цього вихідного.",
        "Nie gramy w piłkę nożną w ten weekend."
    ],
    [
        "I am not listening to music.",
        "Are you not listening to music?",
        "Do you not listen to music?",
        "Had you not been listening to music?",
        "Will you not be listening to music?",
        "Я не слушаю музыку.",
        "Я не слухаю музику.",
        "Nie słucham muzyki."
    ],
    [
        "She is not attending the meeting.",
        "Is she not attending the meeting?",
        "Does she not attend the meeting?",
        "Was she not attending the meeting?",
        "Might she not be attending the meeting?",
        "Она не присутствует на встрече.",
        "Вона не присутня на зустрічі.",
        "Ona nie jest obecna na spotkaniu."
    ],
    [
        "They are not visiting their grandparents.",
        "Are they not visiting their grandparents?",
        "Do they not visit their grandparents?",
        "Had they not been visiting their grandparents?",
        "Will they not be visiting their grandparents?",
        "Они не навещают своих бабушку и дедушку.",
        "Вони не відвідують своїх бабусю і дідуся.",
        "Oni nie odwiedzają swoich dziadków."
    ],
    [
        "He is not cooking dinner.",
        "Is he not cooking dinner?",
        "Does he not cook dinner?",
        "Was he not cooking dinner?",
        "Might he not be cooking dinner?",
        "Он не готовит ужин.",
        "Він не готує вечерю.",
        "On nie gotuje kolacji."
    ],
    [
        "We are not cleaning the house today.",
        "Are we not cleaning the house today?",
        "Do we not clean the house today?",
        "Were we not cleaning the house today?",
        "Will we not be cleaning the house today?",
        "Мы не убираем дом сегодня.",
        "Ми не прибираємо будинок сьогодні.",
        "Nie sprzątamy domu dzisiaj."
    ],
    [
        "I am not reading a newspaper.",
        "Are you not reading a newspaper?",
        "Do you not read a newspaper?",
        "Had you not been reading a newspaper?",
        "Will you not be reading a newspaper?",
        "Я не читаю газету.",
        "Я не читаю газету.",
        "Nie czytam gazety."
    ],
    [
        "You are not driving to work.",
        "Are you not driving to work?",
        "Do you not drive to work?",
        "Had you not been driving to work?",
        "Might you not be driving to work?",
        "Ты не едешь на работу.",
        "Ти не їдеш на роботу.",
        "Nie jedziesz do pracy."
    ],
    [
        "They are not learning English.",
        "Are they not learning English?",
        "Do they not learn English?",
        "Were they not learning English?",
        "Will they not be learning English?",
        "Они не учат английский.",
        "Вони не вивчають англійську.",
        "Oni nie uczą się angielskiego."
    ],
    [
        "He is not watching a movie.",
        "Is he not watching a movie?",
        "Does he not watch a movie?",
        "Was he not watching a movie?",
        "Might he not be watching a movie?",
        "Он не смотрит фильм.",
        "Він не дивиться фільм.",
        "On nie ogląda filmu."
    ],
    [
        "We are not waiting for the bus.",
        "Are we not waiting for the bus?",
        "Do we not wait for the bus?",
        "Had we not been waiting for the bus?",
        "Will we not be waiting for the bus?",
        "Мы не ждем автобус.",
        "Ми не чекаємо на автобус.",
        "Nie czekamy na autobus."
    ],
    [
        "I am not studying history.",
        "Are you not studying history?",
        "Do you not study history?",
        "Had you not been studying history?",
        "Will you not be studying history?",
        "Я не изучаю историю.",
        "Я не вивчаю історію.",
        "Nie studiuję historii."
    ],
    [
        "She is not helping her friend.",
        "Is she not helping her friend?",
        "Does she not help her friend?",
        "Had she not been helping her friend?",
        "Will she not be helping her friend?",
        "Она не помогает своей подруге.",
        "Вона не допомагає своїй подрузі.",
        "Ona nie pomaga swojej przyjaciółce."
    ],
    [
        "They are not playing chess.",
        "Are they not playing chess?",
        "Do they not play chess?",
        "Were they not playing chess?",
        "Will they not be playing chess?",
        "Они не играют в шахматы.",
        "Вони не грають у шахи.",
        "Oni nie grają w szachy."
    ],
    [
        "He is not reading a book.",
        "Is he not reading a book?",
        "Does he not read a book?",
        "Was he not reading a book?",
        "Might he not be reading a book?",
        "Он не читает книгу.",
        "Він не читає книгу.",
        "On nie czyta książki."
    ],
    [
        "We are not going to the park.",
        "Are we not going to the park?",
        "Do we not go to the park?",
        "Had we not been going to the park?",
        "Will we not be going to the park?",
        "Мы не идем в парк.",
        "Ми не йдемо в парк.",
        "Nie idziemy do parku."
    ],
    [
        "I am not cooking dinner.",
        "Are you not cooking dinner?",
        "Do you not cook dinner?",
        "Had you not been cooking dinner?",
        "Will you not be cooking dinner?",
        "Я не готовлю ужин.",
        "Я не готую вечерю.",
        "Nie gotuję kolacji."
    ],
    function (id) {
        //функция подготавливает предложение, которое должно попасть
        //в блок предыдущих ответов, для этого все индексы 0-74
        //конкатенируются нулевой и первый индекс.
        if (id>=0 && id<=59) {
            let str1 = presentSimpleOrContinius[id][0];
            let str2 = presentSimpleOrContinius[id][1];
            str1 = str1.replace('___', str2);
            return str1;
        }
        if (id>=60 && id<=177) {
            let str1 = presentSimpleOrContinius[id][0];
            let str2 = presentSimpleOrContinius[id][1];
            str1 = str1.replace('___', '');
            const pattern = /\(.*?\)/g;
            const result = str1.replace(pattern, str2);
            return result.trim();
        }
        if (id>=178) {
            let str1 = presentSimpleOrContinius[id][0];
            return str1;
        }
    }

];
