const unit23 = [
    ["Are you eating?", "Yes, I am eating.", "Did you eat?", "You eat every day.", "You had eaten.", "Ты ешь?", "Ти їси?", "Czy jesz?"],
    ["She is reading.", "Is she reading?", "She read a book.", "She reads a lot.", "She had read it.", "Она читает.", "Вона читає.", "Ona czyta."],
    ["Are they going?", "Yes, they are going.", "They went home.", "They go often.", "They had gone already.", "Они идут?", "Вони йдуть?", "Czy oni idą?"],
    ["I am writing.", "Am I writing?", "I wrote a letter.", "I write emails.", "I had written before.", "Я пишу.", "Я пишу.", "Piszę."],
    ["Is he watching TV?", "Yes, he is watching TV.", "He watched TV.", "He watches TV.", "He had watched it.", "Он смотрит телевизор?", "Він дивиться телевізор?", "Czy on ogląda telewizję?"],
    ["We are cooking.", "Are we cooking?", "We cooked dinner.", "We cook every day.", "We had cooked before.", "Мы готовим.", "Ми готуємо.", "Gotujemy."],
    ["Are you driving?", "Yes, I am driving.", "Did you drive?", "You drive well.", "You had driven before.", "Ты ведёшь машину?", "Ти ведеш машину?", "Czy prowadzisz samochód?"],
    ["He is playing.", "Is he playing?", "He played yesterday.", "He plays daily.", "He had played before.", "Он играет.", "Він грає.", "On gra."],
    ["Am I speaking?", "Yes, you are speaking.", "I spoke to him.", "I speak clearly.", "I had spoken before.", "Я говорю?", "Я говорю?", "Czy mówię?"],
    ["They are swimming.", "Are they swimming?", "They swam fast.", "They swim well.", "They had swum before.", "Они плавают.", "Вони плавають.", "Oni pływają."],
    ["Is she singing?", "Yes, she is singing.", "She sang beautifully.", "She sings songs.", "She had sung before.", "Она поёт?", "Вона співає?", "Czy ona śpiewa?"],
    ["We are running.", "Are we running?", "We ran fast.", "We run daily.", "We had run before.", "Мы бегаем.", "Ми бігаємо.", "Biegamy."],
    ["Are you reading?", "Yes, I am reading.", "Did you read?", "You read often.", "You had read it.", "Ты читаешь?", "Ти читаєш?", "Czy czytasz?"],
    ["He is listening.", "Is he listening?", "He listened carefully.", "He listens to music.", "He had listened before.", "Он слушает.", "Він слухає.", "On słucha."],
    ["Am I dancing?", "Yes, you are dancing.", "I danced last night.", "I dance often.", "I had danced before.", "Я танцую?", "Я танцюю?", "Czy tańczę?"],
    ["She is painting.", "Is she painting?", "She painted a picture.", "She paints well.", "She had painted before.", "Она рисует.", "Вона малює.", "Ona maluje."],
    ["Are we learning?", "Yes, we are learning.", "We learned quickly.", "We learn daily.", "We had learned it.", "Мы учимся?", "Ми вчимося?", "Czy się uczymy?"],
    ["They are laughing.", "Are they laughing?", "They laughed loudly.", "They laugh a lot.", "They had laughed before.", "Они смеются.", "Вони сміються.", "Oni się śmieją."],
    ["I am sleeping.", "Am I sleeping?", "I slept well.", "I sleep here.", "I had slept before.", "Я сплю.", "Я сплю.", "Śpię."],
    ["Is he working?", "Yes, he is working.", "He worked late.", "He works hard.", "He had worked before.", "Он работает?", "Він працює?", "Czy on pracuje?"],
    ["You are shopping.", "Are you shopping?", "You shopped a lot.", "You shop online.", "You had shopped earlier.", "Ты покупаешь.", "Ти купуєш.", "Robisz zakupy."],
    ["Are they talking?", "Yes, they are talking.", "They talked yesterday.", "They talk a lot.", "They had talked already.", "Они разговаривают?", "Вони розмовляють?", "Czy oni rozmawiają?"],
    ["She is cleaning.", "Is she cleaning?", "She cleaned the room.", "She cleans every day.", "She had cleaned before.", "Она убирает.", "Вона прибирає.", "Ona sprząta."],
    ["We are fixing it.", "Are we fixing it?", "We fixed it.", "We fix things.", "We had fixed it before.", "Мы чинем это.", "Ми це лагодимо.", "Naprawiamy to."],
    ["Is he calling?", "Yes, he is calling.", "He called you.", "He calls often.", "He had called before.", "Он звонит?", "Він телефонує?", "Czy on dzwoni?"],
    ["I am studying.", "Am I studying?", "I studied last night.", "I study often.", "I had studied before.", "Я учусь.", "Я вчуся.", "Uczę się."],
    ["They are building.", "Are they building?", "They built a house.", "They build things.", "They had built it.", "Они строят.", "Вони будують.", "Budują."],
    ["Are we walking?", "Yes, we are walking.", "We walked together.", "We walk daily.", "We had walked far.", "Мы идём пешком?", "Ми йдемо пішки?", "Czy idziemy pieszo?"],
    ["You are helping.", "Are you helping?", "You helped me.", "You help everyone.", "You had helped earlier.", "Ты помогаешь.", "Ти допомагаєш.", "Pomagasz."],
    ["Is she cooking?", "Yes, she is cooking.", "She cooked lunch.", "She cooks well.", "She had cooked before.", "Она готовит?", "Вона готує?", "Czy ona gotuje?"],

];