const irregularVerbsPastSimple = [
    ['...be', 'was/were', 'is', 'are', 'been', 'быть', 'бути', 'być'],
    ['...become', 'became', 'become', 'begun', 'begin', 'становиться', 'ставати', 'stać się'],
    ['...begin', 'began', 'begin', 'begun', 'began', 'начинать', 'починати', 'zacząć'],
    ['...break', 'broke', 'breaked', 'broken', 'breaks', 'ломать', 'ламати', 'łamać'],
    ['...bring', 'brought', 'bringed', 'broughted', 'brung', 'приносить', 'приносити', 'przynosić'],
    ['...build', 'built', 'builded', 'builds', 'build', 'строить', 'будувати', 'budować'],
    ['...buy', 'bought', 'buyed', 'buys', 'boughted', 'покупать', 'купувати', 'kupować'],
    ['...choose', 'chose', 'choosen', 'choose', 'choosed', 'выбирать', 'вибирати', 'wybierać'],
    ['...come', 'came', 'comed', 'comes', 'coming', 'приходить', 'приходити', 'przychodzić'],
    ['...do', 'did', 'done', 'does', 'doing', 'делать', 'робити', 'robić'],
    ['...drink', 'drank', 'drunk', 'drinks', 'drinked', 'пить', 'пити', 'pić'],
    ['...drive', 'drove', 'driven', 'drives', 'drive', 'водить', 'водити', 'prowadzić'],
    ['...eat', 'ate', 'eated', 'eats', 'eaten', 'есть', 'їсти', 'jeść'],
    ['...find', 'found', 'finded', 'finds', 'finding', 'находить', 'знаходити', 'znaleźć'],
    ['...get', 'got', 'getted', 'gets', 'getting', 'получать', 'отримувати', 'dostać'],
    ['...give', 'gave', 'gived', 'gives', 'given', 'давать', 'давати', 'dawać'],
    ['...go', 'went', 'gone', 'goes', 'going', 'идти', 'йти', 'iść'],
    ['...have', 'had', 'haved', 'has', 'having', 'иметь', 'мати', 'mieć'],
    ['...know', 'knew', 'known', 'knows', 'knowed', 'знать', 'знати', 'wiedzieć'],
    ['...leave', 'left', 'leaved', 'leaves', 'lefted', 'покидать', 'залишати', 'zostawić'],
    ['...make', 'made', 'maked', 'makes', 'making', 'делать, создавать', 'робити', 'robić'],
    ['...meet', 'met', 'meet', 'meet', 'meeted', 'встречать', 'зустрічати', 'spotykać'],
    ['...read', 'read (red)', 'readed', 'reads', 'reading', 'читать', 'читати', 'czytać'],
    ['...run', 'ran', 'runned', 'runs', 'running', 'бежать', 'бігти', 'biec'],
    ['...say', 'said', 'sayed', 'says', 'saying', 'говорить', 'казати', 'powiedzieć'],
    ['...see', 'saw', 'seen', 'sees', 'seeing', 'видеть', 'бачити', 'widzieć'],
    ['...sing', 'sang', 'singed', 'sings', 'singing', 'петь', 'співати', 'śpiewać'],
    ['...sit', 'sat', 'sitted', 'sits', 'sitting', 'сидеть', 'сидіти', 'siedzieć'],
    ['...speak', 'spoke', 'spoken', 'speaks', 'speaked', 'говорить', 'говорити', 'mówić'],
    ['...take', 'took', 'taken', 'takes', 'taking', 'брать', 'брати', 'brać'],
    ['...tell', 'told', 'telled', 'tells', 'telling', 'рассказывать', 'розповідати', 'mówić'],
    ['...think', 'thought', 'thinked', 'thinks', 'thinking', 'думать', 'думати', 'myśleć'],
    ['...write', 'wrote', 'written', 'writes', 'writed', 'писать', 'писати', 'pisać'],
];

