const presentPerfectOrPastSimple = [
    ["I have finished my work.", "Have you finished your work?", "Did you finish your work?", "Will you finish your work?", "Are you finishing your work?", "Я закончил свою работу.", "Я закінчив свою роботу.", "Skończyłem swoją pracę."],
    ["She has not seen this movie.", "Has she seen this movie?", "Did she see this movie?", "Will she see this movie?", "Is she seeing this movie?", "Она не видела этот фильм.", "Вона не бачила цей фільм.", "Ona nie widziała tego filmu."],
    ["They have built a new house.", "Have they built a new house?", "Did they build a new house?", "Will they build a new house?", "Are they building a new house?", "Они построили новый дом.", "Вони побудували новий будинок.", "Zbudowali nowy dom."],
    ["He has not called me yet.", "Has he called you yet?", "Did he call you?", "Will he call you?", "Is he calling you?", "Он еще не звонил мне.", "Він ще не дзвонив мені.", "On jeszcze do mnie nie dzwonił."],
    ["We have just arrived.", "Have you just arrived?", "Did you just arrive?", "Will you just arrive?", "Are you just arriving?", "Мы только что приехали.", "Ми щойно приїхали.", "Właśnie przyjechaliśmy."],
    ["The train has already left.", "Has the train already left?", "Did the train already leave?", "Will the train already leave?", "Is the train already leaving?", "Поезд уже ушел.", "Поїзд уже пішов.", "Pociąg już odjechał."],
    ["She has not finished her book.", "Has she finished her book?", "Did she finish her book?", "Will she finish her book?", "Is she finishing her book?", "Она не закончила свою книгу.", "Вона не закінчила свою книгу.", "Ona nie skończyła swojej książki."],
    ["I have traveled to Japan.", "Have you traveled to Japan?", "Did you travel to Japan?", "Will you travel to Japan?", "Are you traveling to Japan?", "Я путешествовал в Японию.", "Я подорожував до Японії.", "Podróżowałem do Japonii."],
    ["They have never met him.", "Have they ever met him?", "Did they ever meet him?", "Will they ever meet him?", "Are they ever meeting him?", "Они никогда не встречали его.", "Вони ніколи не зустрічали його.", "Nigdy go nie spotkali."],
    ["He has studied French.", "Has he studied French?", "Did he study French?", "Will he study French?", "Is he studying French?", "Он изучал французский.", "Він вивчав французьку.", "On uczył się francuskiego."],
    ["We have lost our keys.", "Have you lost your keys?", "Did you lose your keys?", "Will you lose your keys?", "Are you losing your keys?", "Мы потеряли наши ключи.", "Ми загубили наші ключі.", "Zgubiliśmy nasze klucze."],
    ["She has not been to New York.", "Has she been to New York?", "Did she go to New York?", "Will she go to New York?", "Is she going to New York?", "Она не была в Нью-Йорке.", "Вона не була в Нью-Йорку.", "Ona nie była w Nowym Jorku."],
    ["I have read this book.", "Have you read this book?", "Did you read this book?", "Will you read this book?", "Are you reading this book?", "Я прочитал эту книгу.", "Я прочитав цю книгу.", "Przeczytałem tę książkę."],
    ["They have not finished the project.", "Have they finished the project?", "Did they finish the project?", "Will they finish the project?", "Are they finishing the project?", "Они не закончили проект.", "Вони не закінчили проект.", "Nie skończyli projektu."],
    ["He has played the guitar.", "Has he played the guitar?", "Did he play the guitar?", "Will he play the guitar?", "Is he playing the guitar?", "Он играл на гитаре.", "Він грав на гітарі.", "On grał na gitarze."],
    ["She has not visited her grandma.", "Has she visited her grandma?", "Did she visit her grandma?", "Will she visit her grandma?", "Is she visiting her grandma?", "Она не навестила бабушку.", "Вона не відвідала бабусю.", "Ona nie odwiedziła babci."],
    ["I have made dinner.", "Have you made dinner?", "Did you make dinner?", "Will you make dinner?", "Are you making dinner?", "Я приготовил ужин.", "Я приготував вечерю.", "Zrobiłem kolację."],
    ["They have bought a car.", "Have they bought a car?", "Did they buy a car?", "Will they buy a car?", "Are they buying a car?", "Они купили машину.", "Вони купили машину.", "Kupili samochód."],
    ["She has cleaned the house.", "Has she cleaned the house?", "Did she clean the house?", "Will she clean the house?", "Is she cleaning the house?", "Она убрала в доме.", "Вона прибрала в домі.", "Ona posprzątała dom."],
    ["He has not done his homework.", "Has he done his homework?", "Did he do his homework?", "Will he do his homework?", "Is he doing his homework?", "Он не сделал домашнее задание.", "Він не зробив домашнє завдання.", "On nie zrobił pracy domowej."],
    ["We have watched this movie.", "Have you watched this movie?", "Did you watch this movie?", "Will you watch this movie?", "Are you watching this movie?", "Мы смотрели этот фильм.", "Ми дивилися цей фільм.", "Oglądaliśmy ten film."],
    ["She has never been to Italy.", "Has she ever been to Italy?", "Did she ever go to Italy?", "Will she ever go to Italy?", "Is she ever going to Italy?", "Она никогда не была в Италии.", "Вона ніколи не була в Італії.", "Ona nigdy nie była we Włoszech."],
    ["I have written a letter.", "Have you written a letter?", "Did you write a letter?", "Will you write a letter?", "Are you writing a letter?", "Я написал письмо.", "Я написав листа.", "Napisałem list."],
    ["They have not won the game.", "Have they won the game?", "Did they win the game?", "Will they win the game?", "Are they winning the game?", "Они не выиграли игру.", "Вони не виграли гру.", "Nie wygrali gry."],
    ["She has taken a picture.", "Has she taken a picture?", "Did she take a picture?", "Will she take a picture?", "Is she taking a picture?", "Она сделала фото.", "Вона зробила фото.", "Ona zrobiła zdjęcie."],
    ["He has fixed the car.", "Has he fixed the car?", "Did he fix the car?", "Will he fix the car?", "Is he fixing the car?", "Он починил машину.", "Він полагодив машину.", "On naprawił samochód."],
    ["We have met the new teacher.", "Have you met the new teacher?", "Did you meet the new teacher?", "Will you meet the new teacher?", "Are you meeting the new teacher?", "Мы встретили нового учителя.", "Ми зустріли нового вчителя.", "Spotkaliśmy nowego nauczyciela."],
    ["Have you ever visited Paris?", "Yes, I have visited Paris.", "Yes, I visited Paris last year.", "Yes, I am visiting Paris right now.", "Yes, I will visit Paris next summer.", "Вы когда-нибудь бывали в Париже?", "Чи ти коли-небудь відвідував Париж?", "Czy kiedykolwiek odwiedziłeś Paryż?"],
    ["Has she ever been to the zoo?", "Yes, she has been to the zoo.", "Yes, she went to the zoo last weekend.", "Yes, she is at the zoo now.", "Yes, she will go to the zoo tomorrow.", "Она когда-нибудь была в зоопарке?", "Чи вона колись була в зоопарку?", "Czy ona kiedykolwiek była w zoo?"],
    ["Have you finished your homework?", "Yes, I have finished my homework.", "Yes, I finished my homework yesterday.", "Yes, I am finishing my homework right now.", "Yes, I will finish my homework later.", "Ты закончил домашку?", "Ти вже закінчив домашнє завдання?", "Czy skończyłeś pracę domową?"],
    ["Have they seen the new movie?", "Yes, they have seen the new movie.", "Yes, they saw the new movie last week.", "Yes, they are watching the new movie now.", "Yes, they will watch the new movie tomorrow.", "Они видели новый фильм?", "Вони бачили новий фільм?", "Czy oni widzieli nowy film?"],
    ["Have you read this book?", "Yes, I have read this book.", "Yes, I read this book last month.", "Yes, I am reading this book right now.", "Yes, I will read this book next week.", "Ты читал эту книгу?", "Ти читав цю книгу?", "Czy przeczytałeś tę książkę?"],
    ["Has he ever met your parents?", "Yes, he has met my parents.", "Yes, he met my parents last year.", "Yes, he is meeting my parents tomorrow.", "Yes, he will meet my parents next week.", "Он когда-нибудь встречался с твоими родителями?", "Чи він колись зустрічався з твоїми батьками?", "Czy on kiedykolwiek spotkał twoich rodziców?"],
    ["Have we bought the tickets?", "Yes, we have bought the tickets.", "Yes, we bought the tickets yesterday.", "Yes, we are buying the tickets now.", "Yes, we will buy the tickets tomorrow.", "Мы купили билеты?", "Ми купили квитки?", "Czy kupiliśmy bilety?"],
    ["Have they traveled to Japan?", "Yes, they have traveled to Japan.", "Yes, they traveled to Japan last summer.", "Yes, they are traveling to Japan this year.", "Yes, they will travel to Japan next summer.", "Они путешествовали в Японию?", "Вони подорожували до Японії?", "Czy oni podróżowali do Japonii?"],
    ["Have you met her before?", "Yes, I have met her before.", "Yes, I met her last week.", "Yes, I am meeting her tomorrow.", "Yes, I will meet her next month.", "Ты встречал её раньше?", "Ти зустрічав її раніше?", "Czy spotkałeś ją wcześniej?"],
    ["Have you been to the beach?", "Yes, I have been to the beach.", "Yes, I went to the beach last weekend.", "Yes, I am going to the beach tomorrow.", "Yes, I will go to the beach next summer.", "Ты был на пляже?", "Ти був на пляжі?", "Czy byłeś na plaży?"],
    ["Has he learned how to cook?", "Yes, he has learned how to cook.", "Yes, he learned how to cook last year.", "Yes, he is learning how to cook now.", "Yes, he will learn how to cook soon.", "Он научился готовить?", "Він навчився готувати?", "Czy on nauczył się gotować?"],
    ["Have you ever tried sushi?", "Yes, I have tried sushi.", "Yes, I tried sushi last month.", "Yes, I am trying sushi now.", "Yes, I will try sushi next time.", "Ты когда-нибудь пробовал суши?", "Ти коли-небудь пробував суші?", "Czy kiedykolwiek próbowałeś sushi?"],
    ["Has she finished her work?", "Yes, she has finished her work.", "Yes, she finished her work yesterday.", "Yes, she is finishing her work now.", "Yes, she will finish her work later.", "Она закончила свою работу?", "Вона закінчила свою роботу?", "Czy ona skończyła swoją pracę?"],
    ["Have they met the new boss?", "Yes, they have met the new boss.", "Yes, they met the new boss last week.", "Yes, they are meeting the new boss tomorrow.", "Yes, they will meet the new boss next week.", "Они встретили нового босса?", "Вони зустріли нового начальника?", "Czy oni spotkali nowego szefa?"],
    ["Have you seen my phone?", "Yes, I have seen your phone.", "Yes, I saw your phone this morning.", "Yes, I am seeing your phone right now.", "Yes, I will see your phone later.", "Ты видел мой телефон?", "Ти бачив мій телефон?", "Czy widziałeś mój telefon?"],
    ["Has he visited the museum?", "Yes, he has visited the museum.", "Yes, he visited the museum last weekend.", "Yes, he is visiting the museum today.", "Yes, he will visit the museum tomorrow.", "Он посещал музей?", "Він відвідував музей?", "Czy on odwiedził muzeum?"],
    ["Have you tried the new restaurant?", "Yes, I have tried the new restaurant.", "Yes, I tried the new restaurant yesterday.", "Yes, I am trying the new restaurant now.", "Yes, I will try the new restaurant soon.", "Ты пробовал новый ресторан?", "Ти пробував новий ресторан?", "Czy próbowałeś nowej restauracji?"],
    ["Have you watched the new season?", "Yes, I have watched the new season.", "Yes, I watched the new season last week.", "Yes, I am watching the new season now.", "Yes, I will watch the new season soon.", "Ты смотрел новый сезон?", "Ти дивився новий сезон?", "Czy oglądałeś nowy sezon?"],
    ["Has she studied for the test?", "Yes, she has studied for the test.", "Yes, she studied for the test yesterday.", "Yes, she is studying for the test now.", "Yes, she will study for the test tomorrow.", "Она готовилась к тесту?", "Вона готувалася до тесту?", "Czy ona uczyła się do testu?"],
    ["Have you cleaned the house?", "Yes, I have cleaned the house.", "Yes, I cleaned the house this morning.", "Yes, I am cleaning the house now.", "Yes, I will clean the house later.", "Ты убрался в доме?", "Ти прибрався в будинку?", "Czy posprzątałeś dom?"],
    ["Have they bought a new car?", "Yes, they have bought a new car.", "Yes, they bought a new car last month.", "Yes, they are buying a new car now.", "Yes, they will buy a new car soon.", "Они купили новую машину?", "Вони купили нову машину?", "Czy oni kupili nowy samochód?"],
    ["Have you ever been to New York?", "Yes, I have been to New York.", "Yes, I went to New York last year.", "Yes, I am going to New York next month.", "Yes, I will go to New York someday.", "Ты когда-нибудь был в Нью-Йорке?", "Ти колись був у Нью-Йорку?", "Czy kiedykolwiek byłeś w Nowym Jorku?"],
    ["Has he visited Italy?", "Yes, he has visited Italy.", "Yes, he visited Italy last summer.", "Yes, he is visiting Italy next week.", "Yes, he will visit Italy soon.", "Он посещал Италию?", "Він відвідував Італію?", "Czy on odwiedził Włochy?"],
    ["Have you ever eaten at this restaurant?", "Yes, I have eaten at this restaurant.", "Yes, I ate at this restaurant last week.", "Yes, I am eating at this restaurant right now.", "Yes, I will eat at this restaurant next time.", "Ты когда-нибудь ел в этом ресторане?", "Ти коли-небудь їв у цьому ресторані?", "Czy kiedykolwiek jadłeś w tej restauracji?"],
    ["Has he played the piano?", "Yes, he has played the piano.", "Yes, he played the piano yesterday.", "Yes, he is playing the piano now.", "Yes, he will play the piano later.", "Он играл на пианино?", "Він грав на піаніно?", "Czy on grał na pianinie?"],
    ["Have we finished the project?", "Yes, we have finished the project.", "Yes, we finished the project last month.", "Yes, we are finishing the project now.", "Yes, we will finish the project next week.", "Мы завершили проект?", "Ми завершили проект?", "Czy skończyliśmy projekt?"],
    ["Has she visited the doctor?", "Yes, she has visited the doctor.", "Yes, she visited the doctor yesterday.", "Yes, she is visiting the doctor tomorrow.", "Yes, she will visit the doctor next week.", "Она посетила врача?", "Вона відвідала лікаря?", "Czy ona odwiedziła lekarza?"],
    ["Did you visit Paris last year?", "Yes, I visited Paris last year.", "Yes, I have visited Paris.", "Yes, I am visiting Paris now.", "Yes, I will visit Paris next summer.", "Ты посетил Париж в прошлом году?", "Ти відвідував Париж минулого року?", "Czy odwiedziłeś Paryż w zeszłym roku?"],
    ["Did she go to the zoo?", "Yes, she went to the zoo.", "Yes, she has been to the zoo.", "Yes, she is going to the zoo today.", "Yes, she will go to the zoo tomorrow.", "Она ходила в зоопарк?", "Вона ходила в зоопарк?", "Czy ona poszła do zoo?"],
    ["Did you finish your homework?", "Yes, I finished my homework.", "Yes, I have finished my homework.", "Yes, I am finishing my homework now.", "Yes, I will finish my homework later.", "Ты закончил домашку?", "Ти закінчив домашнє завдання?", "Czy skończyłeś pracę domową?"],
    ["Did they watch the new movie?", "Yes, they watched the new movie.", "Yes, they have watched the new movie.", "Yes, they are watching the new movie now.", "Yes, they will watch the new movie next weekend.", "Они смотрели новый фильм?", "Вони дивилися новий фільм?", "Czy oni obejrzeli nowy film?"],
    ["Did you read the book?", "Yes, I read the book.", "Yes, I have read the book.", "Yes, I am reading the book now.", "Yes, I will read the book tomorrow.", "Ты читал книгу?", "Ти читав книгу?", "Czy przeczytałeś książkę?"],
    ["Did he meet your parents?", "Yes, he met my parents.", "Yes, he has met my parents.", "Yes, he is meeting my parents tomorrow.", "Yes, he will meet my parents next week.", "Он встретил твоих родителей?", "Він зустрічався з твоїми батьками?", "Czy on spotkał twoich rodziców?"],
    ["Did we buy the tickets?", "Yes, we bought the tickets.", "Yes, we have bought the tickets.", "Yes, we are buying the tickets now.", "Yes, we will buy the tickets tomorrow.", "Мы купили билеты?", "Ми купили квитки?", "Czy kupiliśmy bilety?"],
    ["Did they travel to Japan?", "Yes, they traveled to Japan.", "Yes, they have traveled to Japan.", "Yes, they are traveling to Japan this year.", "Yes, they will travel to Japan next summer.", "Они путешествовали в Японию?", "Вони подорожували до Японії?", "Czy oni podróżowali do Japonii?"],
    ["Did you meet her before?", "Yes, I met her before.", "Yes, I have met her before.", "Yes, I am meeting her tomorrow.", "Yes, I will meet her next month.", "Ты встречал её раньше?", "Ти зустрічав її раніше?", "Czy spotkałeś ją wcześniej?"],
    ["Did you go to the beach?", "Yes, I went to the beach.", "Yes, I have been to the beach.", "Yes, I am going to the beach tomorrow.", "Yes, I will go to the beach next summer.", "Ты ходил на пляж?", "Ти ходив на пляж?", "Czy poszedłeś na plażę?"],
    ["Did he learn how to cook?", "Yes, he learned how to cook.", "Yes, he has learned how to cook.", "Yes, he is learning how to cook now.", "Yes, he will learn how to cook soon.", "Он научился готовить?", "Він навчився готувати?", "Czy on nauczył się gotować?"],
    ["Did you try sushi?", "Yes, I tried sushi.", "Yes, I have tried sushi.", "Yes, I am trying sushi now.", "Yes, I will try sushi next time.", "Ты пробовал суши?", "Ти пробував суші?", "Czy próbowałeś sushi?"],
    ["Did she finish her work?", "Yes, she finished her work.", "Yes, she has finished her work.", "Yes, she is finishing her work now.", "Yes, she will finish her work later.", "Она закончила свою работу?", "Вона закінчила свою роботу?", "Czy ona skończyła swoją pracę?"],
    ["Did they meet the new boss?", "Yes, they met the new boss.", "Yes, they have met the new boss.", "Yes, they are meeting the new boss tomorrow.", "Yes, they will meet the new boss next week.", "Они встретили нового босса?", "Вони зустріли нового начальника?", "Czy oni spotkali nowego szefa?"],
    ["Did you see my phone?", "Yes, I saw your phone.", "Yes, I have seen your phone.", "Yes, I am seeing your phone now.", "Yes, I will see your phone later.", "Ты видел мой телефон?", "Ти бачив мій телефон?", "Czy widziałeś mój telefon?"],
    ["Did he visit the museum?", "Yes, he visited the museum.", "Yes, he has visited the museum.", "Yes, he is visiting the museum tomorrow.", "Yes, he will visit the museum next week.", "Он посетил музей?", "Він відвідав музей?", "Czy on odwiedził muzeum?"],
    ["Did you try the new restaurant?", "Yes, I tried the new restaurant.", "Yes, I have tried the new restaurant.", "Yes, I am trying the new restaurant now.", "Yes, I will try the new restaurant soon.", "Ты пробовал новый ресторан?", "Ти пробував новий ресторан?", "Czy próbowałeś nowej restauracji?"],
    ["Did you watch the new season?", "Yes, I watched the new season.", "Yes, I have watched the new season.", "Yes, I am watching the new season now.", "Yes, I will watch the new season soon.", "Ты смотрел новый сезон?", "Ти дивився новий сезон?", "Czy oglądałeś nowy sezon?"],
    ["Did she study for the test?", "Yes, she studied for the test.", "Yes, she has studied for the test.", "Yes, she is studying for the test now.", "Yes, she will study for the test tomorrow.", "Она готовилась к тесту?", "Вона готувалася до тесту?", "Czy ona uczyła się do testu?"],
    ["Did you clean the house?", "Yes, I cleaned the house.", "Yes, I have cleaned the house.", "Yes, I am cleaning the house now.", "Yes, I will clean the house later.", "Ты убрался в доме?", "Ти прибрався в будинку?", "Czy posprzątałeś dom?"],
    ["Did they buy a new car?", "Yes, they bought a new car.", "Yes, they have bought a new car.", "Yes, they are buying a new car now.", "Yes, they will buy a new car soon.", "Они купили новую машину?", "Вони купили нову машину?", "Czy oni kupili nowy samochód?"],
    ["Did you ever go to New York?", "Yes, I went to New York.", "Yes, I have been to New York.", "Yes, I am going to New York next month.", "Yes, I will go to New York someday.", "Ты когда-нибудь был в Нью-Йорке?", "Ти коли-небудь був у Нью-Йорку?", "Czy kiedykolwiek byłeś w Nowym Jorku?"],
    ["Did he visit Italy?", "Yes, he visited Italy.", "Yes, he has visited Italy.", "Yes, he is visiting Italy next week.", "Yes, he will visit Italy soon.", "Он посещал Италию?", "Він відвідував Італію?", "Czy on odwiedził Włochy?"],
    ["Did you eat at this restaurant?", "Yes, I ate at this restaurant.", "Yes, I have eaten at this restaurant.", "Yes, I am eating at this restaurant right now.", "Yes, I will eat at this restaurant next time.", "Ты ел в этом ресторане?", "Ти їв у цьому ресторані?", "Czy jadłeś w tej restauracji?"],
    ["Did he play the piano?", "Yes, he played the piano.", "Yes, he has played the piano.", "Yes, he is playing the piano now.", "Yes, he will play the piano later.", "Он играл на пианино?", "Він грав на піаніно?", "Czy on grał na pianinie?"],
    ["Did we finish the project?", "Yes, we finished the project.", "Yes, we have finished the project.", "Yes, we are finishing the project now.", "Yes, we will finish the project next week.", "Мы завершили проект?", "Ми завершили проект?", "Czy skończyliśmy projekt?"],
    ["Did she visit the doctor?", "Yes, she visited the doctor.", "Yes, she has visited the doctor.", "Yes, she is visiting the doctor tomorrow.", "Yes, she will visit the doctor next week.", "Она посетила врача?", "Вона відвідала лікаря?", "Czy ona odwiedziła lekarza?"],
    ["I visited Paris last year.", "Did you visit Paris last year?", "Have you visited Paris?", "Are you visiting Paris now?", "Will you visit Paris next year?", "Я посетил Париж в прошлом году.", "Я відвідав Париж минулого року.", "Odwiedziłem Paryż w zeszłym roku."],
    ["She didn't go to the zoo yesterday.", "Did she go to the zoo yesterday?", "Has she gone to the zoo?", "Is she going to the zoo now?", "Will she go to the zoo tomorrow?", "Она не ходила в зоопарк вчера.", "Вона не ходила в зоопарк вчора.", "Ona nie poszła do zoo wczoraj."],
    ["They watched the movie last night.", "Did they watch the movie last night?", "Have they watched the movie?", "Are they watching the movie now?", "Will they watch the movie next weekend?", "Они смотрели фильм прошлой ночью.", "Вони дивилися фільм минулої ночі.", "Oni oglądali film wczoraj wieczorem."],
    ["I didn't read the book.", "Did you read the book?", "Have you read the book?", "Are you reading the book now?", "Will you read the book next week?", "Я не читал книгу.", "Я не читав книгу.", "Nie przeczytałem książki."],
    ["He played the piano yesterday.", "Did he play the piano yesterday?", "Has he played the piano?", "Is he playing the piano now?", "Will he play the piano tomorrow?", "Он играл на пианино вчера.", "Він грав на піаніно вчора.", "Grał na pianinie wczoraj."],
    ["They didn't eat lunch at noon.", "Did they eat lunch at noon?", "Have they eaten lunch?", "Are they eating lunch now?", "Will they eat lunch later?", "Они не обедали в полдень.", "Вони не обідали в полудень.", "Nie jedli obiadu w południe."],
    ["She went to the market this morning.", "Did she go to the market this morning?", "Has she gone to the market?", "Is she going to the market now?", "Will she go to the market tomorrow?", "Она ходила на рынок сегодня утром.", "Вона ходила на ринок сьогодні вранці.", "Poszła na rynek dzisiaj rano."],
    ["We didn't visit the museum last week.", "Did we visit the museum last week?", "Have we visited the museum?", "Are we visiting the museum now?", "Will we visit the museum next month?", "Мы не посещали музей на прошлой неделе.", "Ми не відвідували музей минулого тижня.", "Nie odwiedziliśmy muzeum w zeszłym tygodniu."],
    ["I studied for the test yesterday.", "Did you study for the test yesterday?", "Have you studied for the test?", "Are you studying for the test now?", "Will you study for the test tomorrow?", "Я учился для теста вчера.", "Я вчився до тесту вчора.", "Uczyłem się do testu wczoraj."],
    ["They didn't clean the house yesterday.", "Did they clean the house yesterday?", "Have they cleaned the house?", "Are they cleaning the house now?", "Will they clean the house tomorrow?", "Они не убирались в доме вчера.", "Вони не прибирали в будинку вчора.", "Nie sprzątali wczoraj w domu."],
    ["She traveled to Japan last year.", "Did she travel to Japan last year?", "Has she traveled to Japan?", "Is she traveling to Japan now?", "Will she travel to Japan next year?", "Она путешествовала в Японию в прошлом году.", "Вона подорожувала до Японії минулого року.", "Podróżowała do Japonii w zeszłym roku."],
    ["We didn't go to the party last night.", "Did we go to the party last night?", "Have we gone to the party?", "Are we going to the party now?", "Will we go to the party tomorrow?", "Мы не ходили на вечеринку прошлой ночью.", "Ми не ходили на вечірку минулої ночі.", "Nie poszliśmy na imprezę wczoraj wieczorem."],
    ["He visited the doctor yesterday.", "Did he visit the doctor yesterday?", "Has he visited the doctor?", "Is he visiting the doctor now?", "Will he visit the doctor tomorrow?", "Он посетил врача вчера.", "Він відвідав лікаря вчора.", "Od visitał lekarza wczoraj."],
    ["I didn't buy a new phone.", "Did you buy a new phone?", "Have you bought a new phone?", "Are you buying a new phone now?", "Will you buy a new phone soon?", "Я не купил новый телефон.", "Я не купив новий телефон.", "Nie kupiłem nowego telefonu."],
    ["They visited the beach last summer.", "Did they visit the beach last summer?", "Have they visited the beach?", "Are they visiting the beach now?", "Will they visit the beach next summer?", "Они посетили пляж прошлым летом.", "Вони відвідували пляж минулого літа.", "Odwiedzili plażę w zeszłym lecie."],
    ["We didn't watch the game on TV.", "Did we watch the game on TV?", "Have we watched the game?", "Are we watching the game now?", "Will we watch the game tomorrow?", "Мы не смотрели игру по телевизору.", "Ми не дивилися гру по телевізору.", "Nie oglądaliśmy meczu w telewizji."],
    ["He didn't take the bus yesterday.", "Did he take the bus yesterday?", "Has he taken the bus?", "Is he taking the bus now?", "Will he take the bus tomorrow?", "Он не ехал на автобусе вчера.", "Він не їхав автобусом вчора.", "Nie jechał autobusem wczoraj."],
    ["I didn't drink coffee this morning.", "Did you drink coffee this morning?", "Have you drunk coffee?", "Are you drinking coffee now?", "Will you drink coffee tomorrow?", "Я не пил кофе сегодня утром.", "Я не пив каву цього ранку.", "Nie piłem kawy dziś rano."],
    ["They didn't finish their homework.", "Did they finish their homework?", "Have they finished their homework?", "Are they finishing their homework now?", "Will they finish their homework tomorrow?", "Они не закончили домашку.", "Вони не закінчили домашнє завдання.", "Nie skończyli pracy domowej."],
    ["She studied abroad last year.", "Did she study abroad last year?", "Has she studied abroad?", "Is she studying abroad now?", "Will she study abroad next year?", "Она училась за границей в прошлом году.", "Вона вчилася за кордоном минулого року.", "Studiowała za granicą w zeszłym roku."],
    ["We didn't walk to the park.", "Did we walk to the park?", "Have we walked to the park?", "Are we walking to the park now?", "Will we walk to the park tomorrow?", "Мы не шли в парк.", "Ми не ходили в парк.", "Nie szliśmy do parku."],
    ["I didn't write an email.", "Did you write an email?", "Have you written an email?", "Are you writing an email now?", "Will you write an email later?", "Я не написал письмо.", "Я не написав листа.", "Nie napisałem e-maila."],
    ["They didn't work yesterday.", "Did they work yesterday?", "Have they worked?", "Are they working now?", "Will they work tomorrow?", "Они не работали вчера.", "Вони не працювали вчора.", "Nie pracowali wczoraj."],
    ["She didn't arrive on time.", "Did she arrive on time?", "Has she arrived on time?", "Is she arriving on time now?", "Will she arrive on time tomorrow?", "Она не приехала вовремя.", "Вона не приїхала вчасно.", "Nie przyjechała na czas."],
    ["I didn't go for a walk.", "Did you go for a walk?", "Have you gone for a walk?", "Are you going for a walk now?", "Will you go for a walk tomorrow?", "Я не гулял.", "Я не гуляв.", "Nie poszedłem na spacer."],
    ["They didn't attend the meeting.", "Did they attend the meeting?", "Have they attended the meeting?", "Are they attending the meeting now?", "Will they attend the meeting tomorrow?", "Они не присутствовали на встрече.", "Вони не були на зустрічі.", "Nie uczestniczyli w spotkaniu."],
    ["We didn't take a vacation last year.", "Did we take a vacation last year?", "Have we taken a vacation?", "Are we taking a vacation now?", "Will we take a vacation next year?", "Мы не брали отпуск в прошлом году.", "Ми не брали відпустку минулого року.", "Nie wzięliśmy urlopu w zeszłym roku."],
    [
      "I have adopted a cute puppy.",
      "Have you adopted a cute puppy?",
      "Did you adopt a cute puppy?",
      "Will you adopt a cute puppy?",
      "Are you adopting a cute puppy?",
      "Я усыновил милого щенка.",
      "Я всиновив милого цуценя.",
      "Zaadoptowałem urocze szczenię."
    ],
    [
      "She has never owned a cat.",
      "Has she ever owned a cat?",
      "Did she own a cat?",
      "Will she own a cat?",
      "Is she owning a cat?",
      "Она никогда не владела кошкой.",
      "Вона ніколи не мала кота.",
      "Ona nigdy nie miała kota."
    ],
    [
      "They have taken their dog to the vet.",
      "Have they taken their dog to the vet?",
      "Did they take their dog to the vet?",
      "Will they take their dog to the vet?",
      "Are they taking their dog to the vet?",
      "Они отвезли свою собаку к ветеринару.",
      "Вони відвезли свою собаку до ветеринара.",
      "Zabrali swojego psa do weterynarza."
    ],
    [
      "He has never fed a parrot before.",
      "Has he ever fed a parrot before?",
      "Did he feed a parrot before?",
      "Will he feed a parrot?",
      "Is he feeding a parrot?",
      "Он никогда раньше не кормил попугая.",
      "Він ніколи раніше не годував папугу.",
      "Nigdy wcześniej nie karmił papugi."
    ],
    [
      "We have rescued a stray kitten.",
      "Have we rescued a stray kitten?",
      "Did we rescue a stray kitten?",
      "Will we rescue a stray kitten?",
      "Are we rescuing a stray kitten?",
      "Мы спасли бездомного котенка.",
      "Ми врятували бездомне кошеня.",
      "Uratowaliśmy bezdomnego kociaka."
    ],
    [
      "She has never ridden a horse.",
      "Has she ever ridden a horse?",
      "Did she ride a horse?",
      "Will she ride a horse?",
      "Is she riding a horse?",
      "Она никогда не ездила на лошади.",
      "Вона ніколи не їздила на коні.",
      "Ona nigdy nie jeździła na koniu."
    ],
    [
      "I have trained my dog to sit.",
      "Have you trained your dog to sit?",
      "Did you train your dog to sit?",
      "Will you train your dog to sit?",
      "Are you training your dog to sit?",
      "Я научил свою собаку сидеть.",
      "Я навчив свого собаку сидіти.",
      "Nauczyłem swojego psa siadać."
    ],
    [
      "They have never seen a wild tiger.",
      "Have they ever seen a wild tiger?",
      "Did they see a wild tiger?",
      "Will they see a wild tiger?",
      "Are they seeing a wild tiger?",
      "Они никогда не видели дикого тигра.",
      "Вони ніколи не бачили дикого тигра.",
      "Nigdy nie widzieli dzikiego tygrysa."
    ],
    [
      "My friend has adopted a rabbit.",
      "Has your friend adopted a rabbit?",
      "Did your friend adopt a rabbit?",
      "Will your friend adopt a rabbit?",
      "Is your friend adopting a rabbit?",
      "Мой друг усыновил кролика.",
      "Мій друг усиновив кролика.",
      "Mój przyjaciel adoptował królika."
    ],
    [
      "We have never touched a snake.",
      "Have we ever touched a snake?",
      "Did we touch a snake?",
      "Will we touch a snake?",
      "Are we touching a snake?",
      "Мы никогда не трогали змею.",
      "Ми ніколи не торкалися змії.",
      "Nigdy nie dotknęliśmy węża."
    ],
    [
      "I have found a wounded bird.",
      "Have you found a wounded bird?",
      "Did you find a wounded bird?",
      "Will you find a wounded bird?",
      "Are you finding a wounded bird?",
      "Я нашел раненую птицу.",
      "Я знайшов пораненого птаха.",
      "Znalazłem rannego ptaka."
    ],
    [
      "She has never played with a hamster.",
      "Has she ever played with a hamster?",
      "Did she play with a hamster?",
      "Will she play with a hamster?",
      "Is she playing with a hamster?",
      "Она никогда не играла с хомяком.",
      "Вона ніколи не гралася з хом'яком.",
      "Ona nigdy nie bawiła się chomikiem."
    ],
    ["The cat ate the food.", 
      "Did the cat eat the food?", 
      "What does the cat eat?", 
      "What is the cat eating?", 
      "What will the cat eat?", 
      "Кошка съела еду.", 
      "Кішка з'їла їжу.", 
      "Kot zjadł jedzenie."],
     
     ["The dog played in the yard.", 
      "Did the dog play in the yard?", 
      "What does the dog play with?", 
      "What is the dog playing with?", 
      "What will the dog play with?", 
      "Собака играла во дворе.", 
      "Собака грала на дворі.", 
      "Pies bawił się na podwórku."],
     
     ["The rabbit jumped over the fence.", 
      "Did the rabbit jump over the fence?", 
      "What does the rabbit jump over?", 
      "What is the rabbit jumping over?", 
      "What will the rabbit jump over?", 
      "Кролик прыгнул через забор.", 
      "Кролик стрибнув через паркан.", 
      "Zając skoczył przez ogrodzenie."],
     
     ["The hamster ran on the wheel.", 
      "Did the hamster run on the wheel?", 
      "Where does the hamster run?", 
      "Where is the hamster running?", 
      "Where will the hamster run?", 
      "Хомяк бегал на колесе.", 
      "Хом'як бігав на колесі.", 
      "Chomik biegał na kole."],
     
     ["The parrot spoke loudly.", 
      "Did the parrot speak loudly?", 
      "What does the parrot speak?", 
      "What is the parrot speaking?", 
      "What will the parrot speak?", 
      "Попугай говорил громко.", 
      "Папуга говорив голосно.", 
      "Papuga mówiła głośno."],
     
     ["The fish swam in the aquarium.", 
      "Did the fish swim in the aquarium?", 
      "Where does the fish swim?", 
      "Where is the fish swimming?", 
      "Where will the fish swim?", 
      "Рыба плавала в аквариуме.", 
      "Риба плавала в акваріумі.", 
      "Ryba pływała w akwarium."],
     
     ["The cat chased the mouse.", 
      "Did the cat chase the mouse?", 
      "What does the cat chase?", 
      "What is the cat chasing?", 
      "What will the cat chase?", 
      "Кошка гонялась за мышью.", 
      "Кошка ганяла мишу.", 
      "Kot gonił mysz."],
     
     ["The dog barked loudly.", 
      "Did the dog bark loudly?", 
      "Why does the dog bark?", 
      "Why is the dog barking?", 
      "Why will the dog bark?", 
      "Собака лаяла громко.", 
      "Собака гавкала голосно.", 
      "Pies szczekał głośno."],
     
     ["The bird flew in the sky.", 
      "Did the bird fly in the sky?", 
      "Where does the bird fly?", 
      "Where is the bird flying?", 
      "Where will the bird fly?", 
      "Птица летела в небе.", 
      "Птах летів у небі.", 
      "Ptak leciał na niebie."],
     
     ["The horse ran across the field.", 
      "Did the horse run across the field?", 
      "Where does the horse run?", 
      "Where is the horse running?", 
      "Where will the horse run?", 
      "Лошадь бегала по полю.", 
      "Кінь бігав по полю.", 
      "Koń biegał po polu."],
     
     ["The cow mooed loudly.", 
      "Did the cow moo loudly?", 
      "Why does the cow moo?", 
      "Why is the cow mooing?", 
      "Why will the cow moo?", 
      "Корова мычала громко.", 
      "Корова мукала голосно.", 
      "Krowa muczała głośno."],
     
     ["The pig wallowed in the mud.", 
      "Did the pig wallow in the mud?", 
      "Why does the pig wallow?", 
      "Why is the pig wallowing?", 
      "Why will the pig wallow?", 
      "Свинья валялась в грязи.", 
      "Свиня валялася в багні.", 
      "Świnia tarzała się w błocie."],
     
     ["The duck swam in the pond.", 
      "Did the duck swim in the pond?", 
      "Where does the duck swim?", 
      "Where is the duck swimming?", 
      "Where will the duck swim?", 
      "Утка плавала в пруду.", 
      "Качка плавала в ставку.", 
      "Kaczka pływała w stawie."],
     
     ["The turtle crawled slowly.", 
      "Did the turtle crawl slowly?", 
      "How does the turtle crawl?", 
      "How is the turtle crawling?", 
      "How will the turtle crawl?", 
      "Черепаха ползла медленно.", 
      "Черепаха повзла повільно.", 
      "Żółw czołgał się powoli."],
     
     ["The kitten slept on the couch.", 
      "Did the kitten sleep on the couch?", 
      "Where does the kitten sleep?", 
      "Where is the kitten sleeping?", 
      "Where will the kitten sleep?", 
      "Котенок спал на диване.", 
      "Котеня спало на дивані.", 
      "Kociak spał na kanapie."],
     
     ["The puppy chewed the toy.", 
      "Did the puppy chew the toy?", 
      "What does the puppy chew?", 
      "What is the puppy chewing?", 
      "What will the puppy chew?", 
      "Щенок жевал игрушку.", 
      "Цуценя жувало іграшку.", 
      "Szczeniak żuł zabawkę."],
     
     ["The lion roared in the jungle.", 
      "Did the lion roar in the jungle?", 
      "Why does the lion roar?", 
      "Why is the lion roaring?", 
      "Why will the lion roar?", 
      "Лев рычал в джунглях.", 
      "Лев ричав у джунглях.", 
      "Lew ryczał w dżungli."],
     
     ["The elephant ate the grass.", 
      "Did the elephant eat the grass?", 
      "What does the elephant eat?", 
      "What is the elephant eating?", 
      "What will the elephant eat?", 
      "Слон ел траву.", 
      "Слон їв траву.", 
      "Słoń jadł trawę."],
     
     ["The monkey climbed the tree.", 
      "Did the monkey climb the tree?", 
      "What does the monkey climb?", 
      "What is the monkey climbing?", 
      "What will the monkey climb?", 
      "Обезьяна лазила по дереву.", 
      "Мавпа лізла по дереву.", 
      "Małpa wspinała się po drzewie."],
     
     ["The zebra ran across the savannah.", 
      "Did the zebra run across the savannah?", 
      "Where does the zebra run?", 
      "Where is the zebra running?", 
      "Where will the zebra run?", 
      "Зебра бегала по саванне.", 
      "Зебра бігала по савані.", 
      "Zebra biegała po sawannie."],
     
     ["The giraffe ate the leaves.", 
      "Did the giraffe eat the leaves?", 
      "What does the giraffe eat?", 
      "What is the giraffe eating?", 
      "What will the giraffe eat?", 
      "Жираф ел листья.", 
      "Жираф їв листя.", 
      "Żyrafa jadła liście."],
     
     ["The horse galloped on the track.", 
      "Did the horse gallop on the track?", 
      "Where does the horse gallop?", 
      "Where is the horse galloping?", 
      "Where will the horse gallop?", 
      "Лошадь галопировала по трассе.", 
      "Кінь галопував по трасі.", 
      "Koń galopował po torze."],
     
     ["The sheep grazed in the field.", 
      "Did the sheep graze in the field?", 
      "What does the sheep graze?", 
      "What is the sheep grazing?", 
      "What will the sheep graze?", 
      "Овца паслась на поле.", 
      "Вівця паслася на полі.", 
      "Owca pasła się na polu."],
     
     ["The camel walked across the desert.", 
      "Did the camel walk across the desert?", 
      "Where does the camel walk?", 
      "Where is the camel walking?", 
      "Where will the camel walk?", 
      "Верблюд шел через пустыню.", 
      "Верблюд йшов через пустелю.", 
      "Wielbłąd szedł przez pustynię."],
     
     ["The owl flew at night.", 
      "Did the owl fly at night?", 
      "Why does the owl fly at night?", 
      "Why is the owl flying at night?", 
      "Why will the owl fly at night?", 
      "Сова летала ночью.", 
      "Сова літала вночі.", 
      "Sowa latała w nocy."],
     
     ["The snake slithered on the ground.", 
      "Did the snake slither on the ground?", 
      "Where does the snake slither?", 
      "Where is the snake slithering?", 
      "Where will the snake slither?", 
      "Змея ползала по земле.", 
      "Змія повзала по землі.", 
      "Wąż pełzał po ziemi."],
     
     ["The frog jumped into the water.", 
      "Did the frog jump into the water?", 
      "What does the frog jump into?", 
      "What is the frog jumping into?", 
      "What will the frog jump into?", 
      "Лягушка прыгнула в воду.", 
      "Жаба стрибнула у воду.", 
      "Żaba skoczyła do wody."],
     
     ["The duck quacked loudly.", 
      "Did the duck quack loudly?", 
      "Why does the duck quack?", 
      "Why is the duck quacking?", 
      "Why will the duck quack?", 
      "Утка крякала громко.", 
      "Качка крякала голосно.", 
      "Kaczka kwacząca głośno."],
     
     ["The squirrel ran up the tree.", 
      "Did the squirrel run up the tree?", 
      "Where does the squirrel run?", 
      "Where is the squirrel running?", 
      "Where will the squirrel run?", 
      "Белка бегала по дереву.", 
      "Білка бігала по дереву.", 
      "Wiewiórka biegała po drzewie."],
     
     ["The cow grazed in the field.", 
      "Did the cow graze in the field?", 
      "What does the cow graze?", 
      "What is the cow grazing?", 
      "What will the cow graze?", 
      "Корова паслась на поле.", 
      "Корова паслася на полі.", 
      "Krowa pasła się na polu."],
     
     ["The tiger hunted in the forest.", 
      "Did the tiger hunt in the forest?", 
      "Where does the tiger hunt?", 
      "Where is the tiger hunting?", 
      "Where will the tiger hunt?", 
      "Тигр охотился в лесу.", 
      "Тигр полював у лісі.", 
      "Tygrys polował w lesie."],
  ];

  
      // Если это свойство есть, то оно попадает в заголовок теста
      presentPerfectOrPastSimple.nameLeson = "Pr. Perfect or Ps. Simple";
      // Свойство показывает сколько индексов содержат правильные предложения
      // Если его нет, то будет считаться, что правильные предложения 
      // только индекс 0 и 1. Если 5 - это индексы 0,1,2,3,4 с правильно
      // созданными предложениями.
      presentPerfectOrPastSimple.lengthTrue = 5;
