export const toBeSentences = [
    ['I ... happy.', "I'm", 'Im', 'Iam', 'I am', 'Я счастлив.', 'Я щасливий.', 'Jestem szczęśliwy.'],
    ['I ... not happy.', "I'm not", 'Im not', 'Iamnot', 'I amnot', 'Я не счастлив.', 'Я не щасливий.', 'Nie jestem szczęśliwy.'],
    ['You ... a student.', "You're", 'Your', 'Youre', 'You ar', 'Ты студент.', 'Ти студент.', 'Jesteś studentem.'],
    ['You ... not a student.', "You aren't", 'Your not', 'You arent', 'You arnt', 'Ты не студент.', 'Ти не студент.', 'Nie jesteś studentem.'],
    ['You ... not a student.', "You're not", 'Your not', 'Youre not', 'You arnt', 'Ты не студент.', 'Ти не студент.', 'Nie jesteś studentem.'],
    ['He ... my friend.', "He's", 'Hes', 'Heis', 'He is', 'Он мой друг.', 'Він мій друг.', 'On jest moim przyjacielem.'],
    ['He ... not my friend.', "He isn't", 'Hes not', 'He isnt', 'He isnot', 'Он не мой друг.', 'Він не мій друг.', 'On nie jest moim przyjacielem.'],
    ['He ... not my friend.', "He's not", 'Hes not', 'He is not', 'Heis not', 'Он не мой друг.', 'Він не мій друг.', 'On nie jest moim przyjacielem.'],
    ['She ... a teacher.', "She's", 'Shes', 'Sheis', 'She is', 'Она учитель.', 'Вона вчитель.', 'Ona jest nauczycielem.'],
    ['She ... not a teacher.', "She isn't", 'Shes not', 'She isnt', 'She isnot', 'Она не учитель.', 'Вона не вчитель.', 'Ona nie jest nauczycielem.'],
    ['She ... not a teacher.', "She's not", 'Shes not', 'She is not', 'Sheis not', 'Она не учитель.', 'Вона не вчитель.', 'Ona nie jest nauczycielem.'],
    ['It ... a cat.', "It's", 'Its', 'Itis', 'It is', 'Это кошка.', 'Це кішка.', 'To jest kot.'],
    ['It ... not a cat.', "It isn't", 'Its not', 'It isnt', 'It isnot', 'Это не кошка.', 'Це не кішка.', 'To nie jest kot.'],
    ['It ... not a cat.', "It's not", 'Its not', 'It is not', 'Itis not', 'Это не кошка.', 'Це не кішка.', 'To nie jest kot.'],
    ['We ... ready.', "We're", 'We are', 'Weare', 'We re', 'Мы готовы.', 'Ми готові.', 'Jesteśmy gotowi.'],
    ['We ... not ready.', "We aren't", 'We are not', 'We arent', 'We arnt', 'Мы не готовы.', 'Ми не готові.', 'Nie jesteśmy gotowi.'],
    ['We ... not ready.', "We're not", 'We are not', 'We re not', 'We arenot', 'Мы не готовы.', 'Ми не готові.', 'Nie jesteśmy gotowi.'],
    ['They ... here.', "They're", 'Theyre', 'They are', 'They re', 'Они здесь.', 'Вони тут.', 'Oni są tutaj.'],
    ['They ... not here.', "They aren't", 'Theyre not', 'They arent', 'They arnt', 'Они не здесь.', 'Вони не тут.', 'Oni nie są tutaj.'],
    ['They ... not here.', "They're not", 'Theyre not', 'They are not', 'They arenot', 'Они не здесь.', 'Вони не тут.', 'Oni nie są tutaj.'],
    ['I ... excited.', "I'm", 'Im', 'Iam', 'I am', 'Я взволнован.', 'Я схвильований.', 'Jestem podekscytowany.'],
    ['I ... not excited.', "I'm not", 'Im not', 'Iamnot', 'I amnot', 'Я не взволнован.', 'Я не схвильований.', 'Nie jestem podekscytowany.'],
    ['You ... my friend.', "You're", 'Your', 'Youre', 'You ar', 'Ты мой друг.', 'Ти мій друг.', 'Jesteś moim przyjacielem.'],
    ['You ... not my friend.', "You aren't", 'Your not', 'You arent', 'You arnt', 'Ты не мой друг.', 'Ти не мій друг.', 'Nie jesteś moim przyjacielem.'],
    ['You ... not my friend.', "You're not", 'Your not', 'Youre not', 'You arnt', 'Ты не мой друг.', 'Ти не мій друг.', 'Nie jesteś moim przyjacielem.'],
    ['He ... a student.', "He's", 'Hes', 'Heis', 'He is', 'Он студент.', 'Він студент.', 'On jest studentem.'],
    ['He ... not a student.', "He isn't", 'Hes not', 'He isnt', 'He isnot', 'Он не студент.', 'Він не студент.', 'On nie jest studentem.'],
    ['He ... not a student.', "He's not", 'Hes not', 'He is not', 'Heis not', 'Он не студент.', 'Він не студент.', 'On nie jest studentem.'],
    ['She ... a friend.', "She's", 'Shes', 'Sheis', 'She is', 'Она подруга.', 'Вона подруга.', 'Ona jest przyjaciółką.'],
    ['She ... not a friend.', "She isn't", 'Shes not', 'She isnt', 'She isnot', 'Она не подруга.', 'Вона не подруга.', 'Ona nie jest przyjaciółką.'],
    ['She ... not a friend.', "She's not", 'Shes not', 'She is not', 'Sheis not', 'Она не подруга.', 'Вона не подруга.', 'Ona nie jest przyjaciółką.'],
    ['It ... sunny.', "It's", 'Its', 'Itis', 'It is', 'Солнечно.', 'Сонячно.', 'Jest słonecznie.'],
    ['It ... not sunny.', "It isn't", 'Its not', 'It isnt', 'It isnot', 'Не солнечно.', 'Не сонячно.', 'Nie jest słonecznie.'],
    ['It ... not sunny.', "It's not", 'Its not', 'It is not', 'Itis not', 'Не солнечно.', 'Не сонячно.', 'Nie jest słonecznie.'],
    ['We ... a team.', "We're", 'We are', 'Weare', 'We re', 'Мы команда.', 'Ми команда.', 'Jesteśmy zespołem.'],
    ['We ... not a team.', "We aren't", 'We are not', 'We arent', 'We arnt', 'Мы не команда.', 'Ми не команда.', 'Nie jesteśmy zespołem.'],
    ['We ... not a team.', "We're not", 'We are not', 'We re not', 'We arenot', 'Мы не команда.', 'Ми не команда.', 'Nie jesteśmy zespołem.'],
    ['They ... friends.', "They're", 'Theyre', 'They are', 'They re', 'Они друзья.', 'Вони друзі.', 'Oni są przyjaciółmi.'],
    ['They ... not friends.', "They aren't", 'Theyre not', 'They arent', 'They arnt', 'Они не друзья.', 'Вони не друзі.', 'Oni nie są przyjaciółmi.'],
    ['They ... not friends.', "They're not", 'Theyre not', 'They are not', 'They arenot', 'Они не друзья.', 'Вони не друзі.', 'Oni nie są przyjaciółmi.'],
    ['I ... tired.', "I'm", 'Im', 'Iam', 'I am', 'Я устал.', 'Я втомився.', 'Jestem zmęczony.'],
    ['I ... not tired.', "I'm not", 'Im not', 'Iamnot', 'I amnot', 'Я не устал.', 'Я не втомився.', 'Nie jestem zmęczony.'],
    ['You ... ready.', "You're", 'Your', 'Youre', 'You ar', 'Ты готов.', 'Ти готовий.', 'Jesteś gotowy.'],
    ['You ... not ready.', "You aren't", 'Your not', 'You arent', 'You arnt', 'Ты не готов.', 'Ти не готовий.', 'Nie jesteś gotowy.'],
    ['You ... not ready.', "You're not", 'Your not', 'Youre not', 'You arnt', 'Ты не готов.', 'Ти не готовий.', 'Nie jesteś gotowy.'],
    ['He ... a good boy.', "He's", 'Hes', 'Heis', 'He is', 'Он хороший мальчик.', 'Він хороший хлопчик.', 'On jest dobrym chłopcem.'],
    ['He ... not a good boy.', "He isn't", 'Hes not', 'He isnt', 'He isnot', 'Он не хороший мальчик.', 'Він не хороший хлопчик.', 'On nie jest dobrym chłopcem.'],
    ['He ... not a good boy.', "He's not", 'Hes not', 'He is not', 'Heis not', 'Он не хороший мальчик.', 'Він не хороший хлопчик.', 'On nie jest dobrym chłopcem.'],
    ['She ... a good girl.', "She's", 'Shes', 'Sheis', 'She is', 'Она хорошая девочка.', 'Вона хороша дівчинка.', 'Ona jest dobrą dziewczynką.'],
    ['She ... not a good girl.', "She isn't", 'Shes not', 'She isnt', 'She isnot', 'Она не хорошая девочка.', 'Вона не хороша дівчинка.', 'Ona nie jest dobrą dziewczynką.'],
    ['She ... not a good girl.', "She's not", 'Shes not', 'She is not', 'Sheis not', 'Она не хорошая девочка.', 'Вона не хороша дівчинка.', 'Ona nie jest dobrą dziewczynką.'],
    ['It ... a sunny day.', "It's", 'Its', 'Itis', 'It is', 'Солнечный день.', 'Сонячний день.', 'To jest słoneczny dzień.'],
    ['It ... not a sunny day.', "It isn't", 'Its not', 'It isnt', 'It isnot', 'Не солнечный день.', 'Не сонячний день.', 'To nie jest słoneczny dzień.'],
    ['It ... not a sunny day.', "It's not", 'Its not', 'It is not', 'Itis not', 'Не солнечный день.', 'Не сонячний день.', 'To nie jest słoneczny dzień.'],
    ['We ... happy.', "We're", 'We are', 'Weare', 'We re', 'Мы счастливы.', 'Ми щасливі.', 'Jesteśmy szczęśliwi.'],
    ['We ... not happy.', "We aren't", 'We are not', 'We arent', 'We arnt', 'Мы не счастливы.', 'Ми не щасливі.', 'Nie jesteśmy szczęśliwi.'],
    ['We ... not happy.', "We're not", 'We are not', 'We re not', 'We arenot', 'Мы не счастливы.', 'Ми не щасливі.', 'Nie jesteśmy szczęśliwi.'],
    ['They ... sad.', "They're", 'Theyre', 'They are', 'They re', 'Они грустные.', 'Вони сумні.', 'Oni są smutni.'],
    ['They ... not sad.', "They aren't", 'Theyre not', 'They arent', 'They arnt', 'Они не грустные.', 'Вони не сумні.', 'Oni nie są smutni.'],
    ['They ... not sad.', "They're not", 'Theyre not', 'They are not', 'They arenot', 'Они не грустные.', 'Вони не сумні.', 'Oni nie są smutni.'],
    ['I ... late.', "I'm", 'Im', 'Iam', 'I am', 'Я опоздал.', 'Я запізнився.', 'Jestem spóźniony.'],
    ['I ... not late.', "I'm not", 'Im not', 'Iamnot', 'I amnot', 'Я не опоздал.', 'Я не запізнився.', 'Nie jestem spóźniony.'],
    ['You ... early.', "You're", 'Your', 'Youre', 'You ar', 'Ты рано.', 'Ти рано.', 'Jesteś wcześnie.'],
    ['You ... not early.', "You aren't", 'Your not', 'You arent', 'You arnt', 'Ты не рано.', 'Ти не рано.', 'Nie jesteś wcześnie.'],
    ['You ... not early.', "You're not", 'Your not', 'Youre not', 'You arnt', 'Ты не рано.', 'Ти не рано.', 'Nie jesteś wcześnie.'],
    ['He ... a doctor.', "He's", 'Hes', 'Heis', 'He is', 'Он доктор.', 'Він лікар.', 'On jest lekarzem.'],
    ['He ... not a doctor.', "He isn't", 'Hes not', 'He isnt', 'He isnot', 'Он не доктор.', 'Він не лікар.', 'On nie jest lekarzem.'],
    ['He ... not a doctor.', "He's not", 'Hes not', 'He is not', 'Heis not', 'Он не доктор.', 'Він не лікар.', 'On nie jest lekarzem.'],
    ['She ... a nurse.', "She's", 'Shes', 'Sheis', 'She is', 'Она медсестра.', 'Вона медсестра.', 'Ona jest pielęgniarką.'],
    ['She ... not a nurse.', "She isn't", 'Shes not', 'She isnt', 'She isnot', 'Она не медсестра.', 'Вона не медсестра.', 'Ona nie jest pielęgniarką.'],
    ['She ... not a nurse.', "She's not", 'Shes not', 'She is not', 'Sheis not', 'Она не медсестра.', 'Вона не медсестра.', 'Ona nie jest pielęgniarką.'],
    ['It ... a book.', "It's", 'Its', 'Itis', 'It is', 'Это книга.', 'Це книга.', 'To jest książka.'],
    ['It ... not a book.', "It isn't", 'Its not', 'It isnt', 'It isnot', 'Это не книга.', 'Це не книга.', 'To nie jest książka.'],
    ['It ... not a book.', "It's not", 'Its not', 'It is not', 'Itis not', 'Это не книга.', 'Це не книга.', 'To nie jest książka.'],
    ['We ... here.', "We're", 'We are', 'Weare', 'We re', 'Мы здесь.', 'Ми тут.', 'Jesteśmy tutaj.'],
    ['We ... not here.', "We aren't", 'We are not', 'We arent', 'We arnt', 'Мы не здесь.', 'Ми не тут.', 'Nie jesteśmy tutaj.'],
    ['We ... not here.', "We're not", 'We are not', 'We re not', 'We arenot', 'Мы не здесь.', 'Ми не тут.', 'Nie jesteśmy tutaj.'],
    ['They ... my friends.', "They're", 'Theyre', 'They are', 'They re', 'Они мои друзья.', 'Вони мої друзі.', 'Oni są moimi przyjaciółmi.'],
    ['They ... not my friends.', "They aren't", 'Theyre not', 'They arent', 'They arnt', 'Они не мои друзья.', 'Вони не мої друзі.', 'Oni nie są moimi przyjaciółmi.'],
    ['They ... not my friends.', "They're not", 'Theyre not', 'They are not', 'They arenot', 'Они не мои друзья.', 'Вони не мої друзі.', 'Oni nie są moimi przyjaciółmi.'],
    ['I ... a teacher.', "I'm", 'Im', 'Iam', 'I am', 'Я учитель.', 'Я вчитель.', 'Jestem nauczycielem.'],
    ['I ... not a teacher.', "I'm not", 'Im not', 'Iamnot', 'I amnot', 'Я не учитель.', 'Я не вчитель.', 'Nie jestem nauczycielem.'],
    ['You ... a parent.', "You're", 'Your', 'Youre', 'You ar', 'Ты родитель.', 'Ти батько.', 'Jesteś rodzicem.'],
    ['You ... not a parent.', "You aren't", 'Your not', 'You arent', 'You arnt', 'Ты не родитель.', 'Ти не батько.', 'Nie jesteś rodzicem.'],
    ['You ... not a parent.', "You're not", 'Your not', 'Youre not', 'You arnt', 'Ты не родитель.', 'Ти не батько.', 'Nie jesteś rodzicem.'],
    ['He ... a pilot.', "He's", 'Hes', 'Heis', 'He is', 'Он пилот.', 'Він пілот.', 'On jest pilotem.'],
    ['He ... not a pilot.', "He isn't", 'Hes not', 'He isnt', 'He isnot', 'Он не пилот.', 'Він не пілот.', 'On nie jest pilotem.'],
    ['He ... not a pilot.', "He's not", 'Hes not', 'He is not', 'Heis not', 'Он не пилот.', 'Він не пілот.', 'On nie jest pilotem.'],
    ['She ... a chef.', "She's", 'Shes', 'Sheis', 'She is', 'Она повар.', 'Вона кухар.', 'Ona jest kucharzem.'],
    ['She ... not a chef.', "She isn't", 'Shes not', 'She isnt', 'She isnot', 'Она не повар.', 'Вона не кухар.', 'Ona nie jest kucharzem.'],
    ['She ... not a chef.', "She's not", 'Shes not', 'She is not', 'Sheis not', 'Она не повар.', 'Вона не кухар.', 'Ona nie jest kucharzem.'],
    ['It ... a pen.', "It's", 'Its', 'Itis', 'It is', 'Это ручка.', 'Це ручка.', 'To jest długopis.'],
    ['It ... not a pen.', "It isn't", 'Its not', 'It isnt', 'It isnot', 'Это не ручка.', 'Це не ручка.', 'To nie jest długopis.'],
    ['It ... not a pen.', "It's not", 'Its not', 'It is not', 'Itis not', 'Это не ручка.', 'Це не ручка.', 'To nie jest długopis.'],
    ['We ... ready to go.', "We're", 'We are', 'Weare', 'We re', 'Мы готовы идти.', 'Ми готові йти.', 'Jesteśmy gotowi do wyjścia.'],
    ['We ... not ready to go.', "We aren't", 'We are not', 'We arent', 'We arnt', 'Мы не готовы идти.', 'Ми не готові йти.', 'Nie jesteśmy gotowi do wyjścia.'],
    ['We ... not ready to go.', "We're not", 'We are not', 'We re not', 'We arenot', 'Мы не готовы идти.', 'Ми не готові йти.', 'Nie jesteśmy gotowi do wyjścia.'],
    ['They ... coming.', "They're", 'Theyre', 'They are', 'They re', 'Они идут.', 'Вони йдуть.', 'Oni idą.'],
    ['They ... not coming.', "They aren't", 'Theyre not', 'They arent', 'They arnt', 'Они не идут.', 'Вони не йдуть.', 'Oni nie idą.'],
    ['They ... not coming.', "They're not", 'Theyre not', 'They are not', 'They arenot', 'Они не идут.', 'Вони не йдуть.', 'Oni nie idą.']
];



    // Если это свойство есть, то оно попадает в заголовок теста
    toBeSentences.nameLeson = "to Be Sentences";
