import { extendForArray } from '../extendForArray.js';
import { extendForArray2 } from '../extendForArray2.js';

const unit35 = [

["Do This before breakfast and your day will change forever.", "Why exactly before breakfast?", "How long is the Great Wall of China?", "What’s your favorite dinosaur?", "Do you like jazz or classical music more?", "Сделай это перед завтраком, и твой день изменится навсегда.", "Зроби це перед сніданком, і твій день зміниться назавжди.", "Zrób to przed śniadaniem, a twój dzień zmieni się na zawsze."],
  ["Do This 10-minute routine to double your focus.", "How does this routine actually work?", "Who painted the Mona Lisa?", "What’s the capital of Mongolia?", "Are you Team iPhone or Team Android?", "Сделай эту 10-минутную рутину, чтобы удвоить концентрацию.", "Зроби цю 10-хвилинну рутину, щоб подвоїти концентрацію.", "Zrób tę 10-minutową rutynę, żeby podwoić koncentrację."],
  ["Do This when you feel stuck and ideas will flow again.", "What should I do exactly when I feel stuck?", "How many bones are in the human body?", "What’s the smell of rain called?", "Do you prefer mountains or ocean?", "Сделай это, когда чувствуешь себя застрявшим, и идеи снова потекут.", "Зроби це, коли відчуваєш, що застряг, і ідеї знову потечуть.", "Zrób to, kiedy czujesz się zablokowany, a pomysły znów popłyną."],
  ["Do This tonight and sleep like a baby.", "What exactly should I do tonight?", "When was the last solar eclipse?", "How fast can a cheetah run?", "Pineapple on pizza — yes or no?", "Сделай это сегодня вечером и спи как младенец.", "Зроби це сьогодні ввечері і спи як немовля.", "Zrób to dzisiaj wieczorem i śpij jak niemowlę."],
  ["Do This every time you open your phone.", "Why every single time I open the phone?", "What is the tallest building in the world right now?", "How many keys on a standard piano?", "Coffee or tea person?", "Делай это каждый раз, когда открываешь телефон.", "Роби це щоразу, коли відкриваєш телефон.", "Rób to za każdym razem, gdy otwierasz telefon."],
  ["Do This for 7 days straight and watch the magic happen.", "What changes should I expect after 7 days?", "Who wrote Romeo and Juliet?", "What color is a mirror?", "Cats or dogs — final answer?", "Сделай это 7 дней подряд и наблюдай за магией.", "Зроби це 7 днів поспіль і спостерігай за магією.", "Zrób to przez 7 dni z rzędu i patrz, jak dzieje się magia."],
  ["Do This instead of scrolling and your life improves fast.", "What should I do instead of scrolling?", "How many oceans are there?", "What’s the opposite of nocturnal?", "Sweet or salty snacks?", "Делай это вместо скроллинга, и жизнь быстро улучшится.", "Роби це замість скролінгу, і життя швидко покращиться.", "Rób to zamiast scrollowania, a życie szybko się poprawi."],
  ["Do This the moment you wake up — game changer.", "Why right after waking up?", "What’s the smallest country in the world?", "How many tastes can the human tongue detect?", "Morning person or night owl?", "Сделай это в момент пробуждения — меняет всё.", "Зроби це в момент пробудження — змінює все.", "Zrób to w momencie przebudzenia — zmienia wszystko."],
  ["Do This before important meetings and you’ll feel unstoppable.", "How does it help before meetings?", "Who discovered penicillin?", "What animal can’t jump?", "Pizza or sushi tonight?", "Сделай это перед важными встречами, и ты будешь неудержим.", "Зроби це перед важливими зустрічами, і ти будеш невпинним.", "Zrób to przed ważnymi spotkaniami, a poczujesz się niepowstrzymany."],
  ["Do This when you’re angry — instant calm.", "What technique calms you down when angry?", "How deep is the Mariana Trench?", "What’s the fastest bird?", "Rain or snow — which do you prefer?", "Сделай это, когда злишься — мгновенное спокойствие.", "Зроби це, коли злишся — миттєве заспокоєння.", "Zrób to, kiedy jesteś zły — natychmiastowy spokój."],
  ["Do This with your next breath and stress disappears.", "How can one breath remove stress?", "Who is the richest person in 2026?", "What fruit is a berry?", "Hot or cold showers?", "Сделай это со следующим вдохом, и стресс исчезнет.", "Зроби це з наступним вдихом, і стрес зникне.", "Zrób to z następnym oddechem, a stres zniknie."],
  ["Do This every Sunday evening and the week starts strong.", "Why specifically Sunday evening?", "How many planets in our solar system?", "What’s the longest word in English?", "Beach or city vacation?", "Делай это каждое воскресенье вечером, и неделя начнётся мощно.", "Роби це щонеділі ввечері, і тиждень почнеться потужно.", "Rób to w każdą niedzielę wieczorem, a tydzień zacznie się mocno."],
  ["Do This before bed and wake up with more energy.", "What should I do before sleeping?", "How many hours does an average person sleep?", "What animal has three hearts?", "Soup or salad first?", "Сделай это перед сном и просыпайся с большей энергией.", "Зроби це перед сном і прокидайся з більшою енергією.", "Zrób to przed snem i budź się z większą energią."],
  ["Do This when nobody is watching — confidence boost.", "Why only when nobody sees?", "What’s the most spoken language in 2026?", "How many ribs does a human have?", "Marvel or DC?", "Сделай это, когда никто не смотрит — прилив уверенности.", "Зроби це, коли ніхто не дивиться — прилив впевненості.", "Zrób to, kiedy nikt nie patrzy — zastrzyk pewności siebie."],
  ["Do This for 30 seconds and anxiety drops.", "How can 30 seconds reduce anxiety?", "Who directed Inception?", "What’s heavier — a ton of bricks or a ton of feathers?", "Coke or Pepsi?", "Сделай это 30 секунд, и тревога спадёт.", "Зроби це 30 секунд, і тривога впаде.", "Zrób to przez 30 sekund, a lęk spadnie."],
  ["Do This every time you feel lazy — motivation hack.", "What’s the fastest way to beat laziness?", "How many time zones in Russia?", "What color is the universe?", "Pancakes or waffles?", "Делай это каждый раз, когда чувствуешь лень — лайфхак мотивации.", "Роби це щоразу, коли відчуваєш лінь — лайфхак мотивації.", "Rób to za każdym razem, gdy czujesz lenistwo — hack motywacyjny."],
  ["Do This and people will start noticing you more.", "How does this make me more noticeable?", "What’s the largest desert?", "How many eyes does a spider usually have?", "Tattoos — yes or no?", "Сделай это, и люди начнут больше тебя замечать.", "Зроби це, і люди почнуть більше тебе помічати.", "Zrób to, a ludzie zaczną cię bardziej zauważać."],
  ["Do This in the morning and your skin thanks you later.", "Why is morning the best time for this?", "How many muscles in the human face?", "What animal laughs?", "Glasses or contacts?", "Сделай это утром, и кожа скажет тебе спасибо позже.", "Зроби це вранці, і шкіра тобі пізніше подякує.", "Zrób to rano, a skóra ci później podziękuje."],
  ["Do This when you’re bored — instant entertainment.", "What’s more fun than being bored?", "Who won the last World Cup?", "How many letters in the Hawaiian alphabet?", "TikTok or YouTube Shorts?", "Сделай это, когда скучно — мгновенное развлечение.", "Зроби це, коли нудно — миттєве розваження.", "Zrób to, kiedy się nudzisz — natychmiastowa rozrywka."],
  ["Do This before every big decision — clarity guaranteed.", "How does it bring clarity?", "What’s the deepest lake?", "How many zeros in a googol?", "Introvert or extrovert?", "Сделай это перед каждым большим решением — ясность гарантирована.", "Зроби це перед кожним великим рішенням — ясність гарантована.", "Zrób to przed każdą dużą decyzją — klarowność gwarantowana."],
  ["Do This daily and your posture fixes itself.", "How long until posture improves?", "What’s the capital of Iceland?", "How many chambers in a human heart?", "Sneakers or boots?", "Делай это ежедневно, и осанка исправится сама.", "Роби це щодня, і постава виправиться сама.", "Rób to codziennie, a postawa sama się poprawi."],
  ["Do This the next time you feel jealous.", "Why should I do something when jealous?", "How many countries in Africa?", "What’s the fastest land animal?", "K-pop or rock?", "Сделай это в следующий раз, когда почувствуешь зависть.", "Зроби це наступного разу, коли відчуєш заздрість.", "Zrób to następnym razem, gdy poczujesz zazdrość."],
  ["Do This and your memory becomes noticeably better.", "How quickly does memory improve?", "Who invented the light bulb?", "What animal never sleeps?", "Paper books or e-books?", "Сделай это, и память заметно улучшится.", "Зроби це, і пам’ять помітно покращиться.", "Zrób to, a pamięć zauważalnie się poprawi."],
  ["Do This for two minutes and mood changes completely.", "What can two minutes really change?", "How many strings on a violin?", "What’s the rarest blood type?", "Summer or winter?", "Сделай это две минуты, и настроение полностью изменится.", "Зроби це дві хвилини, і настрій повністю зміниться.", "Zrób to przez dwie minuty, a nastrój całkowicie się zmieni."],
  ["Do This every time you eat — digestion improves.", "How does it help digestion?", "What’s the longest river?", "How many planets have rings?", "Spicy food or mild?", "Делай это каждый раз, когда ешь — пищеварение улучшается.", "Роби це щоразу, коли їси — травлення покращується.", "Rób to za każdym razem, gdy jesz — trawienie się poprawia."],
  ["Do This while brushing your teeth and health skyrockets.", "Why combine it with brushing?", "How many elements in the periodic table in 2026?", "What’s the national animal of Scotland?", "Mac or Windows?", "Сделай это во время чистки зубов, и здоровье взлетит.", "Зроби це під час чищення зубів, і здоров’я злетить.", "Zrób to podczas mycia zębów, a zdrowie poszybuje w górę."],
  ["Do This on Mondays and the whole week feels easier.", "What makes Monday special for this?", "How many FIFA World Cups so far?", "What gas do plants absorb?", "早起き or 夜更かし?", "Сделай это по понедельникам, и вся неделя покажется легче.", "Зроби це по понеділках, і весь тиждень здаватиметься легшим.", "Zrób to w poniedziałki, a cały tydzień wyda się łatwiejszy."],
  ["Do This after every argument — relationships heal faster.", "How does it help after fights?", "What’s the biggest ocean?", "How many continents touch the equator?", "Hug or handshake?", "Сделай это после каждой ссоры — отношения заживают быстрее.", "Зроби це після кожної сварки — стосунки зцілюються швидше.", "Zrób to po każdej kłótni — relacje szybciej się leczą."],
  ["Do This when traveling and jet lag vanishes.", "Why does it work against jet lag?", "How many hours ahead is Tokyo from New York?", "What’s the currency of Brazil?", "Window or aisle seat?", "Сделай это в путешествиях, и джетлаг исчезнет.", "Зроби це в подорожах, і джетлаг зникне.", "Zrób to w podróży, a jet lag zniknie."],
  ["Do This before workouts and performance doubles.", "How does it boost workout results?", "What muscle is the strongest in the body?", "How many calories in an average banana?", "Gym or home workout?", "Сделай это перед тренировками, и производительность удвоится.", "Зроби це перед тренуваннями, і продуктивність подвоїться.", "Zrób to przed treningiem, a wydajność się podwoi."],
  ["Do This at lunch and afternoon energy stays high.", "Why lunchtime specifically?", "How many liters of water does Earth have?", "What’s the smell of old books called?", "Soup or sandwich for lunch?", "Сделай это за обедом, и энергия после обеда останется высокой.", "Зроби це на обід, і енергія після обіду залишиться високою.", "Zrób to na lunch, a popołudniowa energia pozostanie wysoka."],
  ["Do This when meeting new people — instant charisma.", "What makes someone instantly charismatic?", "How many bones in a newborn baby?", "What animal has blue tongue?", "First impression — handshake or fist bump?", "Сделай это при встрече с новыми людьми — мгновенная харизма.", "Зроби це при знайомстві з новими людьми — миттєва харизма.", "Zrób to przy poznawaniu nowych ludzi — natychmiastowa charyzma."],
  ["Do This during commutes and time flies.", "How can commute become enjoyable?", "What’s the longest train journey possible?", "How many passengers fit on a Boeing 747?", "Podcast or music on the way?", "Сделай это в дороге, и время пролетит незаметно.", "Зроби це під час поїздок, і час пролетить.", "Zrób to w drodze do pracy, a czas poleci."],
  ["Do This before exams and recall improves dramatically.", "Why right before testing?", "How many questions on a standard IQ test?", "What’s the IQ of Albert Einstein estimated?", "Pen or pencil for notes?", "Сделай это перед экзаменами, и вспоминание резко улучшится.", "Зроби це перед іспитами, і згадування різко покращиться.", "Zrób to przed egzaminami, a przypominanie się dramatycznie poprawi."],
  ["Do This after rejection and bounce back faster.", "How to recover quickly from rejection?", "How many times did Edison fail before the bulb?", "What’s the opposite of rejection?", "Cry or laugh it off?", "Сделай это после отказа, и восстановление пройдет быстрее.", "Зроби це після відмови, і відновлення пройде швидше.", "Zrób to po odrzuceniu, a szybciej się pozbierasz."],
  ["Do This every full moon and manifestation accelerates.", "Why tie it to the full moon?", "When is the next full moon after February 2026?", "How many phases does the Moon have?", "Crystals or affirmations?", "Сделай это в каждое полнолуние, и проявление ускорится.", "Зроби це в кожне повноліття, і прояв прискориться.", "Zrób to w każde pełnię księżyca, a manifestacja przyspieszy."],
  ["Do This in the shower and creativity explodes.", "Why does the shower spark ideas?", "How many liters of water per average shower?", "What temperature for the best shower?", "Sing or think in silence?", "Сделай это в душе, и креативность взорвется.", "Зроби це в душі, і креативність вибухне.", "Zrób to pod prysznicem, a kreatywność eksploduje."],
  ["Do This before negotiations and you win more.", "What gives an edge in negotiations?", "How long is the average salary negotiation?", "What animal is best at bargaining?", "Firm handshake or friendly smile?", "Сделай это перед переговорами, и ты будешь выигрывать чаще.", "Зроби це перед переговорами, і ти частіше перемагатимеш.", "Zrób to przed negocjacjami, a wygrasz więcej."],
  ["Do This after victory and next success comes easier.", "Why celebrate in a specific way?", "How many Olympic gold medals does Michael Phelps have?", "What’s the feeling after winning called?", "Party or quiet reflection?", "Сделай это после победы, и следующий успех придёт легче.", "Зроби це після перемоги, і наступний успіх прийде легше.", "Zrób to po zwycięstwie, a kolejny sukces przyjdzie łatwiej."],
  ["Do This when procrastinating and action starts immediately.", "What breaks procrastination fastest?", "How many minutes until the average person gives up?", "What color is associated with urgency?", "Timer or to-do list?", "Сделай это, когда прокрастинируешь, и действие начнётся сразу.", "Зроби це, коли прокрастинуєш, і дія почнеться відразу.", "Zrób to, kiedy odwlekasz, a działanie ruszy od razu."],
  ["Do This with strangers and your social circle grows.", "How many new people per week is ideal?", "What’s the Dunbar number?", "Smile or eye contact first?", "Small talk or deep questions?", "Сделай это с незнакомцами, и круг общения расширится.", "Зроби це з незнайомцями, і коло спілкування розшириться.", "Zrób to z nieznajomymi, a krąg znajomych urośnie."],
  ["Do This before dating apps and matches improve.", "Why prepare before swiping?", "How many dating apps exist in 2026?", "Left or right swipe more often?", "Bio or photos first?", "Сделай это перед приложениями для знакомств, и матчи улучшатся.", "Зроби це перед додатками для знайомств, і матчі покращаться.", "Zrób to przed aplikacjami randkowymi, a mecze się poprawią."],
  ["Do This after compliments and people like you more.", "How to respond to praise best?", "What’s the science behind receiving compliments?", "Blush or say thank you?", "Return compliment or accept silently?", "Сделай это после комплиментов, и люди будут любить тебя сильнее.", "Зроби це після компліментів, і люди любитимуть тебе сильніше.", "Zrób to po komplementach, a ludzie będą cię bardziej lubić."],
  ["Do This during arguments and fights end quicker.", "What de-escalates conflict fastest?", "How long does the average argument last?", "Raise voice or lower it?", "Walk away or stay?", "Сделай это во время споров, и ссоры заканчиваются быстрее.", "Зроби це під час суперечок, і сварки закінчуються швидше.", "Zrób to podczas kłótni, a kłótnie kończą się szybciej."],
  ["Do This before public speaking and nerves disappear.", "What calms stage fright best?", "How many people fear public speaking more than death?", "Power pose or deep breaths?", "Notes or memorize?", "Сделай это перед публичными выступлениями, и нервы исчезнут.", "Зроби це перед публічними виступами, і нерви зникнуть.", "Zrób to przed wystąpieniami publicznymi, a nerwy znikną."],
  ["Do This every paycheck and wealth builds automatically.", "Why right after getting paid?", "How many percent should one save minimum?", "Invest or save first?", "Budget app or spreadsheet?", "Сделай это с каждой зарплатой, и богатство нарастает само.", "Зроби це з кожної зарплати, і багатство нарощується саме.", "Zrób to z każdą wypłatą, a majątek rośnie automatycznie."],
  ["Do This at sunrise and your vibe stays high all day.", "Why sunrise specifically?", "How many minutes after sunrise is best?", "Watch or meditate?", "Coffee at sunrise or later?", "Сделай это на рассвете, и твое настроение будет высоким весь день.", "Зроби це на сході сонця, і твій вайб залишиться високим весь день.", "Zrób to o wschodzie słońca, a twój vibe zostanie wysoki cały dzień."],


];

// Если это свойство есть, то оно попадает в заголовок теста
unit35.nameLeson = "Do This";

//--созданными предложениями.
unit35.lengthTrue = 5;

// console.log(unit33.length);

// расширение числа подмассивов за счёт замены местами нулевого и первого индекса
unit35.push(...extendForArray(unit35));

unit35.push(...extendForArray2(unit35));

export { unit35 };


