export const unit25 = [
[
    "What are you doing tomorrow?",
    "I am going to the park tomorrow.",
    "I go to the park every day.",
    "I went to the park yesterday.",
    "I will go to the park next week.",
    "Что ты делаешь завтра?",
    "Що ти робиш завтра?",
    "Co robisz jutro?"
  ],
  [
    "What are you cooking tomorrow?",
    "I am cooking my favorite dish tomorrow.",
    "I cook my favorite dish every weekend.",
    "I cooked my favorite dish yesterday.",
    "I will cook my favorite dish next month.",
    "Что ты готовишь завтра?",
    "Що ти готуєш завтра?",
    "Co gotujesz jutro?"
  ],
  [
    "Where are you traveling tomorrow?",
    "I am traveling to Paris tomorrow.",
    "I travel to Paris every year.",
    "I travelled to Paris last summer.",
    "I will travel to Paris next year.",
    "Куда ты едешь завтра?",
    "Куди ти їдеш завтра?",
    "Gdzie podróżujesz jutro?"
  ],
  [
    "What are you doing in the gym tomorrow?",
    "I am running in the gym tomorrow.",
    "I run in the gym every morning.",
    "I ran in the gym last week.",
    "I will run in the gym next weekend.",
    "Что ты делаешь в спортзале завтра?",
    "Що ти робиш у спортзалі завтра?",
    "Co robisz na siłowni jutro?"
  ],
  [
    "What are you studying tomorrow?",
    "I am studying math tomorrow.",
    "I study math every evening.",
    "I studied math last semester.",
    "I will study math next term.",
    "Что ты учишь завтра?",
    "Що ти вчиш завтра?",
    "Czego się uczysz jutro?"
  ],
  [
    "What are you writing tomorrow?",
    "I am writing a letter tomorrow.",
    "I write letters every week.",
    "I wrote a letter last month.",
    "I will write a letter next year.",
    "Что ты пишешь завтра?",
    "Що ти пишеш завтра?",
    "Co piszesz jutro?"
  ],
  [
    "Where are you walking tomorrow?",
    "I am walking in the forest tomorrow.",
    "I walk in the forest every Sunday.",
    "I walked in the forest last weekend.",
    "I will walk in the forest next month.",
    "Куда ты идешь гулять завтра?",
    "Куди ти йдеш гуляти завтра?",
    "Gdzie spacerujesz jutro?"
  ],
  [
    "What are you playing tomorrow?",
    "I am playing football tomorrow.",
    "I play football every Saturday.",
    "I played football last week.",
    "I will play football next season.",
    "Во что ты играешь завтра?",
    "У що ти граєш завтра?",
    "W co grasz jutro?"
  ],
  [
    "Who are you seeing tomorrow?",
    "I am seeing my friend tomorrow.",
    "I see my friend every day.",
    "I saw my friend yesterday.",
    "I will see my friend next week.",
    "Кого ты видишь завтра?",
    "Кого ти бачиш завтра?",
    "Kogo widzisz jutro?"
  ],
  [
    "What are you buying tomorrow?",
    "I am buying a new phone tomorrow.",
    "I buy a new phone every year.",
    "I bought a new phone last month.",
    "I will buy a new phone next year.",
    "Что ты покупаешь завтра?",
    "Що ти купуєш завтра?",
    "Co kupujesz jutro?"
  ],
  [
    "What are you reading tomorrow?",
    "I am reading a book tomorrow.",
    "I read books every evening.",
    "I read a book last month.",
    "I will read a book next week.",
    "Что ты читаешь завтра?",
    "Що ти читаєш завтра?",
    "Co czytasz jutro?"
  ],
  [
    "What are you preparing tomorrow?",
    "I am preparing food for the picnic tomorrow.",
    "I prepare food every weekend.",
    "I prepared food last picnic.",
    "I will prepare food next holiday.",
    "Что ты готовишь для пикника завтра?",
    "Що ти готуєш для пікніка завтра?",
    "Co przygotowujesz na piknik jutro?"
  ],
  [
    "Where are you sleeping tomorrow?",
    "I am sleeping at a hotel tomorrow.",
    "I sleep at a hotel every trip.",
    "I slept at a hotel last night.",
    "I will sleep at a hotel next vacation.",
    "Где ты спишь завтра?",
    "Де ти спиш завтра?",
    "Gdzie śpisz jutro?"
  ],
  [
    "What are you planting tomorrow?",
    "I am planting flowers tomorrow.",
    "I plant flowers every spring.",
    "I planted flowers last season.",
    "I will plant flowers next year.",
    "Что ты сажаешь завтра?",
    "Що ти садиш завтра?",
    "Co sadzisz jutro?"
  ],
  [
    "Who are you meeting tomorrow?",
    "I am meeting a friend tomorrow.",
    "I meet friends every weekend.",
    "I met a friend yesterday.",
    "I will meet a friend next month.",
    "Кого ты встречаешь завтра?",
    "Кого ти зустрічаєш завтра?",
    "Kogo spotykasz jutro?"
  ],
  [
    "What are you winning tomorrow?",
    "I am winning a competition tomorrow.",
    "I win competitions every year.",
    "I won a competition last year.",
    "I will win a competition next season.",
    "Что ты выигрываешь завтра?",
    "Що ти виграєш завтра?",
    "Co wygrywasz jutro?"
  ],
  [
    "What are you choosing tomorrow?",
    "I am choosing apples tomorrow.",
    "I choose apples every market day.",
    "I chose apples last week.",
    "I will choose apples next month.",
    "Что ты выбираешь завтра?",
    "Що ти вибираєш завтра?",
    "Co wybierasz jutro?"
  ],
  [
    "What are you bringing tomorrow?",
    "I am bringing gifts for the party tomorrow.",
    "I bring gifts every party.",
    "I brought gifts last party.",
    "I will bring gifts next celebration.",
    "Что ты приносишь на вечеринку завтра?",
    "Що ти приносиш на вечірку завтра?",
    "Co przynosisz na imprezę jutro?"
  ],
  [
    "Where are you swimming tomorrow?",
    "I am swimming in the sea tomorrow.",
    "I swim in the sea every summer.",
    "I swam in the sea last holiday.",
    "I will swim in the sea next vacation.",
    "Где ты плаваешь завтра?",
    "Де ти плаваєш завтра?",
    "Gdzie pływasz jutro?"
  ],
  [
    "What are you learning tomorrow?",
    "I am learning new words tomorrow.",
    "I learn new words every day.",
    "I learned new words last week.",
    "I will learn new words next month.",
    "Что ты учишь завтра?",
    "Що ти вчиш завтра?",
    "Czego się uczysz jutro?"
  ],
  [
    "What are you hearing tomorrow?",
    "I am hearing a song at the concert tomorrow.",
    "I hear songs every concert.",
    "I heard a song last concert.",
    "I will hear a song next event.",
    "Что ты слышишь на концерте завтра?",
    "Що ти чуєш на концерті завтра?",
    "Co słyszysz na koncercie jutro?"
  ],
  [
    "What are you seeing in the museum tomorrow?",
    "I am seeing old paintings in the museum tomorrow.",
    "I see old paintings every visit.",
    "I saw old paintings last visit.",
    "I will see old paintings next tour.",
    "Что ты видишь в музее завтра?",
    "Що ти бачиш у музеї завтра?",
    "Co widzisz w muzeum jutro?"
  ],
  [
    "What are you watching tomorrow evening?",
    "I am watching a movie tomorrow evening.",
    "I watch movies every evening.",
    "I watched a movie last evening.",
    "I will watch a movie next weekend.",
    "Что ты смотришь завтра вечером?",
    "Що ти дивишся завтра ввечері?",
    "Co oglądasz jutro wieczorem?"
  ],
  [
    "What are you preparing for the meeting tomorrow?",
    "I am preparing a report for the meeting tomorrow.",
    "I prepare reports every week.",
    "I prepared a report last meeting.",
    "I will prepare a report next project.",
    "Что ты готовишь для встречи завтра?",
    "Що ти готуєш для зустрічі завтра?",
    "Co przygotowujesz na spotkanie jutro?"
  ],
  [
    "Where are you driving tomorrow?",
    "I am driving to the mountains tomorrow.",
    "I drive to the mountains every holiday.",
    "I drove to the mountains last weekend.",
    "I will drive to the mountains next trip.",
    "Куда ты едешь на машине завтра?",
    "Куди ти їдеш на машині завтра?",
    "Gdzie jedziesz samochodem jutro?"
  ],
  [
    "What are you reading in the library tomorrow?",
    "I am reading a novel in the library tomorrow.",
    "I read novels every week.",
    "I read a novel last month.",
    "I will read a novel next semester.",
    "Что ты читаешь в библиотеке завтра?",
    "Що ти читаєш у бібліотеці завтра?",
    "Co czytasz w bibliotece jutro?"
  ],
  [
    "What are you building tomorrow?",
    "I am building a sandcastle tomorrow.",
    "I build sandcastles every summer.",
    "I built a sandcastle last holiday.",
    "I will build a sandcastle next vacation.",
    "Что ты строишь завтра?",
    "Що ти будуєш завтра?",
    "Co budujesz jutro?"
  ],
  [
    "What are you running tomorrow?",
    "I am running in the marathon tomorrow.",
    "I run in marathons every year.",
    "I ran in a marathon last year.",
    "I will run in a marathon next season.",
    "В чем ты бегаешь завтра?",
    "У чому ти бігаєш завтра?",
    "W czym biegniesz jutro?"
  ],
  [
    "Who are you meeting at the store tomorrow?",
    "I am meeting my cousin at the store tomorrow.",
    "I meet my cousin every week.",
    "I met my cousin last week.",
    "I will meet my cousin next month.",
    "Кого ты встречаешь в магазине завтра?",
    "Кого ти зустрічаєш у магазині завтра?",
    "Kogo spotykasz w sklepie jutro?"
  ],
  [
    "What are you planning for the holiday tomorrow?",
    "I am planning a family trip tomorrow.",
    "I plan family trips every year.",
    "I planned a family trip last holiday.",
    "I will plan a family trip next year.",
    "Что ты планируешь на праздник завтра?",
    "Що ти плануєш на свято завтра?",
    "Co planujesz na święto jutro?"
  ],
  [
    "What are you eating tomorrow?",
    "I am eating pizza tomorrow.",
    "I eat pizza every weekend.",
    "I ate pizza yesterday.",
    "I will eat pizza next week.",
    "Что ты ешь завтра?",
    "Що ти їси завтра?",
    "Co jesz jutro?"
  ],
  [
    "What are you drinking tomorrow?",
    "I am drinking juice tomorrow.",
    "I drink juice every morning.",
    "I drank juice yesterday.",
    "I will drink juice next week.",
    "Что ты пьешь завтра?",
    "Що ти п’єш завтра?",
    "Co pijesz jutro?"
  ],
  [
    "Where are you hiking tomorrow?",
    "I am hiking in the mountains tomorrow.",
    "I hike in the mountains every summer.",
    "I hiked in the mountains last month.",
    "I will hike in the mountains next year.",
    "Куда ты идешь в поход завтра?",
    "Куди ти йдеш у похід завтра?",
    "Gdzie wędrujesz jutro?"
  ],
  [
    "What are you painting tomorrow?",
    "I am painting a picture tomorrow.",
    "I paint pictures every weekend.",
    "I painted a picture last week.",
    "I will paint a picture next month.",
    "Что ты рисуешь завтра?",
    "Що ти малюєш завтра?",
    "Co malujesz jutro?"
  ],
  [
    "What are you singing tomorrow?",
    "I am singing a song tomorrow.",
    "I sing songs every evening.",
    "I sang a song last concert.",
    "I will sing a song next event.",
    "Что ты поешь завтра?",
    "Що ти співаєш завтра?",
    "Co śpiewasz jutro?"
  ],
  [
    "What are you watching on TV tomorrow?",
    "I am watching a documentary on TV tomorrow.",
    "I watch documentaries every week.",
    "I watched a documentary last night.",
    "I will watch a documentary next weekend.",
    "Что ты смотришь по телевизору завтра?",
    "Що ти дивишся по телевізору завтра?",
    "Co oglądasz w telewizji jutro?"
  ],
  [
    "Where are you flying tomorrow?",
    "I am flying to London tomorrow.",
    "I fly to London every year.",
    "I flew to London last year.",
    "I will fly to London next summer.",
    "Куда ты летишь завтра?",
    "Куди ти летиш завтра?",
    "Gdzie lecisz jutro?"
  ],
  [
    "What are you choosing for dinner tomorrow?",
    "I am choosing a salad for dinner tomorrow.",
    "I choose salads every day.",
    "I chose a salad last dinner.",
    "I will choose a salad next week.",
    "Что ты выбираешь на ужин завтра?",
    "Що ти вибираєш на вечерю завтра?",
    "Co wybierasz na obiad jutro?"
  ],
  [
    "What are you visiting tomorrow?",
    "I am visiting a castle tomorrow.",
    "I visit castles every vacation.",
    "I visited a castle last weekend.",
    "I will visit a castle next holiday.",
    "Что ты посещаешь завтра?",
    "Що ти відвідуєш завтра?",
    "Co odwiedzasz jutro?"
  ],
  [
    "What are you drawing tomorrow?",
    "I am drawing a picture tomorrow.",
    "I draw pictures every week.",
    "I drew a picture last class.",
    "I will draw a picture next month.",
    "Что ты рисуешь завтра?",
    "Що ти малюєш завтра?",
    "Co rysujesz jutro?"
  ],
  [
    "What are you buying at the mall tomorrow?",
    "I am buying a dress tomorrow.",
    "I buy dresses every month.",
    "I bought a dress last week.",
    "I will buy a dress next season.",
    "Что ты покупаешь в торговом центре завтра?",
    "Що ти купуєш у торговому центрі завтра?",
    "Co kupujesz w centrum handlowym jutro?"
  ],
  [
    "What are you eating at the party tomorrow?",
    "I am eating cake at the party tomorrow.",
    "I eat cake every party.",
    "I ate cake last party.",
    "I will eat cake next celebration.",
    "Что ты ешь на вечеринке завтра?",
    "Що ти їси на вечірці завтра?",
    "Co jesz na imprezie jutro?"
  ],
  [
    "Where are you riding tomorrow?",
    "I am riding a bike tomorrow.",
    "I ride a bike every weekend.",
    "I rode a bike last summer.",
    "I will ride a bike next month.",
    "Где ты катаешься завтра?",
    "Де ти катаєшся завтра?",
    "Gdzie jeździsz jutro?"
  ],
  [
    "What are you studying for the test tomorrow?",
    "I am studying history for the test tomorrow.",
    "I study history every semester.",
    "I studied history last test.",
    "I will study history next exam.",
    "Что ты учишь для теста завтра?",
    "Що ти вчиш для тесту завтра?",
    "Czego się uczysz na test jutro?"
  ],
  [
    "What are you drinking at the cafe tomorrow?",
    "I am drinking coffee at the cafe tomorrow.",
    "I drink coffee every morning.",
    "I drank coffee yesterday.",
    "I will drink coffee next week.",
    "Что ты пьешь в кафе завтра?",
    "Що ти п’єш у кафе завтра?",
    "Co pijesz w kawiarni jutro?"
  ],
  [
    "What are you making for the family tomorrow?",
    "I am making a cake for the family tomorrow.",
    "I make cakes every holiday.",
    "I made a cake last holiday.",
    "I will make a cake next celebration.",
    "Что ты делаешь для семьи завтра?",
    "Що ти робиш для сім’ї завтра?",
    "Co robisz dla rodziny jutro?"
  ],
  [
    "Where are you camping tomorrow?",
    "I am camping in the forest tomorrow.",
    "I camp in the forest every summer.",
    "I camped in the forest last holiday.",
    "I will camp in the forest next vacation.",
    "Где ты разбиваешь лагерь завтра?",
    "Де ти розбиваєш табір завтра?",
    "Gdzie rozbijasz obóz jutro?"
  ],
  [
    "What are you fixing tomorrow?",
    "I am fixing the door tomorrow.",
    "I fix doors every month.",
    "I fixed the door last week.",
    "I will fix the door next year.",
    "Что ты чинишь завтра?",
    "Що ти лагодиш завтра?",
    "Co naprawiasz jutro?"
  ],
  [
    "What are you cleaning tomorrow?",
    "I am cleaning the room tomorrow.",
    "I clean the room every weekend.",
    "I cleaned the room yesterday.",
    "I will clean the room next week.",
    "Что ты убираешь завтра?",
    "Що ти прибираєш завтра?",
    "Co sprzątasz jutro?"
  ],
  [
    "I am going to the beach tomorrow.",
    "What are you doing tomorrow?",
    "What do you do every day?",
    "What did you do yesterday?",
    "What will you do next week?",
    "Я иду на пляж завтра.",
    "Я йду на пляж завтра.",
    "Idę na plażę jutro."
  ],
  [
    "I am cooking pasta tomorrow.",
    "What are you cooking tomorrow?",
    "What do you cook every week?",
    "What did you cook yesterday?",
    "What will you cook next weekend?",
    "Я готовлю пасту завтра.",
    "Я готую пасту завтра.",
    "Gotuję makaron jutro."
  ],
  [
    "I am traveling to Rome tomorrow.",
    "Where are you traveling tomorrow?",
    "Where do you travel every year?",
    "Where did you travel last summer?",
    "Where will you travel next year?",
    "Я еду в Рим завтра.",
    "Я їду до Риму завтра.",
    "Podróżuję do Rzymu jutro."
  ],
  [
    "I am running in the park tomorrow.",
    "What are you doing in the park tomorrow?",
    "What do you do in the park every morning?",
    "What did you do in the park last week?",
    "What will you do in the park next weekend?",
    "Я бегаю в парке завтра.",
    "Я бігаю в парку завтра.",
    "Biegam w parku jutro."
  ],
  [
    "I am studying history tomorrow.",
    "What are you studying tomorrow?",
    "What do you study every evening?",
    "What did you study last semester?",
    "What will you study next term?",
    "Я изучаю историю завтра.",
    "Я вивчаю історію завтра.",
    "Uczę się historii jutro."
  ],
  [
    "I am writing an email tomorrow.",
    "What are you writing tomorrow?",
    "What do you write every week?",
    "What did you write last month?",
    "What will you write next year?",
    "Я пишу электронное письмо завтра.",
    "Я пишу електронний лист завтра.",
    "Piszę e-mail jutro."
  ],
  [
    "I am walking by the river tomorrow.",
    "Where are you walking tomorrow?",
    "Where do you walk every Sunday?",
    "Where did you walk last weekend?",
    "Where will you walk next month?",
    "Я гуляю у реки завтра.",
    "Я гуляю біля річки завтра.",
    "Spaceruję nad rzeką jutro."
  ],
  [
    "I am playing basketball tomorrow.",
    "What are you playing tomorrow?",
    "What do you play every Saturday?",
    "What did you play last week?",
    "What will you play next season?",
    "Я играю в баскетбол завтра.",
    "Я граю в баскетбол завтра.",
    "Gram w koszykówkę jutro."
  ],
  [
    "I am seeing my cousin tomorrow.",
    "Who are you seeing tomorrow?",
    "Who do you see every day?",
    "Who did you see yesterday?",
    "Who will you see next week?",
    "Я вижу своего кузена завтра.",
    "Я бачу свого кузена завтра.",
    "Spotykam mojego kuzyna jutro."
  ],
  [
    "I am buying a book tomorrow.",
    "What are you buying tomorrow?",
    "What do you buy every month?",
    "What did you buy last week?",
    "What will you buy next year?",
    "Я покупаю книгу завтра.",
    "Я купую книгу завтра.",
    "Kupuję książkę jutro."
  ],
  [
    "I am reading a magazine tomorrow.",
    "What are you reading tomorrow?",
    "What do you read every evening?",
    "What did you read last month?",
    "What will you read next week?",
    "Я читаю журнал завтра.",
    "Я читаю журнал завтра.",
    "Czytam magazyn jutro."
  ],
  [
    "I am preparing snacks for the party tomorrow.",
    "What are you preparing tomorrow?",
    "What do you prepare every party?",
    "What did you prepare last picnic?",
    "What will you prepare next holiday?",
    "Я готовлю закуски для вечеринки завтра.",
    "Я готую закуски для вечірки завтра.",
    "Przygotowuję przekąski na imprezę jutro."
  ],
  [
    "I am sleeping at a friend’s house tomorrow.",
    "Where are you sleeping tomorrow?",
    "Where do you sleep every night?",
    "Where did you sleep last night?",
    "Where will you sleep next vacation?",
    "Я сплю у друга дома завтра.",
    "Я сплю в друга вдома завтра.",
    "Śpię u przyjaciela jutro."
  ],
  [
    "I am planting trees tomorrow.",
    "What are you planting tomorrow?",
    "What do you plant every spring?",
    "What did you plant last season?",
    "What will you plant next year?",
    "Я сажаю деревья завтра.",
    "Я саджу дерева завтра.",
    "Ssadzę drzewa jutro."
  ],
  [
    "I am meeting my teacher tomorrow.",
    "Who are you meeting tomorrow?",
    "Who do you meet every week?",
    "Who did you meet yesterday?",
    "Who will you meet next month?",
    "Я встречаюсь с учителем завтра.",
    "Я зустрічаюся з учителем завтра.",
    "Spotykam się z nauczycielem jutro."
  ],
  [
    "I am winning a race tomorrow.",
    "What are you winning tomorrow?",
    "What do you win every competition?",
    "What did you win last year?",
    "What will you win next season?",
    "Я выигрываю гонку завтра.",
    "Я виграю гонку завтра.",
    "Wygrywam wyścig jutro."
  ],
  [
    "I am choosing a gift tomorrow.",
    "What are you choosing tomorrow?",
    "What do you choose every holiday?",
    "What did you choose last birthday?",
    "What will you choose next celebration?",
    "Я выбираю подарок завтра.",
    "Я вибираю подарунок завтра.",
    "Wybieram prezent jutro."
  ],
  [
    "I am bringing drinks for the party tomorrow.",
    "What are you bringing tomorrow?",
    "What do you bring every party?",
    "What did you bring last party?",
    "What will you bring next celebration?",
    "Я приношу напитки на вечеринку завтра.",
    "Я приношу напої на вечірку завтра.",
    "Przynoszę napoje na imprezę jutro."
  ],
  [
    "I am swimming in the lake tomorrow.",
    "Where are you swimming tomorrow?",
    "Where do you swim every summer?",
    "Where did you swim last holiday?",
    "Where will you swim next vacation?",
    "Я плаваю в озере завтра.",
    "Я плаваю в озері завтра.",
    "Pływam w jeziorze jutro."
  ],
  [
    "I am learning Spanish tomorrow.",
    "What are you learning tomorrow?",
    "What do you learn every day?",
    "What did you learn last week?",
    "What will you learn next month?",
    "Я изучаю испанский завтра.",
    "Я вивчаю іспанську завтра.",
    "Uczę się hiszpańskiego jutro."
  ],
  [
    "I am hearing a band at the festival tomorrow.",
    "What are you hearing tomorrow?",
    "What do you hear every concert?",
    "What did you hear last festival?",
    "What will you hear next event?",
    "Я слушаю группу на фестивале завтра.",
    "Я слухаю групу на фестивалі завтра.",
    "Słucham zespołu na festiwalu jutro."
  ],
  [
    "I am seeing sculptures in the gallery tomorrow.",
    "What are you seeing in the gallery tomorrow?",
    "What do you see in the gallery every visit?",
    "What did you see in the gallery last tour?",
    "What will you see in the gallery next month?",
    "Я смотрю скульптуры в галерее завтра.",
    "Я дивлюся на скульптури в галереї завтра.",
    "Oglądam rzeźby w galerii jutro."
  ],
  [
    "I am watching a comedy tomorrow evening.",
    "What are you watching tomorrow evening?",
    "What do you watch every evening?",
    "What did you watch last evening?",
    "What will you watch next weekend?",
    "Я смотрю комедию завтра вечером.",
    "Я дивлюся комедію завтра ввечері.",
    "Oglądam komedię jutro wieczorem."
  ],
  [
    "I am preparing a presentation for the meeting tomorrow.",
    "What are you preparing for the meeting tomorrow?",
    "What do you prepare every meeting?",
    "What did you prepare last meeting?",
    "What will you prepare next project?",
    "Я готовлю презентацию для встречи завтра.",
    "Я готую презентацію для зустрічі завтра.",
    "Przygotowuję prezentację na spotkanie jutro."
  ],
  [
    "I am driving to the countryside tomorrow.",
    "Where are you driving tomorrow?",
    "Where do you drive every holiday?",
    "Where did you drive last weekend?",
    "Where will you drive next trip?",
    "Я еду за город завтра.",
    "Я їду за місто завтра.",
    "Jadę na wieś jutro."
  ],
  [
    "I am reading a novel in the cafe tomorrow.",
    "What are you reading in the cafe tomorrow?",
    "What do you read in the cafe every week?",
    "What did you read in the cafe last month?",
    "What will you read in the cafe next week?",
    "Я читаю роман в кафе завтра.",
    "Я читаю роман у кафе завтра.",
    "Czytam powieść w kawiarni jutro."
  ],
  [
    "I am building a model tomorrow.",
    "What are you building tomorrow?",
    "What do you build every hobby session?",
    "What did you build last holiday?",
    "What will you build next project?",
    "Я строю модель завтра.",
    "Я будую модель завтра.",
    "Buduję model jutro."
  ],
  [
    "I am running in a race tomorrow.",
    "What are you running tomorrow?",
    "What do you run every competition?",
    "What did you run last race?",
    "What will you run next season?",
    "Я бегаю в гонке завтра.",
    "Я бігаю в гонці завтра.",
    "Biegam w wyścigu jutro."
  ],
  [
    "I am meeting my sister at the mall tomorrow.",
    "Who are you meeting at the mall tomorrow?",
    "Who do you meet at the mall every week?",
    "Who did you meet at the mall last week?",
    "Who will you meet at the mall next month?",
    "Я встречаюсь с сестрой в торговом центре завтра.",
    "Я зустрічаюся з сестрою в торговому центрі завтра.",
    "Spotykam się z siostrą w centrum handlowym jutro."
  ],
  [
    "I am planning a picnic tomorrow.",
    "What are you planning tomorrow?",
    "What do you plan every holiday?",
    "What did you plan last holiday?",
    "What will you plan next year?",
    "Я планирую пикник завтра.",
    "Я планую пікнік завтра.",
    "Planuję piknik jutro."
  ],
  [
    "I am eating sushi tomorrow.",
    "What are you eating tomorrow?",
    "What do you eat every weekend?",
    "What did you eat yesterday?",
    "What will you eat next week?",
    "Я ем суши завтра.",
    "Я їм суші завтра.",
    "Jem sushi jutro."
  ],
  [
    "I am drinking tea tomorrow.",
    "What are you drinking tomorrow?",
    "What do you drink every morning?",
    "What did you drink yesterday?",
    "What will you drink next week?",
    "Я пью чай завтра.",
    "Я п’ю чай завтра.",
    "Piję herbatę jutro."
  ],
  [
    "I am hiking in the forest tomorrow.",
    "Where are you hiking tomorrow?",
    "Where do you hike every summer?",
    "Where did you hike last month?",
    "Where will you hike next year?",
    "Я иду в поход в лес завтра.",
    "Я йду в похід у ліс завтра.",
    "Wędruję po lesie jutro."
  ],
  [
    "I am painting a portrait tomorrow.",
    "What are you painting tomorrow?",
    "What do you paint every weekend?",
    "What did you paint last week?",
    "What will you paint next month?",
    "Я рисую портрет завтра.",
    "Я малюю портрет завтра.",
    "Maluję portret jutro."
  ],
  [
    "I am singing at a karaoke tomorrow.",
    "What are you singing tomorrow?",
    "What do you sing every event?",
    "What did you sing last concert?",
    "What will you sing next show?",
    "Я пою на караоке завтра.",
    "Я співаю на караоке завтра.",
    "Śpiewam na karaoke jutro."
  ],
  [
    "I am watching a series on TV tomorrow.",
    "What are you watching on TV tomorrow?",
    "What do you watch on TV every evening?",
    "What did you watch on TV last night?",
    "What will you watch on TV next weekend?",
    "Я смотрю сериал по телевизору завтра.",
    "Я дивлюся серіал по телевізору завтра.",
    "Oglądam serial w telewizji jutro."
  ],
  [
    "I am flying to Tokyo tomorrow.",
    "Where are you flying tomorrow?",
    "Where do you fly every year?",
    "Where did you fly last year?",
    "Where will you fly next summer?",
    "Я лечу в Токио завтра.",
    "Я лечу до Токіо завтра.",
    "Lecę do Tokio jutro."
  ],
  [
    "I am choosing a dessert tomorrow.",
    "What are you choosing tomorrow?",
    "What do you choose every dinner?",
    "What did you choose last dinner?",
    "What will you choose next week?",
    "Я выбираю десерт завтра.",
    "Я вибираю десерт завтра.",
    "Wybieram deser jutro."
  ],
  [
    "I am visiting a museum tomorrow.",
    "What are you visiting tomorrow?",
    "What do you visit every vacation?",
    "What did you visit last weekend?",
    "What will you visit next holiday?",
    "Я посещаю музей завтра.",
    "Я відвідую музей завтра.",
    "Odwiedzam muzeum jutro."
  ],
  [
    "I am drawing a landscape tomorrow.",
    "What are you drawing tomorrow?",
    "What do you draw every class?",
    "What did you draw last lesson?",
    "What will you draw next month?",
    "Я рисую пейзаж завтра.",
    "Я малюю пейзаж завтра.",
    "Rysuję krajobraz jutro."
  ],
  [
    "I am buying shoes at the mall tomorrow.",
    "What are you buying at the mall tomorrow?",
    "What do you buy at the mall every month?",
    "What did you buy at the mall last week?",
    "What will you buy at the mall next season?",
    "Я покупаю обувь в торговом центре завтра.",
    "Я купую взуття в торговому центрі завтра.",
    "Kupuję buty w centrum handlowym jutro."
  ],
  [
    "I am eating cake at the cafe tomorrow.",
    "What are you eating at the cafe tomorrow?",
    "What do you eat at the cafe every week?",
    "What did you eat at the cafe last week?",
    "What will you eat at the cafe next month?",
    "Я ем торт в кафе завтра.",
    "Я їм торт у кафе завтра.",
    "Jem ciasto w kawiarni jutro."
  ],
  [
    "I am riding a horse tomorrow.",
    "Where are you riding tomorrow?",
    "Where do you ride every weekend?",
    "Where did you ride last summer?",
    "Where will you ride next month?",
    "Я катаюсь на лошади завтра.",
    "Я катаюся на коні завтра.",
    "Jeżdżę konno jutro."
  ],
  [
    "I am studying physics for the test tomorrow.",
    "What are you studying for the test tomorrow?",
    "What do you study every semester?",
    "What did you study last test?",
    "What will you study next exam?",
    "Я изучаю физику для теста завтра.",
    "Я вивчаю фізику для тесту завтра.",
    "Uczę się fizyki na test jutro."
  ],
  [
    "I am drinking coffee at the cafe tomorrow.",
    "What are you drinking at the cafe tomorrow?",
    "What do you drink at the cafe every morning?",
    "What did you drink at the cafe yesterday?",
    "What will you drink at the cafe next week?",
    "Я пью кофе в кафе завтра.",
    "Я п’ю каву в кафе завтра.",
    "Piję kawę w kawiarni jutro."
  ],
  [
    "I am making a salad for the family tomorrow.",
    "What are you making for the family tomorrow?",
    "What do you make for the family every holiday?",
    "What did you make for the family last holiday?",
    "What will you make for the family next celebration?",
    "Я готовлю салат для семьи завтра.",
    "Я готую салат для сім’ї завтра.",
    "Przygotowuję sałatkę dla rodziny jutro."
  ],
  [
    "I am camping by the lake tomorrow.",
    "Where are you camping tomorrow?",
    "Where do you camp every summer?",
    "Where did you camp last holiday?",
    "Where will you camp next vacation?",
    "Я разбиваю лагерь у озера завтра.",
    "Я розбиваю табір біля озера завтра.",
    "Rozbijam obóz nad jeziorem jutro."
  ],
  [
    "I am fixing the window tomorrow.",
    "What are you fixing tomorrow?",
    "What do you fix every month?",
    "What did you fix last week?",
    "What will you fix next year?",
    "Я чиню окно завтра.",
    "Я лагоджу вікно завтра.",
    "Naprawiam okno jutro."
  ],
  [
    "I am cleaning the kitchen tomorrow.",
    "What are you cleaning tomorrow?",
    "What do you clean every weekend?",
    "What did you clean yesterday?",
    "What will you clean next week?",
    "Я убираю кухню завтра.",
    "Я прибираю кухню завтра.",
    "Sprzątam kuchnię jutro."
  ],
  ["The train leaves at 10 o’clock.", "What time does the train leave?", "What time is the train leaving?", "What time will the train leave?", "What time did the train leave yesterday?", "Поезд отправляется в 10 часов.", "Поїзд відправляється о 10 годині.", "Pociąg odjeżdża o godzinie 10."],
  ["The film starts at 8 p.m.", "When does the film start?", "When is the film starting?", "When will the film start?", "When did the film start yesterday?", "Фильм начинается в 8 вечера.", "Фільм починається о 8 вечора.", "Film zaczyna się o 20."],
  ["The shop opens at 9 a.m.", "What time does the shop open?", "What time is the shop opening?", "What time will the shop open?", "What time did the shop open yesterday?", "Магазин открывается в 9 утра.", "Магазин відкривається о 9 ранку.", "Sklep otwiera się o 9."],
  ["The bus leaves at 7.30 a.m.", "What time does the bus leave?", "What time is the bus leaving?", "What time will the bus leave?", "What time did the bus leave yesterday?", "Автобус отправляется в 7:30 утра.", "Автобус відправляється о 7:30 ранку.", "Autobus odjeżdża o 7:30."],
  ["The lesson starts at 2 p.m.", "When does the lesson start?", "When is the lesson starting?", "When will the lesson start?", "When did the lesson start yesterday?", "Урок начинается в 2 часа дня.", "Урок починається о 14 годині.", "Lekcja zaczyna się o 14."],
  ["The train arrives at 6.45 p.m.", "What time does the train arrive?", "What time is the train arriving?", "What time will the train arrive?", "What time did the train arrive yesterday?", "Поезд прибывает в 18:45.", "Поїзд прибуває о 18:45.", "Pociąg przyjeżdża o 18:45."],
  ["The restaurant opens at 11 a.m.", "When does the restaurant open?", "When is the restaurant opening?", "When will the restaurant open?", "When did the restaurant open yesterday?", "Ресторан открывается в 11 утра.", "Ресторан відкривається о 11 ранку.", "Restauracja otwiera się o 11."],
  ["The cinema closes at 11 p.m.", "What time does the cinema close?", "What time is the cinema closing?", "What time will the cinema close?", "What time did the cinema close yesterday?", "Кинотеатр закрывается в 11 вечера.", "Кінотеатр зачиняється о 23 годині.", "Kino zamyka się o 23."],
  ["The flight departs at 3 p.m.", "What time does the flight depart?", "What time is the flight departing?", "What time will the flight depart?", "What time did the flight depart yesterday?", "Рейс отправляется в 3 часа дня.", "Рейс відправляється о 15 годині.", "Lot odlatuje o 15."],
  ["The bus arrives at 5.15 p.m.", "What time does the bus arrive?", "What time is the bus arriving?", "What time will the bus arrive?", "What time did the bus arrive yesterday?", "Автобус прибывает в 17:15.", "Автобус прибуває о 17:15.", "Autobus przyjeżdża o 17:15."],
  ["The meeting starts at 9 a.m.", "When does the meeting start?", "When is the meeting starting?", "When will the meeting start?", "When did the meeting start yesterday?", "Встреча начинается в 9 утра.", "Зустріч починається о 9 ранку.", "Spotkanie zaczyna się o 9."],
  ["The train departs at 12 noon.", "What time does the train depart?", "What time is the train departing?", "What time will the train depart?", "What time did the train depart yesterday?", "Поезд отправляется в полдень.", "Поїзд відправляється опівдні.", "Pociąg odjeżdża w południe."],
  ["The shop closes at 8 p.m.", "What time does the shop close?", "What time is the shop closing?", "What time will the shop close?", "What time did the shop close yesterday?", "Магазин закрывается в 8 вечера.", "Магазин зачиняється о 20 годині.", "Sklep zamyka się o 20."],
  ["The concert starts at 7 p.m.", "When does the concert start?", "When is the concert starting?", "When will the concert start?", "When did the concert start yesterday?", "Концерт начинается в 7 вечера.", "Концерт починається о 19 годині.", "Koncert zaczyna się o 19."],
  ["The ferry leaves at 6 a.m.", "What time does the ferry leave?", "What time is the ferry leaving?", "What time will the ferry leave?", "What time did the ferry leave yesterday?", "Паром отправляется в 6 утра.", "Паром відправляється о 6 ранку.", "Prom odpływa o 6."],
  ["The play starts at 8 p.m.", "When does the play start?", "When is the play starting?", "When will the play start?", "When did the play start yesterday?", "Пьеса начинается в 8 вечера.", "П'єса починається о 20 годині.", "Sztuka zaczyna się o 20."],
  ["The bus departs at 2 p.m.", "What time does the bus depart?", "What time is the bus departing?", "What time will the bus depart?", "What time did the bus depart yesterday?", "Автобус отправляется в 2 часа дня.", "Автобус відправляється о 14 годині.", "Autobus odjeżdża o 14."],
  ["The train arrives at 11 a.m.", "What time does the train arrive?", "What time is the train arriving?", "What time will the train arrive?", "What time did the train arrive yesterday?", "Поезд прибывает в 11 утра.", "Поїзд прибуває о 11 ранку.", "Pociąg przyjeżdża o 11."],
  ["The class starts at 10 a.m.", "When does the class start?", "When is the class starting?", "When will the class start?", "When did the class start yesterday?", "Урок начинается в 10 утра.", "Заняття починається о 10 ранку.", "Lekcja zaczyna się o 10."],
  ["The train leaves at 9.15 a.m.", "What time does the train leave?", "What time is the train leaving?", "What time will the train leave?", "What time did the train leave yesterday?", "Поезд отправляется в 9:15 утра.", "Поїзд відправляється о 9:15 ранку.", "Pociąg odjeżdża o 9:15."],
  ["The cinema opens at 10 a.m.", "What time does the cinema open?", "What time is the cinema opening?", "What time will the cinema open?", "What time did the cinema open yesterday?", "Кинотеатр открывается в 10 утра.", "Кінотеатр відкривається о 10 ранку.", "Kino otwiera się o 10."],
  ["The bus arrives at 8.30 a.m.", "What time does the bus arrive?", "What time is the bus arriving?", "What time will the bus arrive?", "What time did the bus arrive yesterday?", "Автобус прибывает в 8:30 утра.", "Автобус прибуває о 8:30 ранку.", "Autobus przyjeżdża o 8:30."],
  ["The lesson ends at 3 p.m.", "When does the lesson end?", "When is the lesson ending?", "When will the lesson end?", "When did the lesson end yesterday?", "Урок заканчивается в 3 часа дня.", "Урок закінчується о 15 годині.", "Lekcja kończy się o 15."],
  ["The train leaves at 1 p.m.", "What time does the train leave?", "What time is the train leaving?", "What time will the train leave?", "What time did the train leave yesterday?", "Поезд отправляется в 1 час дня.", "Поїзд відправляється о 13 годині.", "Pociąg odjeżdża o 13."],
 ["What time does the train leave?", "The train leaves at 10 o’clock.", "The train is leaving at 10 o’clock.", "The train will leave at 10 o’clock.", "The train left at 10 o’clock yesterday.", "Во сколько отправляется поезд?", "О котрій відправляється поїзд?", "O której odjeżdża pociąg?"],
  ["When does the film start?", "The film starts at 8 p.m.", "The film is starting at 8 p.m.", "The film will start at 8 p.m.", "The film started at 8 p.m. yesterday.", "Когда начинается фильм?", "Коли починається фільм?", "Kiedy zaczyna się film?"],
  ["What time does the shop open?", "The shop opens at 9 a.m.", "The shop is opening at 9 a.m.", "The shop will open at 9 a.m.", "The shop opened at 9 a.m. yesterday.", "Во сколько открывается магазин?", "О котрій відкривається магазин?", "O której otwiera się sklep?"],
  ["When does the bus leave?", "The bus leaves at 7:30 a.m.", "The bus is leaving at 7:30 a.m.", "The bus will leave at 7:30 a.m.", "The bus left at 7:30 a.m. yesterday.", "Когда отправляется автобус?", "Коли відправляється автобус?", "Kiedy odjeżdża autobus?"],
  ["When does the lesson start?", "The lesson starts at 2 p.m.", "The lesson is starting at 2 p.m.", "The lesson will start at 2 p.m.", "The lesson started at 2 p.m. yesterday.", "Когда начинается урок?", "Коли починається урок?", "Kiedy zaczyna się lekcja?"],
  ["What time does the train arrive?", "The train arrives at 6:45 p.m.", "The train is arriving at 6:45 p.m.", "The train will arrive at 6:45 p.m.", "The train arrived at 6:45 p.m. yesterday.", "Во сколько прибывает поезд?", "О котрій прибуває поїзд?", "O której przyjeżdża pociąg?"],
  ["When does the restaurant open?", "The restaurant opens at 11 a.m.", "The restaurant is opening at 11 a.m.", "The restaurant will open at 11 a.m.", "The restaurant opened at 11 a.m. yesterday.", "Когда открывается ресторан?", "Коли відкривається ресторан?", "Kiedy otwiera się restauracja?"],
  ["What time does the cinema close?", "The cinema closes at 11 p.m.", "The cinema is closing at 11 p.m.", "The cinema will close at 11 p.m.", "The cinema closed at 11 p.m. yesterday.", "Во сколько закрывается кинотеатр?", "О котрій зачиняється кінотеатр?", "O której zamyka się kino?"],
  ["When does the flight depart?", "The flight departs at 3 p.m.", "The flight is departing at 3 p.m.", "The flight will depart at 3 p.m.", "The flight departed at 3 p.m. yesterday.", "Когда отправляется рейс?", "Коли відправляється рейс?", "Kiedy odlatuje lot?"],
  ["What time does the bus arrive?", "The bus arrives at 5:15 p.m.", "The bus is arriving at 5:15 p.m.", "The bus will arrive at 5:15 p.m.", "The bus arrived at 5:15 p.m. yesterday.", "Во сколько прибывает автобус?", "О котрій прибуває автобус?", "O której przyjeżdża autobus?"],
  ["When does the meeting start?", "The meeting starts at 9 a.m.", "The meeting is starting at 9 a.m.", "The meeting will start at 9 a.m.", "The meeting started at 9 a.m. yesterday.", "Когда начинается встреча?", "Коли починається зустріч?", "Kiedy zaczyna się spotkanie?"],
  ["What time does the train depart?", "The train departs at 12 noon.", "The train is departing at 12 noon.", "The train will depart at 12 noon.", "The train departed at 12 noon yesterday.", "Во сколько отправляется поезд?", "О котрій відправляється поїзд?", "O której odjeżdża pociąg?"],
  ["When does the shop close?", "The shop closes at 8 p.m.", "The shop is closing at 8 p.m.", "The shop will close at 8 p.m.", "The shop closed at 8 p.m. yesterday.", "Когда закрывается магазин?", "Коли зачиняється магазин?", "Kiedy zamyka się sklep?"],
  ["When does the concert start?", "The concert starts at 7 p.m.", "The concert is starting at 7 p.m.", "The concert will start at 7 p.m.", "The concert started at 7 p.m. yesterday.", "Когда начинается концерт?", "Коли починається концерт?", "Kiedy zaczyna się koncert?"],
  ["What time does the ferry leave?", "The ferry leaves at 6 a.m.", "The ferry is leaving at 6 a.m.", "The ferry will leave at 6 a.m.", "The ferry left at 6 a.m. yesterday.", "Во сколько отплывает паром?", "О котрій відправляється пором?", "O której odpływa prom?"],
  ["When does the play start?", "The play starts at 8 p.m.", "The play is starting at 8 p.m.", "The play will start at 8 p.m.", "The play started at 8 p.m. yesterday.", "Когда начинается пьеса?", "Коли починається п'єса?", "Kiedy zaczyna się sztuka?"],
  ["What time does the bus depart?", "The bus departs at 2 p.m.", "The bus is departing at 2 p.m.", "The bus will depart at 2 p.m.", "The bus departed at 2 p.m. yesterday.", "Во сколько отправляется автобус?", "О котрій відправляється автобус?", "O której odjeżdża autobus?"],
  ["When does the train arrive?", "The train arrives at 11 a.m.", "The train is arriving at 11 a.m.", "The train will arrive at 11 a.m.", "The train arrived at 11 a.m. yesterday.", "Во сколько прибывает поезд?", "О котрій прибуває поїзд?", "O której przyjeżdża pociąg?"],
  ["When does the class start?", "The class starts at 10 a.m.", "The class is starting at 10 a.m.", "The class will start at 10 a.m.", "The class started at 10 a.m. yesterday.", "Когда начинается урок?", "Коли починається заняття?", "Kiedy zaczyna się lekcja?"],
  ["What time does the train leave?", "The train leaves at 9:15 a.m.", "The train is leaving at 9:15 a.m.", "The train will leave at 9:15 a.m.", "The train left at 9:15 a.m. yesterday.", "Во сколько отправляется поезд?", "О котрій відправляється поїзд?", "O której odjeżdża pociąg?"],
  ["When does the cinema open?", "The cinema opens at 10 a.m.", "The cinema is opening at 10 a.m.", "The cinema will open at 10 a.m.", "The cinema opened at 10 a.m. yesterday.", "Когда открывается кинотеатр?", "Коли відкривається кінотеатр?", "Kiedy otwiera się kino?"],
  ["What time does the bus arrive?", "The bus arrives at 8:30 a.m.", "The bus is arriving at 8:30 a.m.", "The bus will arrive at 8:30 a.m.", "The bus arrived at 8:30 a.m. yesterday.", "Во сколько прибывает автобус?", "О котрій прибуває автобус?", "O której przyjeżdża autobus?"],
  ["When does the lesson end?", "The lesson ends at 3 p.m.", "The lesson is ending at 3 p.m.", "The lesson will end at 3 p.m.", "The lesson ended at 3 p.m. yesterday.", "Когда заканчивается урок?", "Коли закінчується урок?", "Kiedy kończy się lekcja?"],
  ["What time does the train leave?", "The train leaves at 1 p.m.", "The train is leaving at 1 p.m.", "The train will leave at 1 p.m.", "The train left at 1 p.m. yesterday.", "Во сколько отправляется поезд?", "О котрій відправляється поїзд?", "O której odjeżdża pociąg?"],
  ["When does the shop open?", "The shop opens at 10 a.m.", "The shop is opening at 10 a.m.", "The shop will open at 10 a.m.", "The shop opened at 10 a.m. yesterday.", "Когда открывается магазин?", "Коли відкривається магазин?", "Kiedy otwiera się sklep?"],
  ["When does the movie start?", "The movie starts at 6 p.m.", "The movie is starting at 6 p.m.", "The movie will start at 6 p.m.", "The movie started at 6 p.m. yesterday.", "Когда начинается фильм?", "Коли починається фільм?", "Kiedy zaczyna się film?"],
  ["What time does the bus leave?", "The bus leaves at 7 a.m.", "The bus is leaving at 7 a.m.", "The bus will leave at 7 a.m.", "The bus left at 7 a.m. yesterday.", "Во сколько отправляется автобус?", "О котрій відправляється автобус?", "O której odjeżdża autobus?"],
  ["When does the restaurant close?", "The restaurant closes at 10 p.m.", "The restaurant is closing at 10 p.m.", "The restaurant will close at 10 p.m.", "The restaurant closed at 10 p.m. yesterday.", "Когда закрывается ресторан?", "Коли зачиняється ресторан?", "Kiedy zamyka się restauracja?"],
  ["When does the train arrive?", "The train arrives at 4 p.m.", "The train is arriving at 4 p.m.", "The train will arrive at 4 p.m.", "The train arrived at 4 p.m. yesterday.", "Во сколько прибывает поезд?", "О котрій прибуває поїзд?", "O której przyjeżdża pociąg?"],


];

    // Если это свойство есть, то оно попадает в заголовок теста
    unit25.nameLeson = "What are you doing tomorrow";

    //--созданными предложениями.
    unit25.lengthTrue = 5;