export const commonFood100pl = [
    ['appetizer', 'przystawka', 'deser', 'danie główne', 'napój', 'zakuska', 'zakuska', 'przystawka'],
    ['beverage', 'napój', 'jedzenie', 'zakuska', 'deser', 'napój', 'napój', 'napój'],
    ['buffet', 'bufet', 'obsługa', 'menu', 'a la carte', 'szwedzki stół', 'szwedzki stół', 'bufet'],
    ['chef', 'szef kuchni', 'kelner', 'pomocnik', 'barman', 'szef kuchni', 'szef kuchni', 'szef kuchni'],
    ['dish', 'danie', 'składnik', 'napój', 'deser', 'danie', 'danie', 'danie'],
    ['entree', 'danie główne', 'zakuska', 'deser', 'napój', 'danie główne', 'danie główne', 'danie główne'],
    ['ingredient', 'składnik', 'danie', 'napój', 'przyprawy', 'składnik', 'składnik', 'składnik'],
    ['menu', 'menu', 'rachunek', 'przepis', 'oferta specjalna', 'menu', 'menu', 'menu'],
    ['order', 'zamówienie', 'płatność', 'rezerwacja', 'inwentaryzacja', 'zamówienie', 'zamówienie', 'zamówienie'],
    ['plate', 'talerz', 'filiżanka', 'sztućce', 'kieliszek', 'talerz', 'talerz', 'talerz'],
    ['reservation', 'rezerwacja', 'rezerwowanie', 'zamówienie', 'płatność', 'rezerwacja', 'rezerwacja', 'rezerwacja'],
    ['service', 'obsługa', 'jedzenie', 'deser', 'rachunek', 'obsługa', 'obsługa', 'obsługa'],
    ['specialty', 'specjalność', 'zakuska', 'napój', 'deser', 'specjalność', 'specjalność', 'specjalność'],
    ['starter', 'przystawka', 'danie główne', 'deser', 'napój', 'przystawka', 'przystawka', 'przystawka'],
    ['table', 'stół', 'krzesło', 'menu', 'obsługa', 'stół', 'stół', 'stół'],
    ['taste', 'smak', 'aromat', 'tekstura', 'wygląd', 'smak', 'smak', 'smak'],
    ['waiter', 'kelner', 'szef kuchni', 'barman', 'klient', 'kelner', 'kelner', 'kelner'],
    ['waitress', 'kelnerka', 'szef kuchni', 'barman', 'klient', 'kelnerka', 'kelnerka', 'kelnerka'],
    ['wine', 'wino', 'piwo', 'woda', 'sok', 'wino', 'wino', 'wino'],
    ['baker', 'piekarz', 'szef kuchni', 'barman', 'kelner', 'piekarz', 'piekarz', 'piekarz'],
    ['barista', 'barista', 'szef kuchni', 'piekarz', 'kelner', 'barista', 'barista', 'barista'],
    ['beef', 'wołowina', 'kurczak', 'wieprzowina', 'ryba', 'wołowina', 'wołowina', 'wołowina'],
    ['bread', 'chleb', 'bułka', 'ciasto', 'muffin', 'chleb', 'chleb', 'chleb'],
    ['butter', 'masło', 'margaryna', 'woda', 'mleko', 'masło', 'masło', 'masło'],
    ['cheese', 'ser', 'chałwa', 'masło', 'jogurt', 'ser', 'ser', 'ser'],
    ['chicken', 'kurczak', 'wołowina', 'wieprzowina', 'ryba', 'kurczak', 'kurczak', 'kurczak'],
    ['coffee', 'kawa', 'herbata', 'woda', 'sok', 'kawa', 'kawa', 'kawa'],
    ['dessert', 'deser', 'danie główne', 'zakuska', 'napój', 'deser', 'deser', 'deser'],
    ['egg', 'jajko', 'mleko', 'ser', 'masło', 'jajko', 'jajko', 'jajko'],
    ['fish', 'ryba', 'mięso', 'drób', 'owoce morza', 'ryba', 'ryba', 'ryba'],
    ['flavor', 'smak', 'aromat', 'tekstura', 'wygląd', 'smak', 'smak', 'smak'],
    ['fruit', 'owoce', 'warzywa', 'mięso', 'produkty mleczne', 'owoce', 'owoce', 'owoce'],
    ['grill', 'grill', 'piekarnik', 'kuchenka', 'wielofunkcyjny', 'grill', 'grill', 'grill'],
    ['herb', 'zioła', 'przyprawy', 'warzywa', 'owoce', 'zioła', 'zioła', 'zioła'],
    ['lunch', 'obiad', 'śniadanie', 'kolacja', 'przekąska', 'obiad', 'obiad', 'lunch']
    ['meat', 'mięso', 'ryba', 'drób', 'owoce morza', 'mięso', 'mięso', 'mięso'],
    ['menu', 'menu', 'rachunek', 'przepis', 'oferta specjalna', 'menu', 'menu', 'menu'],
    ['noodle', 'makaron', 'ryż', 'pasta', 'chleb', 'lokshyna', 'lokshyna', 'makaron'],
    ['oil', 'olej', 'woda', 'ocet', 'sos sojowy', 'olija', 'olija', 'olej'],
    ['pasta', 'pasta', 'ryż', 'makaron', 'pasta', 'pasta', 'pasta', 'pasta'],
    ['pork', 'wieprzowina', 'wołowina', 'kurczak', 'ryba', 'wieprzowina', 'wieprzowina', 'wieprzowina'],
    ['rice', 'ryż', 'pasta', 'makaron', 'lokshyna', 'ryż', 'ryż', 'ryż'],
    ['salad', 'sałatka', 'zupa', 'przystawka', 'deser', 'sałatka', 'sałatka', 'sałatka'],
    ['salt', 'sól', 'cukier', 'pieprz', 'przyprawy', 'sól', 'sól', 'sól'],
    ['sandwich', 'kanapka', 'pizza', 'zupa', 'sałatka', 'kanapka', 'kanapka', 'kanapka'],
    ['sauce', 'sos', 'pasta', 'mięso', 'sałatka', 'sos', 'sos', 'sos'],
    ['seasoning', 'przyprawa', 'przyprawy', 'sos', 'deser', 'przyprawa', 'przyprawa', 'przyprawy'],
    ['snack', 'przekąska', 'danie główne', 'deser', 'napój', 'przekąska', 'przekąska', 'przekąska'],
    ['soup', 'zupa', 'sałatka', 'przystawka', 'deser', 'zupa', 'zupa', 'zupa'],
    ['spice', 'przyprawy', 'sól', 'cukier', 'olej', 'przyprawy', 'przyprawy', 'przyprawy'],
    ['steak', 'stek', 'hamburger', 'kurczak', 'kiełbaski', 'stek', 'stek', 'stek'],
    ['sugar', 'cukier', 'sól', 'miód', 'syrop', 'cukier', 'cukier', 'cukier'],
    ['tea', 'herbata', 'kawa', 'woda', 'sok', 'herbata', 'herbata', 'herbata'],
    ['treat', 'przekąska', 'danie główne', 'deser', 'napój', 'przekąska', 'przekąska', 'przekąska'],
    ['vegetable', 'warzywo', 'owoc', 'mięso', 'ryba', 'warzywo', 'warzywo', 'warzywo'],
    ['vinegar', 'ocet', 'olej', 'woda', 'sos sojowy', 'ocet', 'ocet', 'ocet'],
    ['wine', 'wino', 'piwo', 'woda', 'sok', 'wino', 'wino', 'wino'],
    ['wrap', 'wrap', 'pizza', 'zupa', 'sałatka', 'wrap', 'wrap', 'wrap'],
    ['yogurt', 'jogurt', 'mleko', 'ser', 'ser', 'jogurt', 'jogurt', 'jogurt'],
    ['beef', 'wołowina', 'kurczak', 'wieprzowina', 'ryba', 'wołowina', 'wołowina', 'wołowina'],
    ['butter', 'masło', 'margaryna', 'woda', 'mleko', 'masło', 'masło', 'masło'],
    ['cheese', 'ser', 'twarożek', 'masło', 'jogurt', 'ser', 'ser', 'ser'],
    ['dressing', 'sos', 'smak', 'składnik', 'przyprawa', 'sos', 'sos', 'sos'],
    ['eggplant', 'bakłażan', 'pomidor', 'papryka', 'ziemniak', 'bakłażan', 'bakłażan', 'bakłażan'],
    ['grape', 'winogrono', 'jabłko', 'gruszka', 'pomarańcza', 'winogrono', 'winogrono', 'winogrono'],
    ['ham', 'szynka', 'wieprzowina', 'kurczak', 'wołowina', 'szynka', 'szynka', 'szynka'],
    ['ice', 'lód', 'woda', 'sok', 'mleko', 'lód', 'lód', 'lód'],
    ['jam', 'dżem', 'miód', 'syrop', 'masło', 'dżem', 'dżem', 'dżem'],
    ['lemon', 'cytryna', 'pomarańcza', 'grejpfrut', 'limonka', 'cytryna', 'cytryna', 'cytryna'],
    ['meatloaf', 'klops', 'stek', 'klopsy', 'kiełbasa', 'klops', 'klops', 'klops'],
    ['mushroom', 'grzyb', 'warzywo', 'owoc', 'przyprawa', 'grzyb', 'grzyb', 'grzyb'],
    ['nut', 'orzech', 'owoce', 'warzywa', 'jagody', 'orzech', 'orzech', 'orzech'],
    ['olive', 'oliwka', 'grejpfrut', 'cytryna', 'jabłko', 'oliwka', 'oliwka', 'oliwka'],
    ['pancake', 'naleśnik', 'gofr', 'omlet', 'grzanka', 'naleśnik', 'naleśnik', 'naleśnik'],
    ['peanut', 'orzech ziemny', 'orzech', 'laskowy', 'migdał', 'orzech ziemny', 'orzech ziemny', 'orzech ziemny'],
    ['pepper', 'pieprz', 'sól', 'cukier', 'przyprawy', 'pieprz', 'pieprz', 'pieprz'],
    ['pie', 'ciasto', 'babeczka', 'ciasteczko', 'ciastko', 'ciasto', 'ciasto', 'ciasto'],
    ['pudding', 'pudding', 'lody', 'deser', 'krem', 'pudding', 'pudding', 'pudding'],
    ['quiche', 'tarta', 'ciasto', 'pizza', 'tarta', 'tarta', 'tarta', 'tarta'],
    ['rice', 'ryż', 'makaron', 'kluski', 'pasta', 'ryż', 'ryż', 'ryż'],
    ['scone', 'bułeczka', 'ciasto', 'ciasteczko', 'bułeczka', 'bułeczka', 'bułeczka', 'bułeczka'],
    ['soup', 'zupa', 'sałatka', 'przystawka', 'deser', 'zupa', 'zupa', 'zupa'],
    ['taco', 'taco', 'burrito', 'enchilada', 'fajita', 'taco', 'taco', 'taco'],
    ['toast', 'tost', 'chleb', 'naleśnik', 'grzanka', 'tost', 'tost', 'tost'],
    ['waffle', 'gofr', 'naleśnik', 'ciasto', 'babeczka', 'gofr', 'gofr', 'gofr'],
    ['zucchini', 'cukinia', 'pomidor', 'bakłażan', 'papryka', 'cukinia', 'cukinia', 'cukinia'],
    ['apple', 'jabłko', 'gruszka', 'pomarańcza', 'banan', 'jabłko', 'jabłko', 'jabłko'],
    ['bacon', 'bekon', 'wieprzowina', 'szynka', 'mięso', 'bekon', 'bekon', 'bekon'],
    ['barbecue', 'grill', 'grill', 'smażone', 'pizza', 'grill', 'grill', 'grill'],
    ['cake', 'tort', 'ciasto', 'babeczka', 'ciasteczko', 'tort', 'tort', 'tort'],
    ['carrot', 'marchew', 'pomidor', 'ogórek', 'burak', 'marchew', 'marchew', 'marchew'],
    ['cereal', 'kasza', 'mleko', 'chleb', 'jogurt', 'kasza', 'kasza', 'kasza'],
    ['chocolate', 'czekolada', 'kakao', 'cukierek', 'deser', 'czekolada', 'czekolada', 'czekolada'],
    ['cookie', 'ciastko', 'babeczka', 'ciasto', 'bułeczka', 'ciastko', 'ciastko', 'ciastko'],
    ['cucumber', 'ogórek', 'pomidor', 'papryka', 'marchew', 'ogórek', 'ogórek', 'ogórek'],
    ['cupcake', 'babeczka', 'ciasto', 'ciastko', 'naleśnik', 'babeczka', 'babeczka', 'babeczka'],
    ['dough', 'ciasto', 'chleb', 'ciastko', 'ciasto', 'ciasto', 'ciasto', 'ciasto'],
    ['fish', 'ryba', 'mięso', 'drób', 'owoce morza', 'ryba', 'ryba', 'ryba'],
    ['grape', 'winogrono', 'jabłko', 'gruszka', 'pomarańcza', 'winogrono', 'winogrono', 'winogrono'],
    ['ham', 'szynka', 'wieprzowina', 'kurczak', 'wołowina', 'szynka', 'szynka', 'szynka'],
    ['honey', 'miód', 'syrop', 'dżem', 'cukier', 'miód', 'miód', 'miód'],
    ['lettuce', 'sałata', 'pietruszka', 'koperek', 'szpinak', 'sałata', 'sałata', 'sałata'],
    ['mayo', 'majonez', 'ketchup', 'musztarda', 'sos', 'majonez', 'majonez', 'majonez'],
    ['noodles', 'makaron', 'pasta', 'ryż', 'kluseczki', 'makaron', 'makaron', 'makaron'],
    ['peach', 'brzoskwinia', 'jabłko', 'gruszka', 'śliwka', 'brzoskwinia', 'brzoskwinia', 'brzoskwinia'],
    ['syrup', 'syrop', 'miód', 'dżem', 'cukier', 'syrop', 'syrop', 'syrop'],
    ['tomato', 'pomidor', 'ogórek', 'papryka', 'marchew', 'pomidor', 'pomidor', 'pomidor']
];

    // Если это свойство есть, то оно попадает в заголовок теста
    commonFood100pl.nameLeson = "Food 100";
