export const commonSport100pl = [
        ['athlete', 'atleta', 'sportowiec', 'kulturysta', 'uczestnik', 'atleta', '', ''], 
        ['training', 'trening', 'przygotowanie', 'ćwiczenia', 'nauka', 'trening', '', ''], 
        ['exercise', 'ćwiczenie', 'fizykultura', 'trening', 'zajęcie', 'ćwiczenie', '', ''], 
        ['competition', 'zawody', 'konkurs', 'turniej', 'mecz', 'zawody', '', ''], 
        ['coach', 'trener', 'instruktor', 'menedżer', 'specjalista', 'trener', '', ''], 
        ['team', 'drużyna', 'grupa', 'skład', 'partnerzy', 'drużyna', '', ''], 
        ['sport', 'sport', 'dyscyplina sportowa', 'aktywność fizyczna', 'gra', 'sport', '', ''], 
        ['game', 'gra', 'mecz', 'zawody', 'turniej', 'gra', '', ''], ['player', 'gracz', 'sportowiec', 'uczestnik', 'gracz', 'gracz', '', ''], 
        ['goal', 'cel', 'gola', 'zadanie', 'punkt', 'cel', '', ''], ['score', 'wynik', 'rezultat', 'ocena', 'punkty', 'wynik', '', ''], 
        ['victory', 'zwycięstwo', 'sukces', 'triunf', 'triunf', 'zwycięstwo', '', ''], 
        ['defeat', 'porażka', 'niepowodzenie', 'klęska', 'przegapienie', 'porażka', '', ''], 
        ['championship', 'mistrzostwa', 'turniej', 'pierwszeństwo', 'zawody', 'mistrzostwa', '', ''], 
        ['fitness', 'fitness', 'plastyka', 'prowadzenie', 'przygotowanie', 'fitness', '', ''], 
        ['yoga', 'joga', 'gimnastyka', 'ćwiczenia', 'praktyka', 'joga', '', ''],
        ['running', 'bieganie', 'przebieżka', 'sprint', 'dystans', 'bieganie', '', ''], 
        ['cycling', 'kolarstwo', 'jazda na rowerze', 'wyścig rowerowy', 'rower', 'kolarstwo', '', ''], 
        ['swimming', 'pływanie', 'zabiegi wodne', 'pływanie', 'spływ', 'pływanie', '', ''],
        ['basketball', 'koszykówka', 'gra', 'sport', 'zawody', 'koszykówka', '', ''], 
        ['soccer', 'piłka nożna', 'gra', 'mecz', 'sport', 'piłka nożna', '', ''], 
        ['tennis', 'tenis', 'gra', 'serwis', 'piłka tenisowa', 'tenis', '', ''], 
        ['golf', 'golf', 'gra', 'dublet', 'piłka', 'golf', '', ''],
        ['boxing', 'boks', 'pojedynek', 'walka', 'partia', 'boks', '', ''], 
        ['wrestling', 'zapasy', 'mecz', 'walka', 'pojedynek', 'zapasy', '', ''],
        ['skiing', 'narciarstwo', 'narciarski sport', 'zjazd', 'wspinaczka', 'narciarstwo', '', ''], 
        ['snowboarding', 'snowboarding', 'deska do snowboardu', 'sport', 'jazda', 'snowboarding', '', ''], 
        ['surfing', 'surfing', 'fale', 'jazda', 'sport wodny', 'surfing', '', ''],
        ['hiking', 'wędrówka', 'spacer', 'turystyka piesza', 'trasa', 'wędrówka', '', ''], 
        ['climbing', 'wspinaczka', 'wspinaczka', 'alpinizm', 'trening', 'wspinaczka', '', ''], 
        ['gymnastics', 'gimnastyka', 'ćwiczenia', 'trening', 'sport', 'gimnastyka', '', ''],
        ['weightlifting', 'podnoszenie ciężarów', 'trening', 'sport', 'sport', 'podnoszenie ciężarów', '', ''], 
        ['martial arts', 'sztuki walki', 'sambo', 'judo', 'karate', 'sztuki walki', '', ''], 
        ['karate', 'karate', 'sztuka walki', 'trening', 'pojedynek', 'karate', '', ''], 
        ['judo', 'judo', 'sztuka walki', 'sport', 'pojedynek', 'judo', '', ''], 
        ['taekwondo', 'taekwondo', 'sztuka walki', 'trening', 'pojedynek', 'taekwondo', '', ''], 
        ['fencing', 'szermierka', 'pojedynek', 'sport', 'trening', 'szermierka', '', ''], 
        ['dancing', 'taniec', 'choreografia', 'plastyka', 'nauka', 'taniec', '', ''], 
        ['cheerleading', 'cheerleading', 'występ grupowy', 'taniec', 'wsparcie', 'cheerleading', '', ''],
        ['rowing', 'wioślarstwo', 'sport wioślarski', 'trening', 'sport wodny', 'wioślarstwo', '', ''], 
        ['sailing', 'żeglarstwo', 'pływanie', 'regaty', 'trening', 'żeglarstwo', '', ''], 
        ['skating', 'łyżwiarstwo', 'łyżwiarstwo figurowe', 'sportowe łyżwiarstwo', 'trening', 'łyżwiarstwo', '', ''],
        ['rollerblading', 'jazda na rolkach', 'rolki', 'trening', 'sport', 'jazda na rolkach', '', ''],
        ['baseball', 'baseball', 'gra', 'sport', 'drużyna', 'baseball', '', ''],
        ['volleyball', 'siatkówka', 'gra', 'sport drużynowy', 'trening', 'siatkówka', '', ''],
        ['handball', 'piłka ręczna', 'gra', 'sport', 'drużyna', 'piłka ręczna', '', ''],
        ['rugby', 'rugby', 'gra', 'sport', 'sport drużynowy', 'rugby', '', ''],
        ['cricket', 'kricket', 'gra', 'sport', 'drużyna', 'kricket', '', ''],
        ['ultimate frisbee', 'frisbee', 'gra', 'sport', 'sport drużynowy', 'frisbee', '', ''],
        ['golf', 'golf', 'gra', 'sport', 'pole', 'golf', '', ''],
        ['triathlon', 'triathlon', 'wielobój', 'zawody sportowe', 'trening', 'triathlon', '', ''],
        ['marathon', 'maraton', 'bieg', 'dystans', 'zawody', 'maraton', '', ''],
        ['crossfit', 'crossfit', 'trening', 'ćwiczenia', 'sport', 'crossfit', '', ''],
        ['yoga', 'joga', 'ćwiczenia', 'fitness', 'trening', 'joga', '', ''],
        ['pilates', 'pilates', 'ćwiczenia', 'fitness', 'trening', 'pilates', '', ''],
        ['stretching', 'rozciąganie', 'ćwiczenia', 'trening', 'fitness', 'rozciąganie', '', ''],
        ['balance', 'równowaga', 'ćwiczenia', 'trening', 'sprzęt sportowy', 'równowaga', '', ''],
        ['speed', 'prędkość', 'trening', 'ćwiczenie', 'wydajność', 'prędkość', '', ''],
        ['endurance', 'wytrzymałość', 'trening', 'ćwiczenia', 'sport', 'wytrzymałość', '', ''],
        ['strength', 'siła', 'trening', 'ćwiczenia', 'fitness', 'siła', '', ''],
        ['flexibility', 'elastyczność', 'ćwiczenia', 'trening', 'fitness', 'elastyczność', '', ''],
        ['power', 'moc', 'trening', 'ćwiczenia', 'sport', 'moc', '', ''],
        ['conditioning', 'przygotowanie', 'trening', 'ćwiczenia', 'sport', 'przygotowanie', '', ''],
        ['performance', 'wystąpienie', 'osiągnięcia', 'trening', 'wyniki sportowe', 'wystąpienie', '', ''],
        ['recovery', 'regeneracja', 'odpoczynek', 'trening', 'rehabilitacja', 'regeneracja', '', ''],
        ['nutrition', 'odżywianie', 'dieta', 'racjonalne żywienie', 'zdrowe odżywianie', 'odżywianie', '', ''],
        ['hydration', 'nawodnienie', 'woda', 'spożycie wody', 'regeneracja', 'nawodnienie', '', ''],
        ['athlete', 'atleta', 'sportowiec', 'osoba uprawiająca sport', 'uczestnik', 'atleta', '', ''],
        ['training', 'trening', 'przygotowanie', 'ćwiczenia', 'nauka', 'trening', '', ''],
        ['exercise', 'ćwiczenie', 'fizyczne', 'trening', 'zajęcia', 'ćwiczenie', '', ''],
        ['competition', 'zawody', 'konkurs', 'turniej', 'mecz', 'zawody', '', ''],
        ['coach', 'trener', 'instruktor', 'menedżer', 'specjalista', 'trener', '', ''],
        ['team', 'drużyna', 'grupa', 'skład', 'partnerzy', 'drużyna', '', ''],
        ['sport', 'sport', 'dyscyplina sportowa', 'aktywność fizyczna', 'gra', 'sport', '', ''],
        ['game', 'gra', 'mecz', 'zawody', 'turniej', 'gra', '', ''],
        ['player', 'gracz', 'sportowiec', 'uczestnik', 'gracz', 'gracz', '', ''],
        ['goal', 'cel', 'bramka', 'zadanie', 'znacznik', 'cel', '', ''],
        ['score', 'wynik', 'rezultat', 'ocena', 'punkty', 'wynik', '', ''],
        ['victory', 'zwycięstwo', 'sukces', 'triuf', 'triuf', 'zwycięstwo', '', ''],
        ['defeat', 'porażka', 'niepowodzenie', 'klapa', 'przegapienie', 'porażka', '', ''],
        ['championship', 'mistrzostwa', 'turniej', 'pierwszeństwo', 'zawody', 'mistrzostwa', '', ''],
        ['fitness', 'fitness', 'plastyka', 'przeprowadzenie', 'przygotowanie', 'fitness', '', ''],
        ['yoga', 'joga', 'gimnastyka', 'ćwiczenia', 'praktyka', 'joga', '', ''],
        ['running', 'bieg', 'bieganie', 'sprint', 'dystans', 'bieg', '', ''],
        ['cycling', 'kolarstwo', 'jazda na rowerze', 'wyścig rowerowy', 'rower', 'kolarstwo', '', ''],
        ['swimming', 'pływanie', 'zabiegi wodne', 'pływanie', 'spływ', 'pływanie', '', ''],
        ['basketball', 'koszykówka', 'gra', 'sport', 'zawody', 'koszykówka', '', ''],
        ['soccer', 'piłka nożna', 'gra', 'mecz', 'sport', 'piłka nożna', '', ''],
        ['tennis', 'tenis', 'gra', 'serwis', 'piłka tenisowa', 'tenis', '', ''],
        ['golf', 'golf', 'gra', 'dublet', 'piłka', 'golf', '', ''],
        ['boxing', 'boks', 'pojedynek', 'walka', 'partia', 'boks', '', ''],
        ['wrestling', 'zapaśnictwo', 'mecz', 'walka', 'pojedynek', 'zapaśnictwo', '', ''],
        ['skiing', 'narciarstwo', 'narciarstwo', 'zjazd', 'wzniesienie', 'narciarstwo', '', ''],
        ['snowboarding', 'snowboarding', 'deska snowboardowa', 'sport', 'jazda', 'snowboarding', '', ''],
        ['surfing', 'surfing', 'deska do surfingu', 'jazda', 'sport wodny', 'surfing', '', ''],
        ['hiking', 'wędrówka', 'spacer', 'turystyka piesza', 'szlak', 'wędrówka', '', ''],
        ['climbing', 'wspinaczka', 'wspinaczka', 'alpinistyka', 'trening', 'wspinaczka', '', ''],
        ['gymnastics', 'gimnastyka', 'ćwiczenia', 'trening', 'sport', 'gimnastyka', '', ''],
        ['weightlifting', 'podnoszenie ciężarów', 'podnoszenie ciężarów', 'trening', 'sport', 'podnoszenie ciężarów', '', ''],
        ['martial arts', 'sztuki walki', 'sambo', 'judo', 'karate', 'sztuki walki', '', ''],
        ['karate', 'karate', 'sztuka walki', 'trening', 'pojedynek', 'karate', '', ''],
        ['judo', 'judo', 'sztuka walki', 'sport', 'pojedynek', 'judo', '', ''],
        ['taekwondo', 'taekwondo', 'sztuka walki', 'trening', 'pojedynek', 'taekwondo', '', ''],
        ['fencing', 'szermierka', 'walka', 'sport', 'trening', 'szermierka', '', ''],
        ['dancing', 'taniec', 'choreografia', 'plastyka', 'nauka', 'taniec', '', ''],
        ['cheerleading', 'cheerleading', 'grupowe wystąpienie', 'taniec', 'wsparcie', 'cheerleading', '', ''],
        ['rowing', 'wioślarstwo', 'sport wioślarski', 'trening', 'sport wodny', 'wioślarstwo', '', ''],
        ['sailing', 'żeglarstwo', 'pływanie', 'regaty', 'trening', 'żeglarstwo', '', ''],
        ['skating', 'łyżwiarstwo', 'łyżwiarstwo figurowe', 'sport', 'trening', 'łyżwiarstwo', '', ''],
        ['rollerblading', 'jazda na rolkach', 'rolki', 'trening', 'sport', 'jazda na rolkach', '', ''],
        ['baseball', 'bejsbol', 'gra', 'sport', 'drużyna', 'bejsbol', '', ''],
        ['volleyball', 'siatkówka', 'gra', 'sport drużynowy', 'trening', 'siatkówka', '', ''],
        ['handball', 'piłka ręczna', 'gra', 'sport', 'drużyna', 'piłka ręczna', '', ''],
        ['rugby', 'rugby', 'gra', 'sport', 'sport drużynowy', 'rugby', '', ''],
        ['cricket', 'krykiet', 'gra', 'sport', 'drużyna', 'krykiet', '', ''],
        ['ultimate frisbee', 'frisbee', 'gra', 'sport', 'sport drużynowy', 'frisbee', '', ''],
        ['golf', 'golf', 'gra', 'sport', 'pole', 'golf', '', ''],
        ['triathlon', 'triatlon', 'wielobój', 'zawody sportowe', 'trening', 'triatlon', '', ''],
        ['marathon', 'maraton', 'bieg', 'dystans', 'zawody', 'maraton', '', ''],
        ['crossfit', 'crossfit', 'trening', 'ćwiczenia', 'sport', 'crossfit', '', ''],
        ['yoga', 'joga', 'ćwiczenia', 'fitness', 'trening', 'joga', '', ''],
        ['pilates', 'pilates', 'ćwiczenia', 'fitness', 'trening', 'pilates', '', ''],
        ['stretching', 'rozciąganie', 'ćwiczenia', 'trening', 'fitness', 'rozciąganie', '', ''],
];

// этот код добавляет правильный перевод - это индекс 1 на место с 
// индексом 5, оттуда движек использует это значение
// это вместо того, чтобы заполнить это с помощью чата джипити
// такой фокус с переводом на украинский и польский не получится,
// нужен новый массив
commonSport100pl.forEach((el, index, array) => {
        array[index][7] = el[1];
      });

// Если это свойство есть, то оно попадает в заголовок теста
commonSport100pl.nameLeson = "Sport 100";
