// Массив для задания Вставить правильное слово.

export const whereThat = [
    ["... is the library?", "where", "what", "who", "how", "Где находится библиотека?", "Де знаходиться бібліотека?", "Gdzie jest biblioteka?"],
    ["... are you doing?", "what", "who", "where", "why", "Что ты делаешь?", "Що ти робиш?", "Co robisz?"],
    ["... is that?", "who", "where", "what", "how", "Кто это?", "Хто це?", "Kim jest?"],
    ["... do you do that?", "how", "where", "what", "who", "Как ты это делаешь?", "Як ти це робиш?", "Jak to robisz?"],
    ["... are you late?", "why", "how", "where", "who", "Почему ты опоздал?", "Чому ти запізнився?", "Dlaczego się spóźniłeś?"],
    ["... is your favorite color?", "what", "where", "who", "how", "Какой твой любимый цвет?", "Який твій улюблений колір?", "Jaki jest twój ulubiony kolor?"],
    ["... are you going?", "where", "what", "who", "why", "Куда ты идёшь?", "Куди ти йдеш?", "Gdzie idziesz?"],
    ["... is your name?", "what", "where", "who", "how", "Как тебя зовут?", "Як тебе звати?", "Jak masz na imię?"],
    ["... are they?", "who", "where", "what", "why", "Кто они?", "Хто вони?", "Kim są?"],
    ["... did you come?", "how", "where", "what", "who", "Как ты пришёл?", "Як ти прийшов?", "Jak przyszedłeś?"],
    ["... is this book about?", "what", "where", "who", "how", "О чем эта книга?", "Про що ця книга?", "O czym jest ta książka?"],
    ["... are you from?", "where", "who", "what", "how", "Откуда ты?", "Звідки ти?", "Skąd jesteś?"],
    ["... is the time?", "what", "where", "who", "why", "Который час?", "Котра година?", "Która godzina?"],
    ["... did you do that?", "how", "where", "what", "who", "Как ты это сделал?", "Як ти це зробив?", "Jak to zrobiłeś?"],
    ["... do you feel?", "how", "where", "what", "who", "Как ты себя чувствуешь?", "Як ти себе почуваєш?", "Jak się czujesz?"],
    ["... is the weather like?", "what", "where", "who", "how", "Какая погода?", "Яка погода?", "Jaka jest pogoda?"],
    ["... are your keys?", "where", "what", "who", "how", "Где твои ключи?", "Де твої ключі?", "Gdzie są twoje klucze?"],
    ["... is the movie?", "what", "where", "who", "how", "Какой фильм?", "Який фільм?", "Jaki film?"],
    ["... did you sleep?", "how", "where", "what", "who", "Как ты спал?", "Як ти спав?", "Jak spałeś?"],
    ["... do you think?", "what", "where", "who", "how", "Что ты думаешь?", "Що ти думаєш?", "Co myślisz?"],
    ["... are you laughing?", "why", "how", "where", "who", "Почему ты смеешься?", "Чому ти смієшся?", "Dlaczego się śmiejesz?"],
    ["... is the shop?", "where", "what", "who", "how", "Где магазин?", "Де магазин?", "Gdzie jest sklep?"],
    ["... did you learn?", "what", "where", "who", "how", "Чему ты научился?", "Чому ти навчився?", "Czego się nauczyłeś?"],
    ["... are you crying?", "why", "how", "where", "who", "Почему ты плачешь?", "Чому ти плачеш?", "Dlaczego płaczesz?"],
    ["... do you want?", "what", "where", "who", "why", "Чего ты хочешь?", "Чого ти хочеш?", "Czego chcesz?"],
    ["... is your phone?", "where", "what", "who", "how", "Где твой телефон?", "Де твій телефон?", "Gdzie jest twój telefon?"],
    ["... did you find this?", "where", "what", "who", "how", "Где ты это нашел?", "Де ти це знайшов?", "Gdzie to znalazłeś?"],
    ["... is he?", "who", "where", "what", "how", "Кто он?", "Хто він?", "Kim on jest?"],
    ["... can I buy this?", "where", "what", "who", "how", "Где я могу это купить?", "Де я можу це купити?", "Gdzie mogę to kupić?"],
    ["... does it work?", "how", "where", "what", "who", "Как это работает?", "Як це працює?", "Jak to działa?"],
    ["... did you eat?", "what", "where", "who", "how", "Что ты ел?", "Що ти їв?", "Co jadłeś?"],
    ["... is your car?", "where", "what", "who", "how", "Где твоя машина?", "Де твоя машина?", "Gdzie jest twój samochód?"],
    ["... did you go?", "where", "what", "who", "how", "Куда ты пошёл?", "Куди ти пішов?", "Gdzie poszedłeś?"],
    ["... is this place?", "what", "where", "who", "how", "Что это за место?", "Що це за місце?", "Co to za miejsce?"],
    ["... is that sound?", "what", "where", "who", "how", "Что это за звук?", "Що це за звук?", "Co to za dźwięk?"],
    ["... did you get here?", "how", "where", "what", "who", "Как ты сюда попал?", "Як ти сюди потрапив?", "Jak tu trafiłeś?"],
    ["... is the next train?", "when", "where", "what", "how", "Когда следующий поезд?", "Коли наступний потяг?", "Kiedy jest następny pociąg?"],
    ["... are you?", "who", "what", "where", "how", "Кто ты?", "Хто ти?", "Kim jesteś?"],
    ["... does this cost?", "how much", "where", "what", "who", "Сколько это стоит?", "Скільки це коштує?", "Ile to kosztuje?"],
    ["... did it happen?", "how", "where", "what", "who", "Как это произошло?", "Як це сталося?", "Jak to się stało?"],
    ["... is the nearest hospital?", "where", "what", "who", "how", "Где ближайшая больница?", "Де найближча лікарня?", "Gdzie jest najbliższy szpital?"],
    ["... do you feel today?", "how", "where", "what", "who", "Как ты себя чувствуешь сегодня?", "Як ти себе почуваєш сьогодні?", "Jak się dziś czujesz?"],
    ["... is she?", "who", "where", "what", "how", "Кто она?", "Хто вона?", "Kim ona jest?"],
    ["... is the best restaurant?", "where", "what", "who", "how", "Где лучший ресторан?", "Де найкращий ресторан?", "Gdzie jest najlepsza restauracja?"],
    ["... are you here?", "why", "where", "what", "how", "Почему ты здесь?", "Чому ти тут?", "Dlaczego tu jesteś?"],
    ["... is this?", "what", "where", "who", "how", "Что это?", "Що це?", "Co to jest?"],
    ["... did you arrive?", "when", "where", "what", "how", "Когда ты приехал?", "Коли ти приїхав?", "Kiedy przyjechałeś?"],
    ["... is your birthday?", "when", "where", "what", "how", "Когда твой день рождения?", "Коли твій день народження?", "Kiedy są twoje urodziny?"],
    ["... is it?", "what", "where", "who", "how", "Что это?", "Що це?", "Co to jest?"],
    ["... do you want to eat?", "what", "where", "who", "how", "Что ты хочешь съесть?", "Що ти хочеш з'їсти?", "Co chcesz zjeść?"],
    ["... do you usually wake up?", "when", "where", "what", "how", "Когда ты обычно просыпаешься?", "Коли ти зазвичай прокидаєшся?", "Kiedy zwykle wstajesz?"],
    ["... is this problem?", "what", "where", "who", "how", "Что это за проблема?", "Що це за проблема?", "Co to za problem?"],
    ["... is the bus stop?", "where", "what", "who", "how", "Где автобусная остановка?", "Де автобусна зупинка?", "Gdzie jest przystanek autobusowy?"],
    ["... are you worried?", "why", "where", "what", "how", "Почему ты волнуешься?", "Чому ти хвилюєшся?", "Dlaczego się martwisz?"],
    ["... is your home?", "where", "what", "who", "how", "Где твой дом?", "Де твій дім?", "Gdzie jest twój dom?"],
    ["... do you work?", "where", "what", "who", "how", "Где ты работаешь?", "Де ти працюєш?", "Gdzie pracujesz?"],
    ["... is your house?", "where", "what", "who", "how", "Где твой дом?", "Де твій дім?", "Gdzie jest twój dom?"],
    ["... are you tired?", "why", "where", "what", "how", "Почему ты устал?", "Чому ти втомився?", "Dlaczego jesteś zmęczony?"],
    ["... did you wake up?", "when", "where", "what", "how", "Когда ты проснулся?", "Коли ти прокинувся?", "Kiedy wstałeś?"],
    ["... is the coffee?", "where", "what", "who", "how", "Где кофе?", "Де кава?", "Gdzie jest kawa?"],
    ["... do you love?", "who", "where", "what", "how", "Кого ты любишь?", "Кого ти любиш?", "Kogo kochasz?"],
    ["... are you so happy?", "why", "where", "what", "how", "Почему ты так счастлив?", "Чому ти такий щасливий?", "Dlaczego jesteś taki szczęśliwy?"],
    ["... is your favorite book?", "what", "where", "who", "how", "Какая твоя любимая книга?", "Яка твоя улюблена книга?", "Jaka jest twoja ulubiona książka?"],
    ["... is the train station?", "where", "what", "who", "how", "Где вокзал?", "Де вокзал?", "Gdzie jest dworzec?"],
    ["... did you buy that?", "where", "what", "who", "how", "Где ты это купил?", "Де ти це купив?", "Gdzie to kupiłeś?"],
    ["... do you go to school?", "when", "where", "what", "how", "Когда ты ходишь в школу?", "Коли ти ходиш до школи?", "Kiedy chodzisz do szkoły?"],
    ["... does he live?", "where", "what", "who", "how", "Где он живёт?", "Де він живе?", "Gdzie on mieszka?"],
    ["... is your best friend?", "who", "where", "what", "how", "Кто твой лучший друг?", "Хто твій найкращий друг?", "Kim jest twój najlepszy przyjaciel?"],
    ["... did you start?", "when", "where", "what", "how", "Когда ты начал?", "Коли ти почав?", "Kiedy zacząłeś?"],
    ["... is this street?", "what", "where", "who", "how", "Что это за улица?", "Що це за вулиця?", "Co to za ulica?"],
    ["... did you finish?", "when", "where", "what", "how", "Когда ты закончил?", "Коли ти закінчив?", "Kiedy skończyłeś?"],
    ["... are your shoes?", "where", "what", "who", "how", "Где твои туфли?", "Де твої туфлі?", "Gdzie są twoje buty?"],
    ["... is this called?", "what", "where", "who", "how", "Как это называется?", "Як це називається?", "Jak to się nazywa?"],
    ["... is the bus?", "where", "what", "who", "how", "Где автобус?", "Де автобус?", "Gdzie jest autobus?"],
    ["... do you like to travel?", "where", "what", "who", "how", "Где тебе нравится путешествовать?", "Де тобі подобається подорожувати?", "Gdzie lubisz podróżować?"],
    function (id) {
        let str1 = whereThat[id][0];
        let str2 = whereThat[id][1];
        str1 = str1.replace('...', str2);
        return str1;
    }
]

// Если это свойство есть, то оно попадает в заголовок теста
whereThat.nameLeson = "Where/That...";
