const toBeForms = [
    ['I am', "I'm", 'Im', 'Iam', 'I am', 'Я есть', 'Я є', 'Jestem'],
    ['I am not', "I'm not", 'Im not', 'Iamnot', 'I amnot', 'Я не есть', 'Я не є', 'Nie jestem'],
    ['You are', "You're", 'Your', 'Youre', 'You ar', 'Ты есть', 'Ти є', 'Ty jesteś'],
    ['You are not', "You aren't", 'Your not', 'You arent', 'You arnt', 'Ты не есть', 'Ти не є', 'Nie jesteś'],
    ['You are not', "You're not", 'Your not', 'Youre not', 'You arnt', 'Ты не есть', 'Ти не є', 'Nie jesteś'],
    ['He is', "He's", 'Hes', 'Heis', 'Heis', 'Он есть', 'Він є', 'On jest'],
    ['He is not', "He isn't", 'Hes not', 'He isnt', 'He isnt', 'Он не есть', 'Він не є', 'On nie jest'],
    ['He is not', "He's not", 'Hes not', 'He is not', 'He isnot', 'Он не есть', 'Він не є', 'On nie jest'],
    ['She is', "She's", 'Shes', 'Sheis', 'Sheis', 'Она есть', 'Вона є', 'Ona jest'],
    ['She is not', "She isn't", 'Shes not', 'She isnt', 'She isnt', 'Она не есть', 'Вона не є', 'Ona nie jest'],
    ['She is not', "She's not", 'Shes not', 'She is not', 'She isnot', 'Она не есть', 'Вона не є', 'Ona nie jest'],
    ['It is', "It's", 'Its', 'Itis', 'Itis', 'Это есть', 'Це є', 'To jest'],
    ['It is not', "It isn't", 'Its not', 'It isnt', 'It isnt', 'Это не есть', 'Це не є', 'To nie jest'],
    ['It is not', "It's not", 'Its not', 'It is not', 'It isnot', 'Это не есть', 'Це не є', 'To nie jest'],
    ['We are', "We're", 'We are', 'Weare', 'We re', 'Мы есть', 'Ми є', 'My jesteśmy'],
    ['We are not', "We aren't", 'We are not', 'We arent', 'We arent', 'Мы не есть', 'Ми не є', 'Nie jesteśmy'],
    ['We are not', "We're not", 'We are not', 'We re not', 'We arenot', 'Мы не есть', 'Ми не є', 'Nie jesteśmy'],
    ['They are', "They're", 'Theyre', 'They are', 'They re', 'Они есть', 'Вони є', 'Oni są'],
    ['They are not', "They aren't", 'Theyre not', 'They arent', 'They arnt', 'Они не есть', 'Вони не є', 'Oni nie są'],
    ['They are not', "They're not", 'Theyre not', 'They are not', 'They arenot', 'Они не есть', 'Вони не є', 'Oni nie są']
];
